	; Strings to accompany cutthroats/cutthroats.zap

	.GSTR STR?568,""
	.GSTR STR?569,"  "
	.GSTR STR?570,"    "
	.GSTR STR?571,"      "
	.GSTR STR?572,"        "
	.GSTR STR?573,"          "
	.GSTR STR?0," a transcript of interaction with CUTTHROATS.
CUTTHROATS is a registered trademark of Infocom, Inc.
Copyright (c) 1984, Infocom, Inc. All rights reserved.
"
	.GSTR STR?583," doesn't seem to work."
	.GSTR STR?585," doesn't work."
	.GSTR STR?586," has no effect."
	.GSTR STR?384," He"
	.GSTR STR?584," isn't notably helpful."
	.GSTR STR?265," items"
	.GSTR STR?210," knocks you out. About all you feel after that is a cold knife drawing warm blood from your throat."
	.GSTR STR?457," swims up to you and starts nibbling."
	.GSTR STR?197," that you kill yourself, just as he would have done!"
	.GSTR STR?274," The canister begins to emit noxious fumes. Before you can do anything about it, you lose consciousness."
	.GSTR STR?4," There are spare parts for the engine and other equipment scattered about."
	.GSTR STR?371," to take with you"
	.GSTR STR?6," wedged under the bunks."
	.GSTR STR?374,", dragging the chest up with it."
	.GSTR STR?225,", pushing his cart"
	.GSTR STR?375,"."
	.GSTR STR?610,"""After due consideration, I find myself in an embarrassing position. I would gladly accept a hard biscuit today, if you would accept payment Tuesday."""
	.GSTR STR?519,"""Ajax 9-volt dry cell."""
	.GSTR STR?520,"""Ajax C cell."""
	.GSTR STR?608,"""As my Pappy said, 'When you travel the highways of life, you do not always get to stop and look at a roadmap.'"""
	.GSTR STR?612,"""Compared to salted biscuits, I like myself best."""
	.GSTR STR?613,"""Hello Sailor."""
	.GSTR STR?609,"""I must admit that in my wide travels across this ball of wax, I have seen many human specimens, though none quite like you."""
	.GSTR STR?231,"""No, you don't!"" cries McGinty as he pulls out a gun and shoots you."
	.GSTR STR?611,"""Read any good books lately? I found 'Tropical Birds and their Native Habitats' quite engrossing."""
	.GSTR STR?389,"""Thanks for the info, pal, but I better make sure you don't use it."" He pulls out his gun and shoots."
	.GSTR STR?412,"""That's one of McGinty's envelopes! Traitor!"" Before you can respond, the Weasel's knife has violated the sanctity of your body."
	.GSTR STR?7,"""Tie the line to the treasure when you've got it, then pull on it and we'll pull the treasure up."""
	.GSTR STR?440,"""What kind of joke is this, giving me the coordinates of the island?"""
	.GSTR STR?438,"""You brought McGinty!"" Next thing you know, your throat's been slit."
	.GSTR STR?277,"A bartender behind the bar polishes glasses with a worn towel."
	.GSTR STR?507,"A comfortable bed sits along the wall."
	.GSTR STR?565,"A desk clerk is sitting behind the counter."
	.GSTR STR?237,"A desk clerk sits behind the counter."
	.GSTR STR?305,"a ferry token"
	.GSTR STR?592,"A fishy idea..."
	.GSTR STR?393,"A moment later, McGinty sticks his head out, asks why you were in his place, and shoots you."
	.GSTR STR?561,"A parrot with an eyepatch hobbles up and down the bar."
	.GSTR STR?261,"A salesman stands behind the counter."
	.GSTR STR?558,"A Supremo it's not."
	.GSTR STR?293,"A teller sits behind the window."
	.GSTR STR?12,"a verb"
	.GSTR STR?481,"A winding road starts up here to the southwest. You can see the top of the lighthouse off to the northwest. The Wharf Road lies to the northeast."
	.GSTR STR?53,"a.m."
	.GSTR STR?607,"above"
	.GSTR STR?67,"afford it."
	.GSTR STR?262,"afford that."
	.GSTR STR?14,"afford to."
	.GSTR STR?605,"aft"
	.GSTR STR?472,"Air being what it is, you can't see it."
	.GSTR STR?25,"all week"
	.GSTR STR?553,"Although this sword is old and worn, it is still moderately sharp."
	.GSTR STR?222,"ambivalent"
	.GSTR STR?550,"Amidst a stack of rotted wood is a cask that is still in one piece."
	.GSTR STR?10,"amount of money"
	.GSTR STR?515,"An envelope with some writing on it sits on the desk."
	.GSTR STR?590,"An interesting concept, but beyond this reality."
	.GSTR STR?1,"April 23"
	.GSTR STR?580,"Are you enjoying yourself?"
	.GSTR STR?255,"As McGinty sees someone climbing through the window, he pulls out a gun and fires. His aim is better than your luck."
	.GSTR STR?369,"As the chest starts to rise, you fall off it rather awkwardly and disconnect your airhose."
	.GSTR STR?272,"As the spikes jump toward the magnet, one of them pierces your chest!"
	.GSTR STR?252,"As the tank falls away, it pulls the airhose with it, making you regret your lack of gills."
	.GSTR STR?361,"As you begin to move, you suddenly find yourself breathing water! Your airhose tore on some of the sharper debris."
	.GSTR STR?342,"As you descend further, Merv Griffin swims by, offering you Pittsburgh Penguin tickets. You realize too late that this is a hallucination, since Merv doesn't even like the Penguins. At this depth, narcosis takes over, and all that's left is to say bye to Merv..."
	.GSTR STR?373,"As you move away from the hole, your airhose gets caught on the edge of the hole in the wreck! As it tears, you find that breathing water is beyond your talents."
	.GSTR STR?247,"As you remove the mask, you find you can't breathe."
	.GSTR STR?5,"As you return to a watery environment, you realize the value of leaving your equipment on."
	.GSTR STR?304,"at the landing."
	.GSTR STR?140,"attack"
	.GSTR STR?330,"avoid it."
	.GSTR STR?229,"back door"
	.GSTR STR?380,"barnacle"
	.GSTR STR?276,"bartender"
	.GSTR STR?109,"behind "
	.GSTR STR?606,"below"
	.GSTR STR?141,"Benny Goodman"
	.GSTR STR?420,"boards"
	.GSTR STR?331,"boat:1191"
	.GSTR STR?332,"boat:1244"
	.GSTR STR?335,"boat:1420"
	.GSTR STR?311,"boat:405"
	.GSTR STR?318,"boat:562"
	.GSTR STR?321,"boat:639"
	.GSTR STR?323,"boat:672"
	.GSTR STR?327,"boat:775"
	.GSTR STR?328,"boat:977"
	.GSTR STR?61,"bolts"
	.GSTR STR?382,"BOOOOOOOOOOMMMMMMMMMM!"
	.GSTR STR?91,"bought it!"
	.GSTR STR?416,"bought it."""
	.GSTR STR?623,"bug"
	.GSTR STR?243,"bunch of clothes"
	.GSTR STR?359,"bunch of overturned tables"
	.GSTR STR?326,"bunks"
	.GSTR STR?108,"but "
	.GSTR STR?279,"but claw prints there"
	.GSTR STR?80,"carrying "
	.GSTR STR?256,"chair"
	.GSTR STR?303,"cliff"
	.GSTR STR?195,"climb "
	.GSTR STR?194,"climb onto "
	.GSTR STR?313,"climb that!"
	.GSTR STR?357,"climb the rope with that load."
	.GSTR STR?82,"close that."
	.GSTR STR?45,"closed"
	.GSTR STR?310,"connect the airhose to that!"
	.GSTR STR?309,"connected"
	.GSTR STR?3,"connected to the deep-sea diving suit"
	.GSTR STR?238,"counter"
	.GSTR STR?198,"cross that!"
	.GSTR STR?127,"cut"
	.GSTR STR?350,"cut it with that."
	.GSTR STR?362,"debris"
	.GSTR STR?296,"deposit more than you have."
	.GSTR STR?253,"desk"
	.GSTR STR?236,"desk clerk"
	.GSTR STR?589,"Did you say that just to impress me?"
	.GSTR STR?329,"diesel engine"
	.GSTR STR?179,"dig it, man."
	.GSTR STR?421,"disembarks"
	.GSTR STR?23,"do"
	.GSTR STR?21,"do it alone."
	.GSTR STR?337,"do that underwater."
	.GSTR STR?66,"do that."
	.GSTR STR?582,"Do you expect me to applaud?"
	.GSTR STR?234,"door"
	.GSTR STR?19,"door, which has lettering stencilled on it,"
	.GSTR STR?601,"downstairs"
	.GSTR STR?101,"drill that!"
	.GSTR STR?102,"drink that."
	.GSTR STR?595,"east"
	.GSTR STR?175,"empty"
	.GSTR STR?174,"empty it when it's closed!"
	.GSTR STR?173,"empty that!"
	.GSTR STR?13,"enough nouns"
	.GSTR STR?447,"events:1057"
	.GSTR STR?448,"events:1068"
	.GSTR STR?449,"events:1080"
	.GSTR STR?451,"events:1084"
	.GSTR STR?452,"events:1088"
	.GSTR STR?453,"events:1116"
	.GSTR STR?454,"events:1444"
	.GSTR STR?456,"events:1476"
	.GSTR STR?458,"events:1504"
	.GSTR STR?460,"events:1518"
	.GSTR STR?462,"events:1530"
	.GSTR STR?465,"events:1579"
	.GSTR STR?466,"events:1596"
	.GSTR STR?468,"events:1612"
	.GSTR STR?470,"events:1627"
	.GSTR STR?422,"events:303"
	.GSTR STR?424,"events:330"
	.GSTR STR?425,"events:399"
	.GSTR STR?427,"events:409"
	.GSTR STR?429,"events:419"
	.GSTR STR?431,"events:427"
	.GSTR STR?433,"events:449"
	.GSTR STR?437,"events:744"
	.GSTR STR?439,"events:758"
	.GSTR STR?442,"events:781"
	.GSTR STR?443,"events:837"
	.GSTR STR?445,"events:907"
	.GSTR STR?551,"Except for two broken rungs at the bottom, this ladder looks as if it's in good shape."
	.GSTR STR?355,"fallen partition"
	.GSTR STR?151,"Fiddling with"
	.GSTR STR?248,"filled"
	.GSTR STR?450,"find something to drink soon!"
	.GSTR STR?334,"first hole you drilled"
	.GSTR STR?245,"fit that over the "
	.GSTR STR?68,"fit through the hole carrying the tank."
	.GSTR STR?604,"forward"
	.GSTR STR?22,"from here"
	.GSTR STR?314,"from here."
	.GSTR STR?281,"furniture"
	.GSTR STR?93,"get "
	.GSTR STR?87,"get at your money."
	.GSTR STR?244,"get it over the other equipment you're wearing."
	.GSTR STR?367,"get off the chest"
	.GSTR STR?20,"get there from here."
	.GSTR STR?26,"get through the rocks."
	.GSTR STR?79,"give "
	.GSTR STR?302,"give him more than you've got."
	.GSTR STR?418,"glass of water"
	.GSTR STR?43,"globals:1080"
	.GSTR STR?48,"globals:1231"
	.GSTR STR?50,"globals:1247"
	.GSTR STR?56,"globals:1443"
	.GSTR STR?57,"globals:1450"
	.GSTR STR?60,"globals:1463"
	.GSTR STR?28,"globals:563(a)"
	.GSTR STR?29,"globals:563(b)"
	.GSTR STR?31,"globals:683"
	.GSTR STR?32,"globals:709"
	.GSTR STR?33,"globals:714"
	.GSTR STR?35,"globals:742(a)"
	.GSTR STR?36,"globals:742(b)"
	.GSTR STR?37,"globals:840"
	.GSTR STR?40,"globals:987"
	.GSTR STR?41,"globals:994"
	.GSTR STR?65,"go that way."
	.GSTR STR?74,"going anywhere."
	.GSTR STR?575,"Good day."
	.GSTR STR?577,"Goodbye."
	.GSTR STR?398,"grins"
	.GSTR STR?89,"had to buy"
	.GSTR STR?436,"hands something to McGinty"
	.GSTR STR?289,"have a drink."
	.GSTR STR?75,"have it."
	.GSTR STR?557,"He is wiry, hyper, and devoid of ethics. A fat cigar seems to be his only companion, since he's the type of man who would sell his own mother if given the opportunity."
	.GSTR STR?574,"Hello."
	.GSTR STR?134,"here to "
	.GSTR STR?325,"hidden under the mattress"
	.GSTR STR?383,"high enough to get past the two broken rungs"
	.GSTR STR?408,"his card"
	.GSTR STR?100,"holding the drill."
	.GSTR STR?343,"hole"
	.GSTR STR?543,"hole you drilled"
	.GSTR STR?579,"I hope you enjoyed that as much as I did."
	.GSTR STR?591,"I'll give you the benefit of the doubt and just ignore that."
	.GSTR STR?528,"If you really want to jump, say so, but do so at your own risk."
	.GSTR STR?70,"in"
	.GSTR STR?508,"In a corner of the room is a lopsided wooden dresser."
	.GSTR STR?9,"in that"
	.GSTR STR?86,"in that!"
	.GSTR STR?176,"in the "
	.GSTR STR?333,"in the drill"
	.GSTR STR?122,"inflate"
	.GSTR STR?216,"into that"
	.GSTR STR?251,"island:1004"
	.GSTR STR?254,"island:1047"
	.GSTR STR?257,"island:1150"
	.GSTR STR?258,"island:1156"
	.GSTR STR?259,"island:1161"
	.GSTR STR?263,"island:1246"
	.GSTR STR?271,"island:1667"
	.GSTR STR?273,"island:1746"
	.GSTR STR?278,"island:1860"
	.GSTR STR?280,"island:1930"
	.GSTR STR?283,"island:2026"
	.GSTR STR?284,"island:2028"
	.GSTR STR?285,"island:2058"
	.GSTR STR?286,"island:2070"
	.GSTR STR?287,"island:2072"
	.GSTR STR?288,"island:2123"
	.GSTR STR?290,"island:2171"
	.GSTR STR?297,"island:2336"
	.GSTR STR?300,"island:2376"
	.GSTR STR?230,"island:381"
	.GSTR STR?235,"island:467"
	.GSTR STR?241,"island:620"
	.GSTR STR?246,"island:939"
	.GSTR STR?249,"island:985"
	.GSTR STR?34,"it"
	.GSTR STR?567,"It bears the Hollywood Cruise Lines markings."
	.GSTR STR?317,"it from here"
	.GSTR STR?566,"It is dated 1680 and stamped with a portrait of King Peter II of Portugal."
	.GSTR STR?562,"It sports an eyepatch and wooden leg and has been here since the bartender bought it from a sailor. It's considered insane by the local patrons."
	.GSTR STR?282,"it to clean it"
	.GSTR STR?530,"It would help if a ship were berthed. If you want to take a dip in the ocean, you'll have to say so."
	.GSTR STR?475,"It's drab and worn."
	.GSTR STR?474,"It's faded to a drab off-white."
	.GSTR STR?477,"It's the bottom of a ladder that leads up."
	.GSTR STR?476,"It's the top of a ladder that leads down."
	.GSTR STR?509,"It's your room key."
	.GSTR STR?426,"Johnny glares at McGinty. ""Trying to cash in on my work again, huh? You probably killed Hevlin, too!"" And with that, he pushes McGinty off the cliff.

""I can't leave witnesses,"" he mumbles. Before you can react, you're on your way down to join what's left of McGinty."
	.GSTR STR?2,"Johnny looks around and says, ""This is no place to continue. If McGinty finds out about this, we're sunk. We better meet at the lighthouse at 9:30. Glad you're aboard."""
	.GSTR STR?301,"Johnny looks disappointed. ""We need at least $500 from you. I hate to do this, but you might tell McGinty..."" Suddenly you feel a shove in the back and see the pointy rocks below rush up to meet your descent."
	.GSTR STR?434,"Johnny looks disgusted. ""I can't wait all day..."" You feel a shove and then find yourself on your way down to the rocks below."
	.GSTR STR?432,"Johnny looks disgusted. ""No money? You probably told McGinty already. Traitor!"" He pushes you off the cliff, and you scream as the pointy rocks rush up to meet you."
	.GSTR STR?428,"Johnny sees McGinty on the road. ""You brought McGinty, you traitor! You probably killed Hevlin, too!"" A moment later, you're falling down to the rocks."
	.GSTR STR?430,"Johnny stares at you in disgust. ""A drunk diving for us? You'll probably tell McGinty, too. I'll make sure you don't."" He pushes you off the cliff. Although you feel no pain, your landing is fatal."
	.GSTR STR?147,"Kicking"
	.GSTR STR?133,"kill"
	.GSTR STR?315,"large air compressor"
	.GSTR STR?170,"latitude"
	.GSTR STR?226,"lighthouse door"
	.GSTR STR?396,"lit"
	.GSTR STR?55,"lock"
	.GSTR STR?58,"locked"
	.GSTR STR?171,"longitude"
	.GSTR STR?348,"lower hole"
	.GSTR STR?239,"mail"
	.GSTR STR?207,"make a deposit here!"
	.GSTR STR?206,"make a withdrawal here!"
	.GSTR STR?18,"make anything out on the other side."
	.GSTR STR?316,"make out too many details from here."
	.GSTR STR?24,"make your way through the growth."
	.GSTR STR?51,"make your way to the shoreline."
	.GSTR STR?394,"McGinty"
	.GSTR STR?391,"McGinty walks in the front door, spots something in the shadows, pulls out a gun, and fires. Unfortunately, you are what he noticed."
	.GSTR STR?264,"merchandise"
	.GSTR STR?240,"message"
	.GSTR STR?96,"Moses!"
	.GSTR STR?83,"move "
	.GSTR STR?90,"need to rent"
	.GSTR STR?223,"negative"
	.GSTR STR?576,"Nice weather we've been having lately."
	.GSTR STR?588,"No way. At least not in this reality."
	.GSTR STR?463,"north"
	.GSTR STR?598,"northeast"
	.GSTR STR?597,"northwest"
	.GSTR STR?587,"Not a chance."
	.GSTR STR?594,"Not a prayer."
	.GSTR STR?250,"Not a very good idea..."
	.GSTR STR?11,"number"
	.GSTR STR?306,"occupied"
	.GSTR STR?213,"of interest there"
	.GSTR STR?269,"off"
	.GSTR STR?268,"off."
	.GSTR STR?69,"on"
	.GSTR STR?110,"on "
	.GSTR STR?112,"on the "
	.GSTR STR?153,"on the floor"
	.GSTR STR?510,"On the floor is a note that must have been slipped under the door while you slept."
	.GSTR STR?312,"Oops! So much for instantly growing gills."
	.GSTR STR?44,"open"
	.GSTR STR?232,"open it from this side."
	.GSTR STR?77,"open the "
	.GSTR STR?603,"out"
	.GSTR STR?486,"Outfitters is closed."
	.GSTR STR?322,"over the wet suit"
	.GSTR STR?52,"p.m."
	.GSTR STR?320,"panel"
	.GSTR STR?401,"people:1016"
	.GSTR STR?386,"people:111"
	.GSTR STR?402,"people:1251"
	.GSTR STR?403,"people:1355"
	.GSTR STR?404,"people:1377"
	.GSTR STR?406,"people:1388"
	.GSTR STR?388,"people:142"
	.GSTR STR?411,"people:1805"
	.GSTR STR?413,"people:1825"
	.GSTR STR?417,"people:2234"
	.GSTR STR?390,"people:263"
	.GSTR STR?392,"people:268"
	.GSTR STR?395,"people:472"
	.GSTR STR?397,"people:525"
	.GSTR STR?385,"people:61"
	.GSTR STR?400,"people:940"
	.GSTR STR?423,"Pete spots McGinty, who is near enough to overhear! While Johnny chases McGinty, Pete accuses you of bringing McGinty along. Before you respond, the Weasel plunges his knife into your heart."
	.GSTR STR?560,"Pete wears an eyepatch and got his name on a far-east voyage as the cook. The food ran out, and he did what he could to supply the crew with fresh meat. Needless to say, he was left at the nearest port."
	.GSTR STR?214,"pick it up"
	.GSTR STR?123,"pick that."
	.GSTR STR?354,"plaque"
	.GSTR STR?149,"Playing in this way with"
	.GSTR STR?308,"port"
	.GSTR STR?221,"positive"
	.GSTR STR?97,"pour that."
	.GSTR STR?155,"push things to that."
	.GSTR STR?152,"Pushing"
	.GSTR STR?39,"quite sure which direction is which..."
	.GSTR STR?64,"reach "
	.GSTR STR?415,"reach behind the "
	.GSTR STR?559,"Red got his name from flame-red hair which sprouts from his head and face, and peeks out from under his flannel shirt. He takes no guff, but he is fair and has a sense of justice."
	.GSTR STR?92,"rent that."
	.GSTR STR?267,"reverse entropy."
	.GSTR STR?42,"room"
	.GSTR STR?30,"s"
	.GSTR STR?260,"salesman"
	.GSTR STR?544,"second hole you drilled"
	.GSTR STR?71,"see "
	.GSTR STR?62,"see any"
	.GSTR STR?295,"September 19"
	.GSTR STR?414,"set to "
	.GSTR STR?435,"shakes his head"
	.GSTR STR?399,"showed me this"
	.GSTR STR?441,"sits down for his watch"
	.GSTR STR?319,"small panel on the side of the machine"
	.GSTR STR?180,"smell anything beyond your mask."
	.GSTR STR?464,"south"
	.GSTR STR?600,"southeast"
	.GSTR STR?599,"southwest"
	.GSTR STR?111,"special to be "
	.GSTR STR?203,"spin that!"
	.GSTR STR?358,"stack of rotted wood"
	.GSTR STR?307,"starboard"
	.GSTR STR?291,"stick with grog."
	.GSTR STR?227,"swamp"
	.GSTR STR?54,"table"
	.GSTR STR?178,"take it; thus, you can't shake it!"
	.GSTR STR?199,"talk to "
	.GSTR STR?419,"talk to someone who's not here."
	.GSTR STR?81,"talking to anyone!"
	.GSTR STR?217,"tell without your watch."
	.GSTR STR?292,"teller"
	.GSTR STR?76,"that"
	.GSTR STR?17,"that much"
	.GSTR STR?496,"The bank is closed."
	.GSTR STR?514,"The business envelope has the McGinty Salvage return address, and ""Weasel's Merchant Seaman's card - collateral for deal"" scribbled in McGinty's hand."
	.GSTR STR?564,"The card says:
   ""Frank Webster
   Seaman First Class
   No. 2626868"""
	.GSTR STR?363,"the combination"
	.GSTR STR?49,"The currents pull you in several conflicting directions, and you end up much the worse for it."
	.GSTR STR?498,"The door is locked."
	.GSTR STR?485,"The east/west Wharf Road continues, with Outfitters International, a store which supplies ocean-going vessels, to the south."
	.GSTR STR?409,"the envelope"
	.GSTR STR?531,"The ferry for the mainland bobs up and down, its engines running."
	.GSTR STR?529,"The ferry to the mainland arrives here every two hours during the day. People are milling about. The Shore Road starts off to the east."
	.GSTR STR?455,"The giant squid stirs and sees what disturbed it. When the huge eyes spot you, it moves toward you and hugs you with its tentacles. You squirm in an attempt to get away, but more arms surround you and one disconnects your airhose."
	.GSTR STR?535,"The label is worn, so all you can make out is a large ""ACME"" at the top."
	.GSTR STR?547,"The large, ugly, toothy shark is headed toward you!"
	.GSTR STR?556,"The lighthouse door is locked."
	.GSTR STR?336,"the line. Worry about it when you've found the treasure"
	.GSTR STR?346,"the mast"
	.GSTR STR?511,"The note is hastily scrawled:

""If you're interested in a big deal, be at The Shanty at 8:30 this morning.
               -Johnny"""
	.GSTR STR?505,"The people in those rooms aren't interesting."
	.GSTR STR?16,"the right key"
	.GSTR STR?479,"The road branches to the northeast and northwest with the lighthouse off to the northwest. To the south is an impenetrable swamp."
	.GSTR STR?555,"The road ends at the lighthouse to the north, and heads back to the southeast. You can see and hear the ocean pound the shoreline."
	.GSTR STR?489,"The rocks are too sharp and dangerous.[ID: island:248]"
	.GSTR STR?492,"The rocks are too sharp and dangerous.[ID: island:266]"
	.GSTR STR?494,"The rocks are too sharp and dangerous.[ID: island:284]"
	.GSTR STR?63,"the rope"
	.GSTR STR?459,"The row of fallen bunks pinches your airhose. A few moments later, it is impossible to breathe."
	.GSTR STR?627,"The settling of debris has left a very narrow passage through this cabin. You can go forward or aft."
	.GSTR STR?136,"The squid, angered and wounded, starts wrapping tentacles around you. As you attempt another foray, you find that the squid's strength is too much for you."
	.GSTR STR?532,"The starboard side of the Mary Margaret has the wheelhouse to port. The deck is well-worn after many years of use, but still solid. The ocean is off to the other side of the rail."
	.GSTR STR?478,"The sturdy metal railing encircles the deck."
	.GSTR STR?351,"the top knot"
	.GSTR STR?521,"The tube has ""Frobizz waterproof putty"" printed on the side."
	.GSTR STR?73,"The water is too dark for you to see anything. After a moment, however, you feel something start to munch on you. Something large."
	.GSTR STR?407,"The Weasel glares at you and says, ""I don't take this from no one!"" He pulls out his knife, touches its too-sharp point with a finger, then introduces it to your chest."
	.GSTR STR?563,"The Weasel is a small, greasy man with shifty eyes. He loves his sharp little knife more than life itself, and would sell out anybody for a price. Even himself."
	.GSTR STR?242,"The Weasel is rummaging through your stuff. He notices you, and before you have a chance to react, he smiles then cuts your throat."
	.GSTR STR?387,"The Weasel turns and yells, ""Traitor!"" Next thing you know, you've been stabbed."
	.GSTR STR?405,"The Weasel, quite panic-stricken, doesn't stop to thank you before he pulls a small knife from his ankle and kills you."
	.GSTR STR?27,"there"
	.GSTR STR?554,"There is a giant squid sleeping here."
	.GSTR STR?541,"There's a bulkhead there."
	.GSTR STR?517,"There's a wall in the way."
	.GSTR STR?480,"There's no way to get footing on the swamp."
	.GSTR STR?469,"There's not enough air to breathe!"
	.GSTR STR?523,"These are charts for the Hardscrabble Island area."
	.GSTR STR?624,"This area is full of barnacle-encrusted iron bars, probably pikes used by the sailors for fending off boarding parties. There is a plaque on one wall. Exits are fore and aft."
	.GSTR STR?512,"This book is included in your Cutthroats package."
	.GSTR STR?637,"This cabin has suffered the ravages of the sea. Above your head at one end of the cabin a ladder leads up. The bottom two rungs of the ladder are broken, but the rest of it seems to be pretty sturdy. A doorway, outlined by rotting timbers, leads forward."
	.GSTR STR?631,"This cabin is the third-class passengers' quarters. There couldn't have been many frills here since the remains are spartan. The cabin can be exited aft and up."
	.GSTR STR?622,"This cabin seems to have been sleeping quarters. It must have been used by the crew, as it is spartanly furnished. The only ways out of this room are up and down."
	.GSTR STR?621,"This cabin was apparently used for storage, although what's left can only be described as debris. There is an exit abaft, a doorway outlined with barnacle-encrusted timbers. There is a hole above your head through which a broken-off mast descends."
	.GSTR STR?626,"This former dining room has some tables upturned and scattered about, a door forward, a hole through the floor, and a narrow opening abaft."
	.GSTR STR?635,"This had to have been a mine locker. There is a door forward and a passage above your head."
	.GSTR STR?549,"This heavy iron bar was probably used as a pike."
	.GSTR STR?522,"This heavy, semi-portable air compressor can fill scuba tanks."
	.GSTR STR?636,"This is another cabin used to house the ship's crew. There are exits forward and aft."
	.GSTR STR?518,"This is Outfitters International, a store that specializes in marine supplies. There is a long, high counter separating the supplies and the front area. To the north is the Wharf Road."
	.GSTR STR?616,"This is the bow of a very empty-looking wreck. The deck continues aft."
	.GSTR STR?482,"This is the end of the Wharf Road, an east/west, two-lane road that's the island's main street. Off to the east, small businesses line the south side of the street. A winding road starts to the southwest, heading toward the lighthouse. The Red Boar Inn is to the south."
	.GSTR STR?503,"This is the lobby of the Red Boar Inn, a place with the charm of a two-dollar flophouse. The Wharf Road is outside, to the north, and a stairway leads up to the rooms to the south."
	.GSTR STR?525,"This is The Shanty, a tavern which serves the locals. A wooden bar travels the length of the place, and behind it is a mirror so dirty, it offers no reflection. Round tables occupy the floor. The smell of cooking food permeates the place."
	.GSTR STR?493,"This is the south end of the Ocean Road. To the southeast is a small path leading up to about 100 feet above sea level. The Ocean Road heads north, and the Shore Road starts to the southwest."
	.GSTR STR?552,"This jagged hole is the result of centuries of wear on the hull."
	.GSTR STR?538,"This large, comfortable-looking bunk is the captain's."
	.GSTR STR?629,"This might have been the purser's cabin. It can be exited forward through a narrow opening."
	.GSTR STR?524,"This price list is included in your Cutthroats package."
	.GSTR STR?632,"This room, which may have been a lounge, can be exited fore or aft."
	.GSTR STR?625,"This was a galley or a pantry, though only the shape and size of the cabin suggest that. There are exits fore and aft."
	.GSTR STR?107,"This was not a very safe place to try jumping."
	.GSTR STR?633,"This was once the supplies locker, with exits forward and up, and a door with a sign on it in the aft bulkhead."
	.GSTR STR?208,"throw anything off that!"
	.GSTR STR?187,"tie it to yourself."
	.GSTR STR?370,"tied"
	.GSTR STR?220,"tired."
	.GSTR STR?8,"to "
	.GSTR STR?228,"to from inside"
	.GSTR STR?215,"to read there"
	.GSTR STR?172,"told me that."""
	.GSTR STR?270,"touching "
	.GSTR STR?159,"Trying to destroy"
	.GSTR STR?266,"tube"
	.GSTR STR?85,"turn that off."
	.GSTR STR?84,"turn that on."
	.GSTR STR?121,"turn things to a specific direction."
	.GSTR STR?47,"unlock it with that!"
	.GSTR STR?46,"unlocked"
	.GSTR STR?347,"upper hole"
	.GSTR STR?602,"upstairs"
	.GSTR STR?15,"use multiple "
	.GSTR STR?88,"verbs:1351"
	.GSTR STR?94,"verbs:1424"
	.GSTR STR?98,"verbs:1464"
	.GSTR STR?99,"verbs:1515"
	.GSTR STR?103,"verbs:1563"
	.GSTR STR?104,"verbs:1607"
	.GSTR STR?105,"verbs:1611"
	.GSTR STR?106,"verbs:1690"
	.GSTR STR?113,"verbs:1822(a)"
	.GSTR STR?114,"verbs:1822(b)"
	.GSTR STR?115,"verbs:1832(a)"
	.GSTR STR?116,"verbs:1832(b)"
	.GSTR STR?117,"verbs:1832(c)"
	.GSTR STR?118,"verbs:1837(a)"
	.GSTR STR?119,"verbs:1837(b)"
	.GSTR STR?120,"verbs:1837(c)"
	.GSTR STR?124,"verbs:1864"
	.GSTR STR?125,"verbs:1887(a)"
	.GSTR STR?126,"verbs:1887(b)"
	.GSTR STR?128,"verbs:1889(a)"
	.GSTR STR?129,"verbs:1889(b)"
	.GSTR STR?130,"verbs:1892(a)"
	.GSTR STR?131,"verbs:1892(b)"
	.GSTR STR?132,"verbs:1892(c)"
	.GSTR STR?135,"verbs:1899"
	.GSTR STR?137,"verbs:1919(a)"
	.GSTR STR?138,"verbs:1919(b)"
	.GSTR STR?139,"verbs:1919(c)"
	.GSTR STR?142,"verbs:1925(a)"
	.GSTR STR?143,"verbs:1925(b)"
	.GSTR STR?144,"verbs:1925(c)"
	.GSTR STR?145,"verbs:1928(a)"
	.GSTR STR?146,"verbs:1928(b)"
	.GSTR STR?150,"verbs:1950"
	.GSTR STR?154,"verbs:1975"
	.GSTR STR?156,"verbs:2051(a)"
	.GSTR STR?157,"verbs:2051(b)"
	.GSTR STR?158,"verbs:2051(c)"
	.GSTR STR?160,"verbs:2053(a)"
	.GSTR STR?161,"verbs:2053(b)"
	.GSTR STR?162,"verbs:2053(c)"
	.GSTR STR?163,"verbs:2063(a)"
	.GSTR STR?164,"verbs:2063(b)"
	.GSTR STR?165,"verbs:2063(c)"
	.GSTR STR?166,"verbs:2097(a)"
	.GSTR STR?167,"verbs:2097(b)"
	.GSTR STR?168,"verbs:2097(c)"
	.GSTR STR?169,"verbs:2107"
	.GSTR STR?177,"verbs:2193"
	.GSTR STR?181,"verbs:2319"
	.GSTR STR?183,"verbs:2324"
	.GSTR STR?185,"verbs:2327"
	.GSTR STR?188,"verbs:2391"
	.GSTR STR?189,"verbs:2393"
	.GSTR STR?190,"verbs:2395(a)"
	.GSTR STR?191,"verbs:2395(b)"
	.GSTR STR?192,"verbs:2395(c)"
	.GSTR STR?193,"verbs:2402"
	.GSTR STR?196,"verbs:2514"
	.GSTR STR?200,"verbs:2657"
	.GSTR STR?201,"verbs:2660(a)"
	.GSTR STR?202,"verbs:2660(b)"
	.GSTR STR?209,"verbs:2879"
	.GSTR STR?211,"verbs:2883"
	.GSTR STR?212,"verbs:2904"
	.GSTR STR?218,"verbs:3088"
	.GSTR STR?224,"verbs:3222"
	.GSTR STR?72,"verbs:575"
	.GSTR STR?78,"verbs:679"
	.GSTR STR?578,"Very good. Now you can go to the second grade."
	.GSTR STR?275,"water"
	.GSTR STR?353,"Water rushes into the room, making you realize the value of your equipment."
	.GSTR STR?148,"Waving"
	.GSTR STR?204,"wear "
	.GSTR STR?205,"wearing that!"
	.GSTR STR?596,"west"
	.GSTR STR?593,"What a concept!"
	.GSTR STR?581,"Wheeeeeeeeee!!!!!"
	.GSTR STR?59,"wheel"
	.GSTR STR?233,"window"
	.GSTR STR?294,"withdraw that!"
	.GSTR STR?364,"wrecks:1252"
	.GSTR STR?365,"wrecks:1262"
	.GSTR STR?366,"wrecks:1266"
	.GSTR STR?339,"wrecks:131"
	.GSTR STR?368,"wrecks:1375"
	.GSTR STR?372,"wrecks:1472"
	.GSTR STR?376,"wrecks:1523"
	.GSTR STR?377,"wrecks:1547"
	.GSTR STR?378,"wrecks:1618"
	.GSTR STR?379,"wrecks:1620"
	.GSTR STR?341,"wrecks:168"
	.GSTR STR?381,"wrecks:1827"
	.GSTR STR?344,"wrecks:422"
	.GSTR STR?349,"wrecks:524"
	.GSTR STR?352,"wrecks:703"
	.GSTR STR?356,"wrecks:810"
	.GSTR STR?338,"wrecks:93"
	.GSTR STR?360,"wrecks:971"
	.GSTR STR?527,"You are at Point Lookout, a small, high cliff that affords a spectacular view of the sea. The cliff bottom is dangerous, so the only safe path is the northwest footpath back to the Ocean Road."
	.GSTR STR?615,"You are at the bow of a steel ship that has been here for quite a while. The deck continues aft, and there is a passage leading down at your feet."
	.GSTR STR?614,"You are at the bow of an old, rotting wreck where a ladder leads down through a large square hole in the deck. When the ship sank, the top of one of the masts broke off and fell into the hole. What's left of the deck continues aft."
	.GSTR STR?488,"You are at the north end of the Ocean Road, a narrow north/south road on the east edge of the island. The Wharf Road starts to the northwest, and a back alley starts off to the southwest."
	.GSTR STR?620,"You are at the stern of this wreck. The deck continues forward."
	.GSTR STR?504,"You are at the top of the stairs in the Red Boar. Your room is to the south, and other rooms line the hall. The lighting in the hallway is dim and drab like the wallpaper and carpeting."
	.GSTR STR?495,"You are at the west end of the east/west Shore Road, with the ferry landing to the west. To the north is an impenetrable field, while the south is bordered by the ocean. You can see the mainland in the distance."
	.GSTR STR?444,"You are awakened by what feels like your ship running aground. You are put back to a permanent sleep by the Weasel's knife."
	.GSTR STR?490,"You are halfway along the Ocean Road, with the start of an alley off to the northwest. An empty field lies to your west, and the dangerous ocean shore lies off to your east."
	.GSTR STR?628,"You are in a bunk-lined cabin. The forward bulkhead has an open doorway in it, and a ladder leads down through the deck. The rotting interior of the hull lies aft."
	.GSTR STR?499,"You are in a narrow alley. To the north is the back door of McGinty Salvage, as well as a small window. An overgrown field lies to the south."
	.GSTR STR?536,"You are in a small, cramped cabin decorated with a table and a few chairs. To the aft is the captain's cabin, while the galley lies forward. A ladder leading down goes into the engine room."
	.GSTR STR?501,"You are in an alley behind Outfitters International. An abandoned field lies to the south."
	.GSTR STR?500,"You are in an east/west alley. To the north is a vacant lot, and an overgrown field lies to the south."
	.GSTR STR?526,"You are in Mariners' Trust, the Island's bank. In it are a table and a teller's window. You can see the safe beyond, and it looks pretty empty."
	.GSTR STR?546,"You are in the captain's cabin. A large and comfortable-looking bunk is one of the many comforts in the cabin. The forward doorway leads to the crew's lounge."
	.GSTR STR?537,"You are in the captain's cabin. There is a large and comfortable-looking bunk here. The forward doorway leads to the crew's lounge."
	.GSTR STR?545,"You are in the crew's lounge, a cramped cabin with little more than a table and a few chairs. To aft is the captain's cabin, while the galley lies forward. A ladder leads into the engine room."
	.GSTR STR?513,"You are in the McGinty Salvage office, a concern whose main business is salvaging wrecks. The place is a mess, and the floor is littered with chewed-on cigar stubs. To the north lies the Wharf Road. You can't help feeling uncomfortable here."
	.GSTR STR?617,"You are now aft of midships on the topmost deck. The deck continues fore and aft."
	.GSTR STR?619,"You are on the aft deck of the ship. Passengers could have gathered here to sun themselves and sip drinks. Those times are long gone. The only way to proceed is forward."
	.GSTR STR?618,"You are on the narrowing aft deck of the ship, which continues forward. A hole at the base of one mast leads down."
	.GSTR STR?548,"You are on the ocean floor. Sediment and seaweed wave slowly with the current."
	.GSTR STR?542,"You are on the port side of the Night Wind. The wheelhouse is to starboard. The teak deck is very well-kept. The ocean lies off to port."
	.GSTR STR?484,"You are on the Wharf Road where the wharf starts up to the north. The former site of Outfitters International's warehouse fronts the south side of the road."
	.GSTR STR?483,"You are on the Wharf Road, with the McGinty Salvage office to the south. The ocean lies to the north, its brine smell strong and refreshing."
	.GSTR STR?516,"You are standing on the former site of the Outfitters International warehouse, which burned down a few months back. To the north is the Wharf Road and an alley is to the south."
	.GSTR STR?630,"You can go aft from this cabin, a small and claustrophobic area little more than a widened passageway, or through a jagged hole in the port bulkhead."
	.GSTR STR?491,"You can't get through the weeds."
	.GSTR STR?410,"You can't help notice that your dresser has been opened and the contents messed up."
	.GSTR STR?219,"You fall asleep and run out of air."
	.GSTR STR?182,"You find that diving here is a bad idea without the proper equipment."
	.GSTR STR?184,"You find that the lack of oxygen you quickly encounter is fatally frustrating."
	.GSTR STR?186,"You find the water here too shallow for diving."
	.GSTR STR?461,"You find yourself gasping for air, but there's none to breathe!"
	.GSTR STR?473,"You keep your money in it."
	.GSTR STR?38,"You pass out and never find that you've been mugged, rolled and killed."
	.GSTR STR?95,"You suddenly bump into something in the darkness. You find that this something has long, sharp teeth that feel uncomfortable when they enter your body."
	.GSTR STR?471,"You suddenly find Red's hands around your throat as he makes a comment about hating cowards and Hevlin being wrong."
	.GSTR STR?340,"You suddenly find yourself inhaling water! The airhose trailing behind must have torn, and there's no time to do anything about it!"
	.GSTR STR?324,"You take the suit off and quickly realize you're not a dolphin. You realize this too late, though."
	.GSTR STR?502,"You're at the east end of an east/west alley. The back door of The Shanty is to the north, and an overgrown field is to the south. Narrow paths to the northeast and southeast lead to the Ocean Road."
	.GSTR STR?497,"You're at the west end of an east/west alley. The back entrance to the Red Boar Inn is to the north, and an overgrown field is to the south."
	.GSTR STR?634,"You're in one of the large holds of the ship, impressive in size. There are rooms fore and aft, and a hole in the port bulkhead."
	.GSTR STR?506,"You're in your room in the Red Boar Inn. It's sparsely furnished, but comfortable enough. To the north is the door, and there's a closet without a door to the west."
	.GSTR STR?487,"You're on the east end of Wharf Road. The Ocean Road starts here and parallels the island's east edge, heading to the southeast. The Shanty is to the south."
	.GSTR STR?539,"You're out to sea now.[ID: boat:1039]"
	.GSTR STR?540,"You're out to sea now.[ID: boat:1040]"
	.GSTR STR?533,"You're out to sea now.[ID: boat:196]"
	.GSTR STR?534,"You're out to sea now.[ID: boat:197]"
	.GSTR STR?467,"You've used all your air."
	.GSTR STR?345,"Your airhose catches and tears on the way down."
	.GSTR STR?446,"Your boat is lost in a sudden squall while you sleep."
	.GSTR STR?299,"your money"
	.GSTR STR?298,"Your pleasant leap is interrupted as you find yourself impaled on the jagged rocks."
	.ENDI
