	; Strings to accompany enchanter/enchanter.zap

	.GSTR STR?320,""
	.GSTR STR?321,"  "
	.GSTR STR?322,"    "
	.GSTR STR?323,"      "
	.GSTR STR?324,"        "
	.GSTR STR?325,"          "
	.GSTR STR?0," a transcript of interaction with ENCHANTER
ENCHANTER is a registered trademark of Infocom, Inc.
Copyright (c) 1983 Infocom, Inc. All rights reserved.
"
	.GSTR STR?390," asks what you would be needing treasures for."
	.GSTR STR?338," doesn't accomplish anything."
	.GSTR STR?337," doesn't do anything."
	.GSTR STR?388," eyes your possessions intently."
	.GSTR STR?339," has no desirable effect."
	.GSTR STR?391," offers to relieve you of some of your possessions."
	.GSTR STR?330,", and the jug's practically full."
	.GSTR STR?329,", and there's lots more where that came from."
	.GSTR STR?328,", and there's plenty more."
	.GSTR STR?327,", and there's still some left."
	.GSTR STR?326,", but the jug is now empty."
	.GSTR STR?389,", not overly tactful, asks to see what you're holding."
	.GSTR STR?356,"!"
	.GSTR STR?215,"""Don't Bother"""
	.GSTR STR?372,"""Give Up"""
	.GSTR STR?373,"""Go Away"""
	.GSTR STR?374,"""Had Enough?"""
	.GSTR STR?304,"[ID: outside:400]This spot halfway up the Lonely Mountain is desolate of vegetation. Short, stunted trees with branches empty surround you and the air is heavy and smoke-filled."
	.GSTR STR?461,"[ID: sleep:311]You dream of being pursued through a dank cavern. Something is behind you, something horrible that you can't turn to face. It gets closer and closer, and you can feel its hot breath on your neck."
	.GSTR STR?462,"[ID: sleep:315]You dream of an idyllic scene in the country, a picnic of wood-sprites and dryads."
	.GSTR STR?464,"[ID: sleep:323]You dream of dancing penguins in formal dress. One has a particularly nice tuxedo and a cane with a gold top."
	.GSTR STR?355,"/"
	.GSTR STR?357,"\"
	.GSTR STR?5,"a "
	.GSTR STR?438,"a bit hungry"
	.GSTR STR?445,"a bit thirsty"
	.GSTR STR?223,"A dank and forgotten pit contains the dungeons. There is a cell to the north, and a partly blocked passage leads even deeper into the earth. It looks as if there was once a mortared stone wall blocking this passage, but it has crumbled and collapsed, reopening the tunnel."
	.GSTR STR?186,"A dragon, spouting flame, approaches!"
	.GSTR STR?369,"A dull aching fills your head, and your mind is again probed, more deeply than when you entered the castle."
	.GSTR STR?498,"A gaunt, feral-looking dog carrying a well-chewed bone approaches, is surprised by your presence, growls and then turns tail."
	.GSTR STR?471,"a good deal"
	.GSTR STR?229,"A group of hunched and hairy shapes is standing here."
	.GSTR STR?87,"A jewelled box is sitting on the ground."
	.GSTR STR?86,"A jewelled box, wrapped in a partly untied tangle of rope, is on the ground."
	.GSTR STR?211,"A jewelled box, wrapped tightly in rope, is on the ground."
	.GSTR STR?371,"A knife seems to split your head apart. A deep, black presence seems to enter and probe, deep and sure. After what seems like an eternity, it passes, leaving you with a throbbing headache."
	.GSTR STR?474,"a lot"
	.GSTR STR?496,"A rat skitters across the floor, sees you, is startled, and rushes back the way it came."
	.GSTR STR?200,"A scroll emanating power is here."
	.GSTR STR?280,"A scroll of old, brittle parchment is here."
	.GSTR STR?190,"A scroll ornamented in gold leaf is here."
	.GSTR STR?475,"a whole lot"
	.GSTR STR?473,"about half"
	.GSTR STR?235,"Amid the tubes is an old and dusty book."
	.GSTR STR?4,"an "
	.GSTR STR?298,"An empty jug lies in a corner of the room, against the overturned table."
	.GSTR STR?285,"An enormous turtle is here, its enamelled shell shining with all the colors of the rainbow."
	.GSTR STR?476,"an entire loaf"
	.GSTR STR?1,"An evil presence, borne on a cold blast of air, seems to move beside you, weighing you down with emanations of malice and hatred. A cold fear covers you like fog.[ID: terror:642]"
	.GSTR STR?487,"are"
	.GSTR STR?466,"Are you a magician? Are you going to do something about that annoying Warlock, then?"
	.GSTR STR?416,"around noon"
	.GSTR STR?83,"As you open"
	.GSTR STR?396,"asks for directions to Flood Control Dam #3."
	.GSTR STR?307,"At the last moment, you remember that you don't know a flying spell."
	.GSTR STR?33,"attack"
	.GSTR STR?400,"attempts to eat his sword. I don't think it would agree with him."
	.GSTR STR?411,"Awful day, isn't it?"
	.GSTR STR?201,"banish the victim to another plane of existence"
	.GSTR STR?459,"barely able to move your arms"
	.GSTR STR?353,"barely usable"
	.GSTR STR?499,"Bats flutter by, red eyes glowing."
	.GSTR STR?439,"becoming quite hungry"
	.GSTR STR?450,"beginning to tire"
	.GSTR STR?497,"Bluebottles buzz up to you, and then away."
	.GSTR STR?431,"BUG"
	.GSTR STR?494,"Burma"
	.GSTR STR?318,"Candidate for membership in the Circle of Enchanters"
	.GSTR STR?491,"castle"
	.GSTR STR?119,"castle:1027"
	.GSTR STR?120,"castle:1167"
	.GSTR STR?121,"castle:1213"
	.GSTR STR?103,"castle:175"
	.GSTR STR?104,"castle:228"
	.GSTR STR?105,"castle:237"
	.GSTR STR?106,"castle:346"
	.GSTR STR?101,"castle:56"
	.GSTR STR?107,"castle:596"
	.GSTR STR?102,"castle:63"
	.GSTR STR?108,"castle:644"
	.GSTR STR?109,"castle:689"
	.GSTR STR?110,"castle:755"
	.GSTR STR?111,"castle:761"
	.GSTR STR?112,"castle:803"
	.GSTR STR?113,"castle:846"
	.GSTR STR?114,"castle:848"
	.GSTR STR?115,"castle:874"
	.GSTR STR?118,"castle:924"
	.GSTR STR?187,"cause something to give off light"
	.GSTR STR?204,"change a creature into a small amphibian"
	.GSTR STR?311,"Charlatan"
	.GSTR STR?194,"converse with the beasts in their own tongue"
	.GSTR STR?284,"Crawling slowly along the beach is an enormous turtle, his enamelled shell shining with all the colors of the rainbow."
	.GSTR STR?207,"create gratuitous fireworks"
	.GSTR STR?425,"dawn"
	.GSTR STR?455,"dead on your feet"
	.GSTR STR?202,"Discarded beneath a nearby tree is a slightly crumpled scroll."
	.GSTR STR?196,"dispel a magic spell"
	.GSTR STR?401,"downstairs"
	.GSTR STR?417,"early afternoon"
	.GSTR STR?419,"early evening"
	.GSTR STR?414,"early morning"
	.GSTR STR?362,"east"
	.GSTR STR?493,"east?"
	.GSTR STR?133,"egg:129"
	.GSTR STR?134,"egg:164"
	.GSTR STR?135,"egg:218"
	.GSTR STR?136,"egg:271"
	.GSTR STR?132,"egg:32"
	.GSTR STR?315,"Enchanter"
	.GSTR STR?316,"Expert Enchanter"
	.GSTR STR?448,"extremely thirsty"
	.GSTR STR?310,"F"
	.GSTR STR?442,"faint from lack of food"
	.GSTR STR?449,"faint from lack of water"
	.GSTR STR?441,"fairly starving"
	.GSTR STR?451,"feeling tired"
	.GSTR STR?453,"feeling wrung out and tired"
	.GSTR STR?399,"fends you off with his sword."
	.GSTR STR?38,"Fiddling with the "
	.GSTR STR?368,"five times"
	.GSTR STR?205,"fly like a bird"
	.GSTR STR?344,"foo"
	.GSTR STR?367,"four times"
	.GSTR STR?348,"full."
	.GSTR STR?130,"gallery:186"
	.GSTR STR?131,"gallery:225"
	.GSTR STR?129,"gallery:86"
	.GSTR STR?153,"gears:146"
	.GSTR STR?154,"gears:152"
	.GSTR STR?155,"gears:160"
	.GSTR STR?156,"gears:164"
	.GSTR STR?159,"gears:198"
	.GSTR STR?160,"gears:202"
	.GSTR STR?161,"gears:228"
	.GSTR STR?162,"gears:271"
	.GSTR STR?163,"gears:487"
	.GSTR STR?164,"gears:490"
	.GSTR STR?165,"gears:498"
	.GSTR STR?166,"gears:507"
	.GSTR STR?167,"gears:518"
	.GSTR STR?454,"getting more and more tired"
	.GSTR STR?52,"globals:128"
	.GSTR STR?53,"globals:136"
	.GSTR STR?54,"globals:144"
	.GSTR STR?56,"globals:158"
	.GSTR STR?57,"globals:164"
	.GSTR STR?488,"going"
	.GSTR STR?349,"gone"
	.GSTR STR?332,"Good day."
	.GSTR STR?334,"Good-bye."
	.GSTR STR?346,"half full."
	.GSTR STR?331,"Hello."
	.GSTR STR?269,"Hideous shapes chanting in unison can be seen through the cell window."
	.GSTR STR?410,"Hiya! Seen any juicy flies?"
	.GSTR STR?467,"How do you like my shell? A wizard did that to me about 75 years ago."
	.GSTR STR?443,"huoo"
	.GSTR STR?336,"I'm afraid that leap was a bit much for your weak frame."
	.GSTR STR?403,"in"
	.GSTR STR?176,"In one corner of the room is a badly worn pencil, inscribed with runes."
	.GSTR STR?423,"in the early hours"
	.GSTR STR?210,"In the exact center of the room is a large, jewelled box. It is wrapped in tight coils of thin rope. You try to follow the strands with your eye, but become hopelessly lost in the jumble of thousands of loops and knots."
	.GSTR STR?81,"incinerated by the dragon!"
	.GSTR STR?236,"Inspection has revealed that the tracks lead into a small hole in the wall."
	.GSTR STR?314,"Intermediate Enchanter"
	.GSTR STR?492,"is"
	.GSTR STR?385,"is combing his hair"
	.GSTR STR?387,"is deep in thought"
	.GSTR STR?386,"is wandering around his surroundings, seemingly lost"
	.GSTR STR?177,"It says ""Frobozz Magic Pencil Company."" Some sort of joke, probably."
	.GSTR STR?341,"It would take more magic than you've got!"
	.GSTR STR?468,"It's nice to find a human who talks turtle. Not many do, you know. Most people think turtles are boring, just because we talk slowly."
	.GSTR STR?413,"just past dawn"
	.GSTR STR?34,"Kicking the "
	.GSTR STR?29,"kill"
	.GSTR STR?2,"Krill looks your way and spits: ""You were fortunate, wizard-worm, to have survived our last encounter. But your trivial spells of protection will not save you now!"""
	.GSTR STR?421,"late evening"
	.GSTR STR?233,"Lying in a heap on the ground are what appear to be human bones, picked entirely clean."
	.GSTR STR?225,"Lying near the door is a silver spoon, discarded by the prisoners as too soft to dig with. It is only slightly worn."
	.GSTR STR?206,"Lying on the floor is a purple scroll."
	.GSTR STR?214,"Lying on the ground is an old parchment map."
	.GSTR STR?226,"Lying on the ground, and slightly damaged, is a stained scroll."
	.GSTR STR?189,"magically summon a being"
	.GSTR STR?191,"make a hostile creature your friend"
	.GSTR STR?195,"make things move with greater speed"
	.GSTR STR?317,"Master Enchanter"
	.GSTR STR?319,"Member of the Circle of Enchanters"
	.GSTR STR?420,"mid evening"
	.GSTR STR?418,"mid-afternoon"
	.GSTR STR?415,"mid-morning"
	.GSTR STR?422,"midnight"
	.GSTR STR?345,"mostly empty."
	.GSTR STR?458,"moving only on your last reserves of strength"
	.GSTR STR?347,"nearly full."
	.GSTR STR?351,"nearly gone"
	.GSTR STR?472,"nearly half"
	.GSTR STR?354,"negligible"
	.GSTR STR?333,"Nice weather we've been having lately."
	.GSTR STR?340,"No spell would help with that!"
	.GSTR STR?117,"north"
	.GSTR STR?363,"northeast"
	.GSTR STR?358,"northwest"
	.GSTR STR?352,"not fit for use"
	.GSTR STR?469,"not much"
	.GSTR STR?313,"Novice Enchanter"
	.GSTR STR?8,"Oh, no! Something has come up from behind you and feasted on your person!"
	.GSTR STR?11,"Oh, no! Something slithered alongside you and feasted on your person!"
	.GSTR STR?364,"once"
	.GSTR STR?376,"One of the gargoyles spits in your direction, burning your arm with incendiary byproducts."
	.GSTR STR?470,"only a small amount"
	.GSTR STR?192,"open even locked or enchanted objects"
	.GSTR STR?404,"out"
	.GSTR STR?169,"outside:135"
	.GSTR STR?170,"outside:290"
	.GSTR STR?171,"outside:422"
	.GSTR STR?172,"outside:494"
	.GSTR STR?173,"outside:501"
	.GSTR STR?174,"outside:700"
	.GSTR STR?168,"outside:90"
	.GSTR STR?312,"Parlor Magician"
	.GSTR STR?36,"Playing in this way with the "
	.GSTR STR?457,"practically asleep"
	.GSTR STR?424,"pre-dawn"
	.GSTR STR?197,"protect magic users from harm by evil beings"
	.GSTR STR?393,"pulls out his map, a convoluted collection of lines, arrows, and boxes, and checks it briefly."
	.GSTR STR?89,"purloined:199"
	.GSTR STR?91,"purloined:204"
	.GSTR STR?92,"purloined:325"
	.GSTR STR?93,"purloined:339"
	.GSTR STR?94,"purloined:354"
	.GSTR STR?95,"purloined:474"
	.GSTR STR?88,"purloined:55"
	.GSTR STR?96,"purloined:589"
	.GSTR STR?97,"purloined:594"
	.GSTR STR?98,"purloined:635"
	.GSTR STR?100,"purloined:672"
	.GSTR STR?276,"pushed"
	.GSTR STR?39,"Pushing the "
	.GSTR STR?193,"quench an open flame"
	.GSTR STR?446,"quite thirsty"
	.GSTR STR?203,"repair willful damage"
	.GSTR STR?198,"safely protect a small object as though in a strong box"
	.GSTR STR?495,"Shave"
	.GSTR STR?274,"shoved"
	.GSTR STR?141,"sleep:110"
	.GSTR STR?142,"sleep:168"
	.GSTR STR?143,"sleep:211"
	.GSTR STR?144,"sleep:234"
	.GSTR STR?145,"sleep:240"
	.GSTR STR?147,"sleep:250"
	.GSTR STR?148,"sleep:260"
	.GSTR STR?149,"sleep:275"
	.GSTR STR?150,"sleep:283"
	.GSTR STR?151,"sleep:292"
	.GSTR STR?152,"sleep:295"
	.GSTR STR?137,"sleep:53"
	.GSTR STR?139,"sleep:74"
	.GSTR STR?80,"sliced into bits by the monster!"
	.GSTR STR?392,"smiles at you like an idiot."
	.GSTR STR?456,"so tired you can barely put one foot in front of another"
	.GSTR STR?116,"south"
	.GSTR STR?361,"southeast"
	.GSTR STR?360,"southwest"
	.GSTR STR?64,"stair:25"
	.GSTR STR?65,"stair:289"
	.GSTR STR?66,"stair:371"
	.GSTR STR?68,"stair:398"
	.GSTR STR?69,"stair:404"
	.GSTR STR?70,"stair:409"
	.GSTR STR?71,"stair:416"
	.GSTR STR?72,"stair:443"
	.GSTR STR?73,"stair:461"
	.GSTR STR?74,"stair:465"
	.GSTR STR?75,"stair:470"
	.GSTR STR?76,"stair:474"
	.GSTR STR?77,"stair:498"
	.GSTR STR?78,"stair:509"
	.GSTR STR?79,"stair:538"
	.GSTR STR?82,"stair:558"
	.GSTR STR?394,"stares at his possessions as if expecting a revelation."
	.GSTR STR?384,"stares in your direction but seems not to see you"
	.GSTR STR?188,"survive unnatural death"
	.GSTR STR?412,"Tell Belboz that Fr'nb-ap says hello!"
	.GSTR STR?125,"temple:145"
	.GSTR STR?126,"temple:157"
	.GSTR STR?127,"temple:294"
	.GSTR STR?128,"temple:334"
	.GSTR STR?122,"temple:59"
	.GSTR STR?123,"temple:74"
	.GSTR STR?124,"temple:78"
	.GSTR STR?58,"terror:358"
	.GSTR STR?59,"terror:377"
	.GSTR STR?60,"terror:393"
	.GSTR STR?61,"terror:686"
	.GSTR STR?62,"terror:692"
	.GSTR STR?63,"terror:712"
	.GSTR STR?490,"the"
	.GSTR STR?99,"The adventurer, startled momentarily, fights back with surprising skill. In fact, his skill is much greater than your own, and he quickly dispatches you."
	.GSTR STR?3,"The bedpost pops open, revealing a small compartment and, nestled inside, a gold leaf scroll!"
	.GSTR STR?232,"The corridor widens here to form a large hall. To the north and south are small passages, and to the east is what appears to be an enormous spiral staircase. A passage to the west leads into a courtyard. The walls here are scarred and black, and a strange heaviness hangs in the air."
	.GSTR STR?222,"The damp corridor continues east and west from here. A dark and forbidding stairway leads down to the south. In addition, a narrow passage leads to the north."
	.GSTR STR?380,"The door opens, and nineteen demons, each a cross between a carrot and a sledge hammer, march out from behind it, knock you senseless, and return, the last closing the door behind it."
	.GSTR STR?220,"The eyrie is a round bedroom high in the tower. Narrow windows overlook the outside. A stone stairway leads down."
	.GSTR STR?406,"the finer points of insect flavoring."
	.GSTR STR?379,"The floating sign, once serene, knocks you delicately over the head."
	.GSTR STR?240,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1100]"
	.GSTR STR?241,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1102]"
	.GSTR STR?242,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1103]"
	.GSTR STR?243,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1104]"
	.GSTR STR?244,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1105]"
	.GSTR STR?245,"The forest is deep and dark. I wouldn't go in there.[ID: castle:1106]"
	.GSTR STR?238,"The gate is rusted shut."
	.GSTR STR?295,"The inside of the shack is a shambles. An overturned table and bench, and a few broken windows remain. An oven is the only fixture that's even recognizable. The door is to the south."
	.GSTR STR?408,"the Interlogic series of prose adventures."
	.GSTR STR?286,"The iron gate is locked."
	.GSTR STR?231,"The kitchen has been freshly used. The oven, though empty, is still warm. Bones litter the floor, and the carving knives are bloody. The bones give all too clear an indication of the nature of the viands prepared here."
	.GSTR STR?230,"The kitchen is dusty and disused. Old bones litter the floor, and the carving knives are rusty. A rat nest fills one of the ovens, and cobwebs are everywhere. There is some rotting food in a garbage heap in one corner."
	.GSTR STR?85,"The kulcad spell dispels"
	.GSTR STR?256,"The northern part of the interior courtyard is grey and lifeless. The vast lawns are withered and covered in black ash stretching from south to west. The temple stands to the southeast, and the courtyard continues east."
	.GSTR STR?158,"the other side"
	.GSTR STR?184,"The pit yawns before you, and the izyuk spell has worn off!"
	.GSTR STR?407,"the politics of lily pad assignment."
	.GSTR STR?409,"the recent disturbing rise in the number of predators in the swamp."
	.GSTR STR?84,"The rezrov spell bursts"
	.GSTR STR?277,"The scroll is damaged beyond readability. You can make out the word ""summon,"" in the title, but that's all."
	.GSTR STR?297,"The top of a battered lantern is partially visible behind the overturned table."
	.GSTR STR?292,"The trail ends here. A ruined stone foundation marks the site of the Old Lingolf House, which presumably was a monument of some sort. The trail head is off to the southwest, and a small brook flows slowly by."
	.GSTR STR?300,"The trail here turns dry and dusty. To the northwest is the fork leading to the Long Road, and the trail continues to the southeast."
	.GSTR STR?305,"The trail is narrow and only heads up and down."
	.GSTR STR?301,"The trail makes a hairpin turn here, swinging out to the northwest and northeast, where it enters a small village. Low, smoky hills stretch out to the west and south."
	.GSTR STR?293,"The trail turns a corner here, bending out of sight to the southeast and southwest. The ground is higher here than to the south, allowing you to make out the top of the Lonely Mountain, shrouded in clouds. No path from here leads up the mountain, however."
	.GSTR STR?180,"The wall is cylindrical here, with exits east and west. The eastern one opens into a dark, enclosed space. The air is thick with acrid smoke, and black, greasy ashes mar the floor. The mortar and stones of the walls are stained and crumbly."
	.GSTR STR?67,"The warlock Krill appears before you, staring in astonishment. ""Who is it that disturbs my slumber? Oh, it is only you, secondary-school sorcerer!"" He points a finger and chants a spell. You are cast into the endless void!"
	.GSTR STR?185,"The warlock Krill, robed in black, stands before you, in eager anticipation of your death."
	.GSTR STR?247,"There could be quicksand there. You should stay here.[ID: castle:1128]"
	.GSTR STR?248,"There could be quicksand there. You should stay here.[ID: castle:1129]"
	.GSTR STR?249,"There could be quicksand there. You should stay here.[ID: castle:1130]"
	.GSTR STR?250,"There could be quicksand there. You should stay here.[ID: castle:1132]"
	.GSTR STR?251,"There could be quicksand there. You should stay here.[ID: castle:1133]"
	.GSTR STR?252,"There could be quicksand there. You should stay here.[ID: castle:1134]"
	.GSTR STR?253,"There could be quicksand there. You should stay here.[ID: castle:1135]"
	.GSTR STR?208,"There is a faintly glowing strong box here."
	.GSTR STR?272,"There is an ornamented egg here, both beautiful and complex. It is carefully crafted and bears further examination."
	.GSTR STR?262,"There is no entrance to the tower here."
	.GSTR STR?309,"There is no road there."
	.GSTR STR?485,"There's a full loaf, too."
	.GSTR STR?483,"There's a lot of bread left, too."
	.GSTR STR?484,"There's a whole lot of it left, too."
	.GSTR STR?481,"There's nearly half of it left, too."
	.GSTR STR?282,"There's no path there."
	.GSTR STR?477,"There's none left, though."
	.GSTR STR?478,"There's not much left, though."
	.GSTR STR?479,"There's only a small amount left, though."
	.GSTR STR?480,"There's still a good deal left, too."
	.GSTR STR?482,"There's still about half of it left, too."
	.GSTR STR?219,"This dark and damp spot is at the base of the southwest tower of the castle. Two corridors lead off to the north and east. A winding staircase ascends into the tower."
	.GSTR STR?270,"This fabulous room commands a magnificent view of the Lonely Mountain which lies to the north and west. The room itself is filled with beautiful chests and cabinets which once contained precious jewels and other objets d'art. These are empty. Winding stone stairs lead down to the base of the tower."
	.GSTR STR?182,"This is a circular pit of apparently infinite depth. The walls are of crudely dressed stone. No floor is visible."
	.GSTR STR?181,"This is a circular room with no floor. There are exits east and west. A crude drawing of stairsteps graces the ceiling. Downward is only darkness."
	.GSTR STR?234,"This is a library, or rather it was until it was ransacked and despoiled. Most of the contents of the room have been burned in a huge bonfire in the center of the room. Hundreds of charred and empty tubes are scattered about, as if by someone searching, so ashes are strewn about. There are rat tracks in the ashes."
	.GSTR STR?281,"This is a meadow near the sea. There is a smell of salt in the air. Only heather and thistles grow here. To the north is a gate leading into the castle. A narrow path to the southeast leads to the shore of the Sea."
	.GSTR STR?283,"This is a rocky beach along a grey and lifeless sea. There is dead seaweed covering many rocks, and listless waves barely stir the flotsam and jetsam here. There are many shells, but all are broken. A narrow path to the northwest leads into a meadow."
	.GSTR STR?183,"This is a room carved out of black basalt, eerily lit by flickering fires and the dim glow of magic."
	.GSTR STR?268,"This is a small prison cell in the north tower of the temple. Hideous shapes can be seen through the iron-barred window in the prison door. From the temple, a bloodcurdling chant can be heard."
	.GSTR STR?382,"This is a spot within the long"
	.GSTR STR?267,"This is the altar of the temple. Acrid smoke fills the air, and a feeling of lurking evil is all around. A low droning, just at the lowest end of your perception, causes your hair to stand on end. Behind the altar is an enormous statue of a demon which reaches toward you with dripping fangs and razor-sharp talons. The fangs and talons are blood-red. In the temple below is a mass of hunched figures, chanting in hideous tones."
	.GSTR STR?254,"This is the base of the northwest tower of the castle. A winding staircase leads up into the tower itself, and passages lead from here to the east and south."
	.GSTR STR?228,"This is the base of the southeast tower of the castle. From atop a winding staircase comes a loud crashing and screeching noise. To the west is a corridor and the southern gate of the castle."
	.GSTR STR?302,"This is the castle's village. Formerly, peasants lived here, going to their farm plots each day. Merchants and artisans made it a center of cultural activity. But now it's deserted. Or almost: there is smoke rising from a particularly decrepit hovel to the south. A path travels through the village from southwest to northeast, heading towards the castle, and a less-used trail heads north up the mountain."
	.GSTR STR?279,"This is the control room for all the machinery nearby. The controls are all magical, of course. The walls are covered by blinking lights and shifting displays, interspersed with arcane dials and glowing buttons. It's all very mysterious looking. The exit, to the northwest, leads into a room with machinery which would surely crush you if you were to attempt to enter it."
	.GSTR STR?383,"This is the eastern end of the"
	.GSTR STR?266,"This is the interior of a huge temple of primitive construction. A few flickering torches cast a sallow illumination over the altar, which, atop a row of stairs, is still drenched with the blood of human sacrifice. Behind the altar is an enormous statue of a demon which seems to reach towards you with dripping fangs and razor-sharp talons. Two open doorways lead out of the temple to the east and west, while two wooden doors stand at the north and south. A mass of hunched figures in the temple are chanting a haunting tune. They don't seem interested in your presence."
	.GSTR STR?255,"This is the northern part of the large interior courtyard of the castle. The vast lawns continue from here south and west. To the southeast stands a huge temple, on either side of which are dark towers. The courtyard continues east along a narrow path."
	.GSTR STR?260,"This is the southern part of the courtyard, spreading north and west. The ground is ashen and grey, and the air heavy with death. The dead grass seems to grab at your feet. A narrow stretch of scorched earth continues to the east. To the northeast stands the temple, flanked by two small towers."
	.GSTR STR?259,"This is the southern part of the great courtyard, which spreads out to the north and west. A narrow stretch of grass continues to the east. To the northeast stands the temple, flanked by two small towers."
	.GSTR STR?306,"This is the top of the Lonely Mountain. In olden days, mariners had named it Signal Mountain, for its glistening peak reflected the pale moonlight, providing an unmistakable landmark on unclouded nights. The bald mountain face is made of a shining substance whose nature is unknown to you. Looking to the west, low hills stretch to the horizon, and small pieces of the Long Road can be seen winding their way to distant lands. To the east, far away, can be seen a great castle at the edge of the Sea. Three turrets it has; two, old and still majestic, lie on either side of a third, cold, black as night and squat as a toad. An evil smoke seems to emanate from this tower, shrouding the others in a darkening fog. A small mountain trail leaves the peak and descends to the south into a small village far below."
	.GSTR STR?381,"This is the western end of the"
	.GSTR STR?217,"This is the westernmost point in a large open courtyard. The huge entrance gate to the castle looms ominously to the west. The courtyard widens as it proceeds to the east, where a large, ivy-covered temple stands. On either side of the temple are small towers. Far beyond the temple, high above, are two large towers marking the corners of the castle. A squat dark turret hunches between them, blackening the sky around it. A small path leads into the castle to the south."
	.GSTR STR?179,"This legend, written in an ancient tongue, goes something like this: At one time a shapeless and formless manifestation of evil was disturbed from millenia of sleep. It was so powerful that it required the combined wisdom of the leading enchanters of that age to conquer it. The legend tells how the enchanters lured the Terror ""to a recess deep within the earth"" by placing there a powerful spell scroll. When it had reached the scroll, the enchanters trapped it there with a spell that encased it in the living rock. The Terror was so horrible that none would dare speak of it. A comment at the end of the narration indicates that the story is considered to be quite fanciful; no other chronicles of the age mention the Terror in any form."
	.GSTR STR?178,"This legend, written in an ancient tongue, speaks of the creation of the world. A more absurd account can hardly be imagined. The universe, it seems, was created by ""Implementers"" who directed the running of great engines. These engines produced this world and others, strange and wondrous, as a test or puzzle for others of their kind. It goes on to state that these beings stand ready to aid those entrapped within their creation. The great magician-philosopher Helfax notes that a creation of this kind is morally and logically indefensible and discards the theory as ""colossal claptrap and kludgery."""
	.GSTR STR?218,"This narrow promenade stretches into darkness to the south and, through an archway, toward an open area to the north."
	.GSTR STR?212,"This room in the high tower appears to be a map room, with hundreds of ancient maps covering the walls. A huge globe, made of gold, sits on a pedestal in the center of the room. Through the tower windows can be seen a vast forest stretching out to the northeast and the sea, covered in fog, to the east and south. Stairs to the south lead to the bottom of the tower."
	.GSTR STR?227,"This short piece of corridor continues to the north and south."
	.GSTR STR?237,"This small open area stands at the old north gate of the castle, now badly rusted. Through the gate, a forest can be seen. To the west, a hall glows with light, and to the south, the dark castle can be reentered. A narrow passage to the east leads to the base of the northeast tower."
	.GSTR STR?209,"This small room must have been a closet of some sort. To the north is a passage leading out into a courtyard. Another exit is to the south."
	.GSTR STR?377,"Three or four tentacles grab you briefly and send you flying."
	.GSTR STR?366,"thrice"
	.GSTR STR?221,"Through the window, you can see a long twisting road making its way through a land of low, smoky hills."
	.GSTR STR?213,"Through the windows you can discern a vast forest to the northeast and the fog-shrouded sea stretching out to the east and south."
	.GSTR STR?395,"tries to make some small talk, but he only mumbles. He'll have to speak up if he expects you to hear him."
	.GSTR STR?397,"tries to make some small talk, but only mumbles. He'll have to speak up if he expects you to hear him."
	.GSTR STR?43,"Trying to damage the "
	.GSTR STR?278,"turned"
	.GSTR STR?365,"twice"
	.GSTR STR?273,"twisted"
	.GSTR STR?375,"Two, or perhaps three, monster heads reach out for you, spearing you in the process."
	.GSTR STR?460,"unable to keep your eyes open for more than a few moments at a time"
	.GSTR STR?224,"Unfortunately, this passage was never completed, so you don't get very far (neither did the prisoners)."
	.GSTR STR?22,"Unfortunately, you were holding it at the time."
	.GSTR STR?402,"upstairs"
	.GSTR STR?14,"verbs:1002"
	.GSTR STR?15,"verbs:1021"
	.GSTR STR?16,"verbs:1024"
	.GSTR STR?17,"verbs:1061"
	.GSTR STR?18,"verbs:1141(a)"
	.GSTR STR?19,"verbs:1141(b)"
	.GSTR STR?20,"verbs:1141(c)"
	.GSTR STR?21,"verbs:1151"
	.GSTR STR?23,"verbs:1156"
	.GSTR STR?24,"verbs:1179"
	.GSTR STR?25,"verbs:1191(a)"
	.GSTR STR?26,"verbs:1191(b)"
	.GSTR STR?27,"verbs:1193(a)"
	.GSTR STR?28,"verbs:1193(b)"
	.GSTR STR?30,"verbs:1204(a)"
	.GSTR STR?31,"verbs:1204(b)"
	.GSTR STR?32,"verbs:1204(c)"
	.GSTR STR?37,"verbs:1250"
	.GSTR STR?40,"verbs:1257(a)"
	.GSTR STR?41,"verbs:1257(b)"
	.GSTR STR?42,"verbs:1257(c)"
	.GSTR STR?44,"verbs:1339"
	.GSTR STR?45,"verbs:1355(a)"
	.GSTR STR?46,"verbs:1355(b)"
	.GSTR STR?47,"verbs:1355(c)"
	.GSTR STR?48,"verbs:1423"
	.GSTR STR?49,"verbs:1487"
	.GSTR STR?50,"verbs:1490(a)"
	.GSTR STR?51,"verbs:1490(b)"
	.GSTR STR?6,"verbs:387"
	.GSTR STR?7,"verbs:565"
	.GSTR STR?9,"verbs:620"
	.GSTR STR?10,"verbs:923"
	.GSTR STR?12,"verbs:986"
	.GSTR STR?13,"verbs:989"
	.GSTR STR?440,"very hungry"
	.GSTR STR?350,"very nearly gone"
	.GSTR STR?447,"very thirsty"
	.GSTR STR?398,"waves his sword menacingly in your direction."
	.GSTR STR?35,"Waving the "
	.GSTR STR?437,"well fed"
	.GSTR STR?444,"well hydrated"
	.GSTR STR?359,"west"
	.GSTR STR?405,"what they will do if they ever become princes again."
	.GSTR STR?489,"when"
	.GSTR STR?486,"Why"
	.GSTR STR?452,"worn out"
	.GSTR STR?275,"wound"
	.GSTR STR?199,"write a magic spell into a spell book"
	.GSTR STR?157,"you"
	.GSTR STR?290,"You are at a fork in the road where paths to the northwest and southwest girdle the base of the Lonely Mountain and a smaller path winds its way to the east."
	.GSTR STR?433,"You are becoming quite hungry."
	.GSTR STR?427,"You are becoming quite thirsty."
	.GSTR STR?436,"You are beginning to feel faint from lack of sustenance.[ID: sleep:85]"
	.GSTR STR?430,"You are beginning to feel faint from lack of water.[ID: sleep:64]"
	.GSTR STR?265,"You are in a courtyard between an open hall to the east and a temple to the west. The temple is flanked, north and south, by twin towers. Paths cross the scarred lawn to the northwest and southwest. Nothing now grows here, however, and a foul stench fills the air."
	.GSTR STR?239,"You are in a dark forest, just north of a rusted gate. Except to the east and south, the forest is thick all around you."
	.GSTR STR?246,"You are in a thick forest shading into a deep and miasmic swamp. The ground is very wet and boggy here, and footing is treacherous. Lily pads cover the surface of the water, and frogs abound. Things look drier to the west."
	.GSTR STR?257,"You are in the center of a large courtyard, which surrounds you in all directions. Directly in front of you, to the east, is a large temple flanked by two smaller towers. Behind the temple can be seen the two eastern towers of the castle, shrouded in fog, and the single dark turret, black as night and sending dark streams of smoke into a lowering sky. From the temple comes a howling, haunting chant."
	.GSTR STR?258,"You are in the center of a large courtyard, which surrounds you. Everything around you is ashen and grey, and the air seems miasmic and oppressive. The dead grass seems to grab at your feet as you stand gazing around. To the east is a temple flanked by two smaller towers. Behind it can be seen the two eastern towers of the castle, shrouded in blood-red fog. Between them is a dark turret, black and ominous as night. It sends dark streams of smoke curling around everything near it. From the temple can be heard a mournful chant."
	.GSTR STR?261,"You are north of a small tower which connects with the temple to the south. A large courtyard can be seen to the west and a smaller one to the southeast."
	.GSTR STR?216,"You are on a long pebbled path, stretching out to the north. To the south the path continues through an open arch into an open area."
	.GSTR STR?308,"You are on a road which enters a small village to the southwest and comes to a fork to the northeast. The Lonely Mountain looms above but there is no path from here which ascends the mountain."
	.GSTR STR?287,"You are on an east-west road, which wends its way through the dark, rolling hills of this land. To the west rises a high mountain, to the east stands a high castle with dark towers."
	.GSTR STR?291,"You are on the northeast side of the Lonely Mountain, walking a narrow path through rolling hills. On one side of the path is a sign and behind that, to the northeast, a winding path through the thick undergrowth. The trail continues to the southeast."
	.GSTR STR?263,"You are south of a small tower which connects with the temple to the north. A large courtyard can be seen to the west and a smaller one to the northeast."
	.GSTR STR?294,"You are south of an old wooden shack, apparently deserted. The trail extends from northeast to southwest here, circling the Lonely Mountain, which lies to the southeast."
	.GSTR STR?264,"You are standing in a small courtyard between a large open hall to the east and a temple to the west. The temple is flanked to the north and south by two small towers. Paths cross the lawn to the northwest and southwest."
	.GSTR STR?434,"You are very hungry now. You'd better have something to eat.[ID: sleep:83]"
	.GSTR STR?428,"You are very thirsty now. You'd better have a drink soon.[ID: sleep:62]"
	.GSTR STR?271,"You can see the Lonely Mountain to the northwest."
	.GSTR STR?342,"You can't be serious."
	.GSTR STR?296,"You can't see much except for scrubby vegetation."
	.GSTR STR?465,"You dream of a river, slow and muddy. Great grey hippopotami sport there, bellowing and splashing, and twitching their ears."
	.GSTR STR?463,"You dream of Krill. He works feverishly in an evilly lit workroom. He is working a conjuration of great complexity and power, and the room is strewn with the noisome components of this horrific casting. Krill chants words of awful power as he works."
	.GSTR STR?175,"You execute a perfect swan-dive into the rocks below."
	.GSTR STR?55,"You experience the most peculiar sensation of being simultaneously shrunken and sucked into what might best be likened to a black hole. The effect is not without its exhilarating aspect; as a way of life, however, it leaves much to be desired."
	.GSTR STR?500,"You hear noises in the darkness nearby."
	.GSTR STR?378,"You manage to reach one of the iron chains before it turns into a pair of teeth and bites you."
	.GSTR STR?343,"You must have had a silliness spell cast upon you."
	.GSTR STR?140,"You pass out from lack of strength and die."
	.GSTR STR?138,"You pass out from lack of water and die."
	.GSTR STR?501,"You sense something behind you, turn, and there is nothing there."
	.GSTR STR?335,"You should have looked before you leaped."
	.GSTR STR?146,"You sleep blissfully, unaware of the evil creatures lurking in the darkness. Unaware, that is, until one of them sets upon you with nasty sharp teeth."
	.GSTR STR?299,"You stand at a point of decision on a road which makes a wide fork to the northeast and southeast, circling the base of the Lonely Mountain, which looms high overhead to the east. A very long and winding road starts here and stretches out of sight to the west through low, smoky hills."
	.GSTR STR?303,"You wander around in the village, find nothing of interest, and return to the path."
	.GSTR STR?288,"You would become lost among the brambles. Better to stay on the road.[ID: outside:41]"
	.GSTR STR?289,"You would become lost among the brambles. Better to stay on the road.[ID: outside:43]"
	.GSTR STR?435,"You're fairly starving. If you don't eat soon you will pass out.[ID: sleep:84]"
	.GSTR STR?90,"You've really gotten those tentacles in an uproar. Sixty-three of them grab you and pull in sixty-three different directions. Not good for the digestion."
	.GSTR STR?370,"Your head is filled with a heavy sensation, as though an enormous weight were being borne by it. Your mind is again probed, this time very deeply, testing and learning. The feeling passes after a long moment."
	.GSTR STR?429,"Your lips are parched. If you don't get a drink soon you will pass out.[ID: sleep:63]"
	.GSTR STR?426,"Your mouth is getting rather dry."
	.GSTR STR?432,"Your stomach is starting to grumble."
	.ENDI
