<ROUTINE PRINT-DESC1 (OBJ)
    <COND (.OBJ
        <TELL D .OBJ>)>>

<ROUTINE PRINT-ID (ID "OPT" (CONDITION T))
    <COND (.CONDITION
        <TELL "[ID: " .ID ", PRSO: "> <PRINT-DESC1 ,PRSO> <TELL ", PRSI: "> <PRINT-DESC1 ,PRSI> <TELL "]">
        )>>

<ROUTINE PRINT-DEBUG (TEXT "OPT" (CONDITION T))
    <COND (.CONDITION
        <TELL "DEBUG FLAG: " .TEXT>
        )>>

; "[RIDX: 2582]"
<ROUTINE IS-THEFT? ()
    <AND <VERB? TAKE>
    <EQUAL? ,PRSO ,BOAT ,PRAM ,NOTICE ,SCULPTURE ,THRUSTERS ,SPHONES ,PHONES ,DISH ,SDISH ,WAND ,STATUES
    ,LIMBS ,HEADS ,TOMBS ,LID ,HERBS ,PATCH ,TBOMB ,TCABLES ,UBOMB ,UCABLES ,BONES ,MIKE ,CAULDRON ,SPEAKER
    ,LSPEAKERS ,DECOR ,GROPES ,HARDWARE ,BOX ,PADLOCK ,PANEL ,ANTENNA ,MAP ,GMAP ,TOME ,PAGES ,GIBINOS
    ,TAPE ,BALL ,PARASOL ,AXE ,SHROUD ,BANDAGE ,RBOOT ,GBOOT ,BCOIN ,SPADE ,APANEL ,BOOK ,MARKER ,BINOS ,BOX
    ,WTK ,WALLET ,PHOTO ,LAMP ,KNIFE>>>

<ROUTINE IS-OBJECT-OR-PROPERTY? ()
    <EQUAL? ,PRSO ,ANTENNA ,APANEL ,ARBOR ,ARBS ,ATREL ,AUX-TS3 ,AWINDOWS ,AXE ,BAD-CRANE ,BAG ,BALL
    ,BANDAGE ,BARROW ,BARROW-DOOR ,BATHROOM ,BBOX ,BCOIN ,BDIAL ,BDIAL-HOLE ,BEDROOM ,BEDS ,BENCH ,BHOUSE ,BIKES
    ,BINOS ,BLGATE ,BLUFF ,BOAT ,BONES ,BOOK ,BOX ,BPAPER ,BPRAM ,BREAKER ,BROKEN-LID ,BROOM-DOOR ,BTREL
    ,BWIRE ,CAGE ,CATS ,CAULDRON ,CAVE ,CAVE-HOLE ,CAVERN ,CCLOCK ,CEILING ,CEMETERY
    ,CINDERS ,CISTAIR ,CITY ,CLEARING ,CLIFF ,CLOSET ,CLOSET-DOOR ,COCO ,COTTAGE
    ,COTTAGE-DOOR ,CRANE ,CRATER ,CRYPT ,CSURFACE ,CTREE ,CUPBOARD
    ,DEBRIS ,DECOR ,DIAL ,DIAL-HOLE ,DISH ,DLEM ,DMAGPIE ,DMEEP ,DMOUNTS ,DORY ,DSKINK ,DSTRUCT ,DTOWER
    ,EBAG ,EMERALD ,ENERGY ,ESHED ,FATMAN ,FEATHERS ,FHILLS ,FIN
    ,FLARE ,FLIPPER ,FLOOR ,FLOWERS ,FLWALK ,FOREST ,FRAME ,GADGET ,GARDEN ,GARDEN-DOOR ,GARDENS ,GARLIC ,GBAG
    ,GBOLTS ,GBOOT ,GCABLES ,GFENCE ,GIBINOS ,GLOWING-LOG
    ,GMAP ,GNOMON ,GOON ,GOON-MOUTH ,GPLATFORM ,GPRAM ,GROPES ,GROUP ,GTREES
    ,HARDWARE ,HEADS ,HEDGE ,HERBS ,HOLLOW ,HONEY ,HTS ,IBUTTON ,ICAVE
    ,ICBM ,ICEHOUSE ,IFENCE ,ILINES ,ISTAIR ,JDOOR
    ,JEEP ,JEEPS ,JUMBO ,KEY ,KEYHOLE ,KITCHEN ,KNIFE ,LAMP ,LANDING ,LANDSLIDE ,LCITY
    ,LEFT-DOOR ,LEVER ,LGATE ,LID ,LIMBS ,LONDON ,LSPEAKERS ,LTREL ,LUMP ,LWDOOR
    ,MAP ,MARKER ,MBOX ,MCRANE ,MEADOW ,MEMORIAL ,MESA ,METEOR ,METERS ,MIKE ,MILK ,MILL ,MISSILE
    ,MLADDER ,MOON ,MOOR ,MOUTH ,NAGASAKI ,NBUNKERS ,NEROOM-DOOR ,NOTICE ,NROOM-DOOR ,NUTS
    ,NWGATE ,OAK ,OBUTTON ,OCOCO ,OCRANE ,OPPIE-THINGS ,OPSHORE ,OSS ,PADLOCK ,PAGES ,PAN ,PANEL
    ,PARASOL ,PATCH ,PEDESTAL ,PGATE ,PHONES ,PHOTO ,PILE ,PIPES ,PITTS ,PLADDER ,PLANES ,PLANET
    ,PLATFORM ,PLUTONIUM ,POOL ,PORCH ,PRAM ,PTREES ,RADIO ,RAIL ,RAMP ,RANCH
    ,RBOOT ,RDIAL ,RESERVOIR ,RIGHT-DOOR ,RING ,ROSE ,RPOND ,RSPEAKER ,RSWITCH ,RTREL ,RUBBLE ,RUBY
    ,RWALLS ,RWIRE ,SBENTRY ,SBUNK ,SCAF-STAIR ,SCAFFOLD ,SCHOOL ,SCHOOL-WINDOWS ,SCOIN ,SCULPTURE
    ,SDISH ,SDOORS ,SDRIVER ,SEAT ,SEGATE ,SEROOM-DOOR ,SHACK ,SHED
    ,SHELTER ,SHROUD ,SINK ,SJUNK ,SLIDER ,SLIGHT ,SPADE
    ,SPEAKER ,SPHONES ,SSTEPS ,STAIR ,STARS ,STATUES ,STOOLS ,STRUCTURE ,STYX ,SUMMIT ,SUN ,SWALL
    ,SWGATE ,SWINGS ,SWIRE ,SWROOM-DOOR ,SYMBOLS ,TAPE ,TCABLES ,TCLIFF ,TERRACE
    ,THICKET ,THRUSTERS ,TKEY ,TLADDER ,TMOUNTS ,TOMBS ,TOME ,TOWER ,TPLAT ,TRAP ,TREE ,TREETOPS ,TRELS ,TRENCHES
    ,TROPES ,TS0 ,TS0-DOOR ,TS1 ,TS1-DOOR ,TS2 ,TS2-DOOR ,TS3 ,TS3-DOOR ,TS4 ,TS4-DOOR ,TS5 ,TS5-DOOR ,TS6 ,TS6-DOOR ,TSWITCH
    ,TUBE ,TUNNEL ,TBOMB ,UBOMB ,UCABLES ,VERTEX ,VICTORIA ,WALLET ,WALLS ,WAND ,WATERFALL ,WATT ,WBENCH ,WBITS
    ,WBUTTON ,WINDOWS ,WIRES ,WSWITCH ,WTK ,WWIRE ,X5 ,XRAY>>

<ROUTINE IS-NUKE? ()
    <EQUAL? ,PRSO ,FATMAN ,GADGET ,ICBM ,MIKE ,MISSILE ,TBOMB ,UBOMB>>

<ROUTINE IS-PERSON? ()
    <AND <OR <FSET? ,PRSO ,PERSON> <EQUAL? ,PRSO ,BABIES ,BAKER ,BOY ,BWOMAN ,CHARON ,CHILDREN ,GIANT ,GIRL ,GIS ,GROVES ,HER
    ,HIM ,JWOMAN ,KIDS ,NANNIES ,OPPIE ,RUSSIANS  ,TEACHERS ,TOURISTS ,WIGHT ,YOU>> <NOT <IS-ANIMAL?>>>>

<ROUTINE IS-ANIMAL? ()
    <EQUAL? ,PRSO ,BEE ,BEES ,CRABS ,DFLIES ,DOG ,HIVE ,LEM ,LEMMINGS ,MAGPIE ,MALLARDS ,MEEP ,PIGEONS ,POND-BIRDS ,RODENTS
     ,SKINK ,SNAKE ,XSNAKE>>

<ROUTINE IS-SELF? ()
    <EQUAL? ,PRSO ,HEAD ,ME ,PLAYER>>

<ROUTINE IS-PART-OF-SELF? ()
    <EQUAL? ,PRSO ,ANKLE ,EYES ,FEET ,HANDS  ,MOUTH>>

<ROUTINE IS-SOPOS? ()
    <OR <IS-SELF?> <IS-PART-OF-SELF?>>>

<ROUTINE IS-YOUR-PROPERTY? ()
    <EQUAL? ,PRSO ,CLOTHES ,POCKET ,WRISTWATCH ,COIN ,CREDIT-CARD>>

<ROUTINE DANGEROUS-DRINK? ()
    <EQUAL? ,PRSO ,PEE>>


; "[RIDX: 2583]"
<ROUTINE DANGEROUS-FOOD? ()
    <AND <OR <IS-PART-OF-SELF?> <IS-OBJECT-OR-PROPERTY?>> <NOT <EQUAL? ,PRSO ,COCO ,HERBS ,HONEY ,MILK ,NUTS ,OCOCO ,PATCH>>>>

<ROUTINE IS-OBJ-PROP-ANIMAL? ()
    <OR <IS-OBJECT-OR-PROPERTY?>
        <IS-ANIMAL?>>>

<ROUTINE IS-POPA? ()
    <OR <IS-PERSON?>
        <IS-OBJECT-OR-PROPERTY?>
        <IS-ANIMAL?>>>


