	; Strings to accompany plunderedhearts/plunderedhearts.zap

	.GSTR STR?17,"

     ***   You have died   ***

"
	.GSTR STR?68,"   "
	.GSTR STR?208,"   It's been rather a long time since any of the crew have dealt with the fairer sex, and they are a bit rough, despite Rodney Quick's exhortations."
	.GSTR STR?47,"   Lafond smacks you hard across the face with the back of his hand, ""Fool."" He casts aside all formalities."
	.GSTR STR?283,"   Roaring anger and revenge, Lafond runs in, pouncing upon you. Your death, when it comes, is wished for."
	.GSTR STR?224,"   Suddenly you appreciate what it is to be a ball in an exploding cannon. The intense heat, the push of fire, and the sense of release when spit from the cannon's mouth -- these you feel when the lighted fuse finally burns up to the largest keg of gunpowder in the hold."
	.GSTR STR?237,"   The tides are against you, however, and carry you out to sea. Days later you collapse, exhausted, to wake in the heaven on earth of a Swedish merchant marine. A midshipman, an ice-eyed blond with Viking physique and no English, nurses you back to health; in a moment of weakness you thank him in the only language all men and women share."
	.GSTR STR?20," A tangled mass of rigging hangs down from the mast, like many rope ladders woven together."
	.GSTR STR?473," accomplishes nothing."
	.GSTR STR?243," and collapses.
   You were warned, of course, but did not listen. A stray keg pushes you off the deck into the sea."
	.GSTR STR?11," calls after you.

"
	.GSTR STR?513," collapses, head back, snoring loudly"
	.GSTR STR?89," Cookie harrumphs, surprised."
	.GSTR STR?10," do you want to "
	.GSTR STR?472," doesn't do anything."
	.GSTR STR?19," drips off your fingers.
"
	.GSTR STR?30," halfway up the cliff stairs."
	.GSTR STR?520," has a small pool of liquid at the bottom"
	.GSTR STR?474," has no desirable effect."
	.GSTR STR?15," his eyes rake over your inadequately dressed body, the damp chemise clinging to your legs and heaving bosom, your gleaming hair"
	.GSTR STR?519," is brimming with wine"
	.GSTR STR?24," is closed"
	.GSTR STR?28," is not flush against the doorsill. "
	.GSTR STR?518," is ornate and expensive"
	.GSTR STR?230," Lafond's dragoons deal with you quickly."
	.GSTR STR?22," only darkness beyond"
	.GSTR STR?42," only the back of"
	.GSTR STR?45," over the head with"
	.GSTR STR?77," over your white linen chemise. Mama would say you belonged in a brothel.
"
	.GSTR STR?511," seems to be having some problems stifling a yawn"
	.GSTR STR?60," squeeze through the opening between cupboard and wall"
	.GSTR STR?196," Suddenly, an offshore current pulls you past the reefs into the open sea. You haven't the strength to row back."
	.GSTR STR?228," The blade bites less then you expected."
	.GSTR STR?6," the dance floor"
	.GSTR STR?4," the edge of"
	.GSTR STR?48," The fall to the bottom of the well is endless; you've lost consciousness by the time the water overtakes you."
	.GSTR STR?78," walks up to you. ""M. Lafond requests your presence in his room immediately, Miss."" He points "
	.GSTR STR?87," With an engaging smile he bows and leaves the folly.
"
	.GSTR STR?14,", his wig awry, sprawls across the parquet floor."
	.GSTR STR?58,", pushing you out of the house.
"
	.GSTR STR?96,", shrugging off your lack of cooperation"
	.GSTR STR?69,".
"
	.GSTR STR?82,". ""Hey, boy! Get away from those. It ain't safe!"" yells a sailor."
	.GSTR STR?296,". The governor of St. Sinistra provides you with food and shelter; at least, until he grows tired of your body and your presence."
	.GSTR STR?91,". The monster snorts in its sleep"
	.GSTR STR?247,". The next few minutes last forever as havoc breaks out. Grabbing a plank, you manage to stay afloat, but you are washed out to sea. A brig, Portuguese by its sails, rescues you. The sailors are brown skinned and smooth, and the first mate, the ship's and yours, is gentle. They leave you in Rio, alone and forgotten."
	.GSTR STR?13,". There is a tear at the bottom"
	.GSTR STR?385,". Visiting that Neptune you tol' me about. Gone to sea, poor man,"" he laughs, and returns to lurking around the doorway."
	.GSTR STR?336,". You are pulled struggling into the pool."
	.GSTR STR?70,"...

"
	.GSTR STR?512,"'s eyes are getting heavier"
	.GSTR STR?88,""" The butler points up the stairs.
"
	.GSTR STR?489,"""Aaieeee!"" echoes a scream, followed by several grunts and thumps"
	.GSTR STR?490,"""Cap'n Jamison! We've got 'em!"" cries a rough voice"
	.GSTR STR?16,"""Help me!"" you cry, hoping someone will help you."
	.GSTR STR?501,"""I am sorry you have been confined down here, but I don't trust my lonely crew with such beauty. Crulley isn't the only man aboard with few principles."" He smiles at you, eyes lingering, and takes your hand. You feel your color rising. ""If anything goes wrong, turn to Cookie. He is quite deaf, but capable. He'll see you through."""
	.GSTR STR?503,"""I haven't found your father. We've long suspected a passage under the library, but I cannot find an entrance,"" says Jamison"
	.GSTR STR?505,"""I wish you would call me 'Nicholas' -- I feel I know you much better than our brief acquaintance would allow."" He presses your hand"
	.GSTR STR?504,"""If there is any trouble, and I am unable to help -- a signal from an upstairs seaward window will bring my men. They can be here in moments,"" the Captain says"
	.GSTR STR?402,"""It's not safe down there,"" the Falcon calls."
	.GSTR STR?491,"""The Falcon! The Falcon conquers!"" yells someone"
	.GSTR STR?500,"""We have anchored off St. Sinistra,"" says Captain Jamison, ""and I must look like a guest at Lafond's dance tonight. I will find and free your father, and then finally wreak my revenge on Lafond."" He half draws his rapier from its scabbard."
	.GSTR STR?532,"""You must ... pay ... for your actions!"" Nicholas gasps."
	.GSTR STR?52,"[Press RETURN or ENTER to "
	.GSTR STR?67,"[There seems to be a noun missing in that sentence.]
"
	.GSTR STR?80,"[There was no verb in that sentence!]
"
	.GSTR STR?419,"A bench is built into the wall, circling the folly."
	.GSTR STR?488,"A bit of canvas sail "
	.GSTR STR?453,"A canvas cot is shoved against a wall."
	.GSTR STR?407,"A chipped piece of mirror sits propped on a shoulder-high timber."
	.GSTR STR?463,"A dagger is driven into the wooden floorboards."
	.GSTR STR?436,"A firepit in the floor smokes badly, fogging up the depths of this large kitchen, somehow not escaping through either the south or west doors."
	.GSTR STR?438,"A grandiose staircase splits and twists up to the next floor here, framing the entrance south to the ballroom. Long hallways lead east and west; cool night air drifts in through the front door, north of you."
	.GSTR STR?406,"A grate blocks your way."
	.GSTR STR?447,"A lace-covered table crouches beside a wing-backed chair in one corner."
	.GSTR STR?240,"A large one rolls into you, stumbling you through the railing into the sea."
	.GSTR STR?445,"A pair of duelling pistols is mounted high on one wall."
	.GSTR STR?486,"A plank of wood "
	.GSTR STR?452,"A powder horn hangs on a long strap from the wall."
	.GSTR STR?433,"A rutted drive runs north-south here, from a high spiked gate through the jungle to Lafond's mansion. You hide in the bushes nearby."
	.GSTR STR?59,"A sinewy arm encircles you, ""Stay, my lady."""
	.GSTR STR?461,"A small bottle has been dropped nearby."
	.GSTR STR?450,"A strong wet breeze blows from a low doorway to the east. A circle of light leads west. The passageway continues south."
	.GSTR STR?432,"A tall hedge prevents you from going around the east wing of the house."
	.GSTR STR?26,"A tiny glow of fire creeps across a stretch of floor -- inside the cage full of ammunition"
	.GSTR STR?98,"Actor"
	.GSTR STR?106,"AGAIN"
	.GSTR STR?1,"Although the lagoon is warm and clear, it is much too deep.
"
	.GSTR STR?81,"An eerie battle cry arises on the wind, from all sides of the house"
	.GSTR STR?272,"As you fiddle with the"
	.GSTR STR?341,"As you lift the hat from its"
	.GSTR STR?112,"ask"
	.GSTR STR?522,"Avast me, but ain't ye a beauty"
	.GSTR STR?73,"Aye-aye.
"
	.GSTR STR?203,"be holding"
	.GSTR STR?108,"begins"
	.GSTR STR?113,"Biting"
	.GSTR STR?114,"blow"
	.GSTR STR?497,"Bswish! Waves smash against the reefs nearby"
	.GSTR STR?428,"Buried in the subtropical undergrowth, you lose all sense of being on someone's private estate; jungle seems to extend for miles on all sides of you. A footworn path curves from east to north here, and the vegetation lessens to the northeast."
	.GSTR STR?123,"burn"
	.GSTR STR?76,"But it's such a beautiful night!
"
	.GSTR STR?411,"Cannon line the deck, aimed at open sea and the island."
	.GSTR STR?190,"Caressing"
	.GSTR STR?83,"Chestnut hair, tousled by the wind, frames the tanned oval of his face. "
	.GSTR STR?124,"climb into"
	.GSTR STR?125,"climb onto"
	.GSTR STR?126,"close"
	.GSTR STR?332,"clothes:177"
	.GSTR STR?333,"clothes:261"
	.GSTR STR?334,"clothes:339"
	.GSTR STR?335,"clothes:465"
	.GSTR STR?339,"clothes:767"
	.GSTR STR?21,"Completely common looking "
	.GSTR STR?448,"Cool salt air, blowing past a torch on a spiral staircase below you, ruffles your hair and circles south into the library."
	.GSTR STR?185,"Dagger sharpening"
	.GSTR STR?345,"dainty fists"
	.GSTR STR?424,"Death lies that way, my lady."
	.GSTR STR?189,"do that to"
	.GSTR STR?478,"Don't be absurd."
	.GSTR STR?485,"Don't bother."
	.GSTR STR?482,"Don't dally around."
	.GSTR STR?415,"Don't push your luck too far."
	.GSTR STR?434,"Dragoons guard the gate."
	.GSTR STR?395,"Dragoons surround you, appearing from nowhere. They show you no mercy, though they let you survive."
	.GSTR STR?8,"Dragoons surround you. "
	.GSTR STR?464,"Dragoons, conversing quietly, patrol the other side of the gate."
	.GSTR STR?460,"Draped across the bed is a lovely cream colored watered silk gown. It looks about your size."
	.GSTR STR?132,"drink"
	.GSTR STR?133,"drink from"
	.GSTR STR?120,"drop"
	.GSTR STR?109,"ends"
	.GSTR STR?471,"enters just a few steps behind you."
	.GSTR STR?159,"extinguish"
	.GSTR STR?364,"extras:1022"
	.GSTR STR?365,"extras:1098"
	.GSTR STR?366,"extras:1108(a)"
	.GSTR STR?367,"extras:1108(b)"
	.GSTR STR?368,"extras:1115(a)"
	.GSTR STR?369,"extras:1115(b)"
	.GSTR STR?348,"extras:112"
	.GSTR STR?370,"extras:1120(a)"
	.GSTR STR?371,"extras:1120(b)"
	.GSTR STR?372,"extras:1129(a)"
	.GSTR STR?373,"extras:1129(b)"
	.GSTR STR?349,"extras:118"
	.GSTR STR?350,"extras:121"
	.GSTR STR?376,"extras:1214"
	.GSTR STR?351,"extras:128"
	.GSTR STR?353,"extras:137"
	.GSTR STR?378,"extras:1560"
	.GSTR STR?379,"extras:1580"
	.GSTR STR?380,"extras:1595"
	.GSTR STR?382,"extras:1718"
	.GSTR STR?383,"extras:1787"
	.GSTR STR?384,"extras:1827"
	.GSTR STR?386,"extras:2037"
	.GSTR STR?387,"extras:2071"
	.GSTR STR?388,"extras:2077"
	.GSTR STR?389,"extras:2088"
	.GSTR STR?390,"extras:2093"
	.GSTR STR?391,"extras:2095"
	.GSTR STR?392,"extras:2097"
	.GSTR STR?393,"extras:2102"
	.GSTR STR?394,"extras:2141"
	.GSTR STR?396,"extras:2201"
	.GSTR STR?398,"extras:2238"
	.GSTR STR?400,"extras:2276"
	.GSTR STR?354,"extras:311"
	.GSTR STR?355,"extras:339"
	.GSTR STR?356,"extras:541(a)"
	.GSTR STR?357,"extras:541(b)"
	.GSTR STR?358,"extras:544(a)"
	.GSTR STR?359,"extras:544(b)"
	.GSTR STR?342,"extras:69"
	.GSTR STR?360,"extras:693"
	.GSTR STR?361,"extras:716"
	.GSTR STR?343,"extras:74"
	.GSTR STR?344,"extras:84"
	.GSTR STR?346,"extras:89"
	.GSTR STR?362,"extras:895"
	.GSTR STR?347,"extras:97"
	.GSTR STR?363,"extras:990"
	.GSTR STR?85,"Eyes closed, his skin with the pallor of death, Nick looks entirely spent.
"
	.GSTR STR?72,"Failed.
"
	.GSTR STR?136,"Fiddling with"
	.GSTR STR?218,"finely woven"
	.GSTR STR?232,"Firing cannon"
	.GSTR STR?449,"Flickering torchlight lights the bottom of a spiral staircase. A draft blows from the east; a passage leads south."
	.GSTR STR?470,"follows you."
	.GSTR STR?172,"get in"
	.GSTR STR?115,"get into"
	.GSTR STR?215,"get off"
	.GSTR STR?197,"get on"
	.GSTR STR?116,"get onto"
	.GSTR STR?233,"get out of"
	.GSTR STR?201,"globals:1168(a)"
	.GSTR STR?202,"globals:1168(b)"
	.GSTR STR?205,"globals:1620"
	.GSTR STR?206,"globals:1646"
	.GSTR STR?207,"globals:2135"
	.GSTR STR?198,"globals:661"
	.GSTR STR?195,"globals:85"
	.GSTR STR?199,"globals:858"
	.GSTR STR?200,"globals:874"
	.GSTR STR?468,"Happily Ever After"
	.GSTR STR?127,"have hysterics"
	.GSTR STR?23,"He doesn't respond.
"
	.GSTR STR?94,"He kisses your forehead.
"
	.GSTR STR?63,"He laughs triumphantly and pulls you into the dance.
"
	.GSTR STR?259,"hero:136"
	.GSTR STR?260,"hero:198(a)"
	.GSTR STR?261,"hero:198(b)"
	.GSTR STR?262,"hero:244"
	.GSTR STR?257,"hero:73"
	.GSTR STR?263,"hero:741"
	.GSTR STR?264,"hero:893"
	.GSTR STR?457,"Hewn from dense rock, the cell is a stagnant burrow. Except for the tiniest glow of light from the torch two rooms away, it is pitch black."
	.GSTR STR?509,"His eyes twinkle, like moonlight on the sea"
	.GSTR STR?502,"His look darkens. ""You should know why I hate Lafond: Some years ago, as my brother and his bride sailed to a new life in Virginia, pirates struck. Their ship was boarded, looted and burned, the women taken, never to be seen again. A sailor, the one survivor, watched as a man of Lafond's description shot my brother in the back as he tried to save the women. Lafond has now bought respectability, but he shall never buy peace."" Jamison straightens resolutely, bows, and departs."
	.GSTR STR?410,"If you wish to go to the Poop, go AFT."
	.GSTR STR?191,"in front of"
	.GSTR STR?271,"island:1312"
	.GSTR STR?273,"island:1674"
	.GSTR STR?274,"island:1783"
	.GSTR STR?275,"island:1902"
	.GSTR STR?276,"island:1907"
	.GSTR STR?277,"island:1924"
	.GSTR STR?278,"island:1927"
	.GSTR STR?279,"island:1930"
	.GSTR STR?280,"island:1935"
	.GSTR STR?281,"island:1963"
	.GSTR STR?282,"island:1984"
	.GSTR STR?284,"island:2057"
	.GSTR STR?285,"island:2104"
	.GSTR STR?286,"island:2136"
	.GSTR STR?287,"island:2141"
	.GSTR STR?288,"island:2150"
	.GSTR STR?289,"island:2204"
	.GSTR STR?290,"island:2227"
	.GSTR STR?291,"island:2247"
	.GSTR STR?293,"island:2252"
	.GSTR STR?295,"island:2259"
	.GSTR STR?297,"island:2353"
	.GSTR STR?298,"island:2355"
	.GSTR STR?299,"island:2360"
	.GSTR STR?300,"island:2389"
	.GSTR STR?301,"island:2485"
	.GSTR STR?302,"island:2489"
	.GSTR STR?303,"island:2525"
	.GSTR STR?304,"island:2553"
	.GSTR STR?306,"island:2558"
	.GSTR STR?308,"island:2564"
	.GSTR STR?311,"island:2792"
	.GSTR STR?313,"island:3032"
	.GSTR STR?314,"island:3049"
	.GSTR STR?315,"island:3051"
	.GSTR STR?316,"island:3063"
	.GSTR STR?317,"island:3067"
	.GSTR STR?318,"island:3070"
	.GSTR STR?319,"island:3118"
	.GSTR STR?320,"island:3168"
	.GSTR STR?321,"island:3175"
	.GSTR STR?322,"island:3222"
	.GSTR STR?324,"island:3290"
	.GSTR STR?325,"island:3325"
	.GSTR STR?327,"island:3405"
	.GSTR STR?328,"island:3413"
	.GSTR STR?329,"island:3415"
	.GSTR STR?330,"island:3423"
	.GSTR STR?331,"island:3469"
	.GSTR STR?266,"island:368"
	.GSTR STR?267,"island:688"
	.GSTR STR?268,"island:795"
	.GSTR STR?269,"island:830"
	.GSTR STR?265,"island:89"
	.GSTR STR?270,"island:955"
	.GSTR STR?75,"It already is.
"
	.GSTR STR?7,"It doesn't look like"
	.GSTR STR?29,"It is thoroughly unladylike to "
	.GSTR STR?33,"It seems that"
	.GSTR STR?477,"It's Bedlam for you!"
	.GSTR STR?483,"It's not worth it. Believe me."
	.GSTR STR?27,"It's too dark to see a thing."
	.GSTR STR?507,"Jamison grins down at you, a dazzling white smile"
	.GSTR STR?506,"Jamison touches your hair softly"
	.GSTR STR?459,"Kicked into a far corner is a pile of clothes."
	.GSTR STR?140,"Kicking"
	.GSTR STR?144,"Knocking on"
	.GSTR STR?397,"Lafond cries, ""No deal then. Take them, men!"" The dragoons pour down the cliff."
	.GSTR STR?95,"Lafond grabs your hair and pulls your head sharply back, clinching your arms to your sides. "
	.GSTR STR?374,"Lafond hits you back. The end is not sweet and not fast."
	.GSTR STR?381,"Lafond pulls the sheets up to cover you both, pressing his long flaccid body against yours. Waves crash against the base of the cliff."
	.GSTR STR?530,"Lafond's voice is cold, lazy, ""You will die, you know, Jamison."""
	.GSTR STR?248,"launch"
	.GSTR STR?110,"leave the game[EVENT: GAME OVER]"
	.GSTR STR?526,"Leave yer honey be, wench. He'll join ye anon."
	.GSTR STR?105,"letters"
	.GSTR STR?160,"light"
	.GSTR STR?442,"Lit only with moonlight through the open window, tonight this room is serving as a ladies' dressing room. An exit lies to the north."
	.GSTR STR?135,"look"
	.GSTR STR?62,"Look around you.
"
	.GSTR STR?149,"look inside"
	.GSTR STR?466,"Love Transcending Death"
	.GSTR STR?99,"M-Beg"
	.GSTR STR?55,"Mama would have been shocked.
"
	.GSTR STR?152,"marrying"
	.GSTR STR?521,"Me name's Andy Crulley, and ladies learn to love me"
	.GSTR STR?154,"move"
	.GSTR STR?469,"mutters something to himself. You hear an occasional ""Zounds!"""
	.GSTR STR?158,"nega"
	.GSTR STR?258,"Nicholas stops at your cry, and turns, curious, to face Crulley just as the pistol sprays shot into his chest."
	.GSTR STR?510,"Nicholas's hands are smooth and cool"
	.GSTR STR?437,"No expense has been spared to make this long dim hallway anything but a servant's corridor. The foyer is east, a kitchen north of you."
	.GSTR STR?97,"Not Here"
	.GSTR STR?71,"Nothing happens.
"
	.GSTR STR?338,"on"
	.GSTR STR?451,"Once a cell, now, with the door missing, made into a guard's bunkroom, this room is distinctly uncomfortable. Gasps of air are forced through a crack in the seaward wall of the room. The way out is west of you."
	.GSTR STR?420,"One bamboo slat at the back seems to be loose."
	.GSTR STR?440,"One long table set across the north entrance indicates that supper was served here earlier. West of you is the ballroom."
	.GSTR STR?103,"OOPS"
	.GSTR STR?148,"open"
	.GSTR STR?465,"Orphan"
	.GSTR STR?309,"Other cries rise to match yours as you sweep down the center of the ballroom in an avalanche of dancers, knocking yourself unconscious against the far wall. You awaken the next morning, in the village, embarrassed and alone."
	.GSTR STR?462,"Out of the smoke staggers Davis, tugging a bloodied knife from the back of a pirate. Davis's eyes gleam white from a face blackened and bloody, his lips dark red as if he has been drinking blood. He turns to face you."
	.GSTR STR?74,"Pardon?
"
	.GSTR STR?418,"Perfumed by the heady odor of the night-blooming jasmine entwined in the bamboo latticework, this folly is a cool, dark haven."
	.GSTR STR?161,"pick"
	.GSTR STR?467,"Pirate Queen"
	.GSTR STR?164,"Playing in this way with"
	.GSTR STR?51,"PLUNDERED HEARTS"
	.GSTR STR?193,"posi"
	.GSTR STR?162,"pour"
	.GSTR STR?100,"Preaction"
	.GSTR STR?101,"PRSI"
	.GSTR STR?102,"PRSO"
	.GSTR STR?153,"Pulling"
	.GSTR STR?163,"Pushing"
	.GSTR STR?340,"put"
	.GSTR STR?312,"put anything into"
	.GSTR STR?337,"put the stone in"
	.GSTR STR?533,"Rapiers click and slide. ""Bad parry, Captain,"" Lafond says."
	.GSTR STR?167,"read"
	.GSTR STR?194,"remove"
	.GSTR STR?111,"restart[EVENT: GAME OVER]"
	.GSTR STR?169,"return it to"
	.GSTR STR?46,"rief descriptions.
"
	.GSTR STR?173,"search"
	.GSTR STR?176,"Shaking"
	.GSTR STR?220,"ship:1023"
	.GSTR STR?221,"ship:1032"
	.GSTR STR?222,"ship:1137"
	.GSTR STR?223,"ship:1149"
	.GSTR STR?225,"ship:1161"
	.GSTR STR?226,"ship:1165"
	.GSTR STR?227,"ship:1381"
	.GSTR STR?229,"ship:1387"
	.GSTR STR?231,"ship:1520"
	.GSTR STR?234,"ship:1685"
	.GSTR STR?235,"ship:1693"
	.GSTR STR?236,"ship:1699"
	.GSTR STR?238,"ship:1708"
	.GSTR STR?239,"ship:1716"
	.GSTR STR?241,"ship:1776"
	.GSTR STR?242,"ship:1781"
	.GSTR STR?244,"ship:1868"
	.GSTR STR?245,"ship:1942"
	.GSTR STR?209,"ship:216"
	.GSTR STR?246,"ship:2434"
	.GSTR STR?249,"ship:2861"
	.GSTR STR?250,"ship:2863"
	.GSTR STR?251,"ship:2865"
	.GSTR STR?252,"ship:2870"
	.GSTR STR?253,"ship:2874"
	.GSTR STR?254,"ship:2891"
	.GSTR STR?255,"ship:2901"
	.GSTR STR?256,"ship:2927"
	.GSTR STR?210,"ship:333"
	.GSTR STR?211,"ship:573"
	.GSTR STR?212,"ship:580"
	.GSTR STR?214,"ship:664"
	.GSTR STR?216,"ship:685"
	.GSTR STR?217,"ship:690"
	.GSTR STR?517,"Sleep overtakes you and you slump into unconsiousness."
	.GSTR STR?352,"slippered toes"
	.GSTR STR?184,"soak"
	.GSTR STR?487,"Some bloodied flesh "
	.GSTR STR?49,"Something cracks over your head, knocking you unconscious.
   You awaken, cuddled in a huge purple and gold curtained bed, with a shocking migraine. The man lying next to you pays no heed to your complaints, and commands you in French when you try to defend yourself. He tires of you within a few weeks, but lets you work the streets of Santa Ananas."
	.GSTR STR?56,"Sorry, no loitering,"" says the butler"
	.GSTR STR?147,"sound"
	.GSTR STR?204,"stand up"
	.GSTR STR?305,"Startled, Lafond raises his sword and you fly onto the blade. You fall over your lover's body and expire, your lips on his in a kiss outlasting death."
	.GSTR STR?377,"steal jewelry"
	.GSTR STR?25,"Steep stairs descend "
	.GSTR STR?93,"Stunned, Crulley collapses at your feet, his eyes rolling"
	.GSTR STR?61,"Suicide is not the answer.
"
	.GSTR STR?186,"Swimming"
	.GSTR STR?528,"Swords engage and disengage."
	.GSTR STR?188,"talk to"
	.GSTR STR?107,"talk to characters."
	.GSTR STR?481,"That is a waste of time."
	.GSTR STR?2,"That is thoroughly unladylike behavior.
"
	.GSTR STR?484,"That seems a useless idea."
	.GSTR STR?54,"That wouldn't be polite.
"
	.GSTR STR?53,"That's not done in polite society.
"
	.GSTR STR?43,"The ballroom is a "
	.GSTR STR?508,"The blue of the captain's eyes seems to deepen, looking at you"
	.GSTR STR?441,"The carpeted hallway turns from west to north here, extending into the east wing. A long table blocks the way south."
	.GSTR STR?404,"The door at the top of the stairs won't open."
	.GSTR STR?326,"The door creaks open to reveal a black well, water hushing deep within"
	.GSTR STR?409,"The door is barred."
	.GSTR STR?403,"The Falcon follows a step behind."
	.GSTR STR?431,"The front door stands open to the south, light splayed out onto a drive stretching north into the jungle. A path leads around the western wing of the house; jutting out from the east wing is a tall hedge."
	.GSTR STR?412,"The grate is too small."
	.GSTR STR?90,"The monster lunges at you, chain rattling, roaring and angry. "
	.GSTR STR?84,"The pirate captain "
	.GSTR STR?399,"The pistol fires with a deafening roar, spraying shot into Nicholas. Time stops as he falls, reaching for you, your name his last breath.
   The battle afterwards is short and bloody. Spurred by grief, you fight hard, yet greet benumbing death thankfully."
	.GSTR STR?496,"The reefs are definitely getting larger"
	.GSTR STR?495,"The reefs seem a little larger than you thought before"
	.GSTR STR?494,"The ship is floating midway between the island and a line of reefs"
	.GSTR STR?499,"The sound of splintering wood reverberates through the ship as it drifts onto the reefs"
	.GSTR STR?425,"The steps lead south."
	.GSTR STR?375,"The study of Latin"
	.GSTR STR?435,"The underbrush is much too thick to enter."
	.GSTR STR?427,"The undergrowth is much too thick to enter."
	.GSTR STR?430,"The west wall of the house is that way."
	.GSTR STR?439,"The windows overlooking the veranda do not open."
	.GSTR STR?32,"There's nothing "
	.GSTR STR?9,"They already are.
"
	.GSTR STR?523,"They calls me Andy, but I'm really randy"
	.GSTR STR?323,"They clamp shut"
	.GSTR STR?219,"thick"
	.GSTR STR?475,"Think again, guv'nor."
	.GSTR STR?405,"This is a gloomy, damp area at the bottom of the Helena Louise. To the fore there seems to be a little more light, or you can climb up some steep stairs."
	.GSTR STR?476,"This is no time to get hysterical."
	.GSTR STR?79,"This reveals nothing new.
"
	.GSTR STR?444,"This room is exotically furnished with a Turkey divan and chairs. The exit is south."
	.GSTR STR?456,"This short passage turns from east to north to stop abruptly at an iron door."
	.GSTR STR?455,"This tiny cell is airless and shivering cold, entirely empty of anything but darkness. A wooden door leads west."
	.GSTR STR?413,"This tiny kitchen smells of old stew and yeast. A low door to starboard shows the way out."
	.GSTR STR?168,"to"
	.GSTR STR?5,"To your surprise, "
	.GSTR STR?292,"Too drugged to keep your grip on the ropes, you slip into the sea."
	.GSTR STR?156,"Trying to destroy"
	.GSTR STR?157,"Trying to muzzle"
	.GSTR STR?174,"Turning"
	.GSTR STR?310,"untie it"
	.GSTR STR?138,"verbs:1077"
	.GSTR STR?139,"verbs:1079"
	.GSTR STR?141,"verbs:1084(a)"
	.GSTR STR?142,"verbs:1084(b)"
	.GSTR STR?143,"verbs:1084(c)"
	.GSTR STR?145,"verbs:1140"
	.GSTR STR?146,"verbs:1147"
	.GSTR STR?151,"verbs:1382"
	.GSTR STR?155,"verbs:1406"
	.GSTR STR?165,"verbs:1723(a)"
	.GSTR STR?166,"verbs:1723(b)"
	.GSTR STR?170,"verbs:1797"
	.GSTR STR?171,"verbs:1799"
	.GSTR STR?175,"verbs:1949"
	.GSTR STR?177,"verbs:1975(a)"
	.GSTR STR?178,"verbs:1975(b)"
	.GSTR STR?179,"verbs:1975(c)"
	.GSTR STR?180,"verbs:1978(a)"
	.GSTR STR?181,"verbs:1978(b)"
	.GSTR STR?182,"verbs:1978(c)"
	.GSTR STR?183,"verbs:2033"
	.GSTR STR?187,"verbs:2200"
	.GSTR STR?117,"verbs:373"
	.GSTR STR?118,"verbs:379"
	.GSTR STR?119,"verbs:382"
	.GSTR STR?121,"verbs:390"
	.GSTR STR?122,"verbs:392"
	.GSTR STR?128,"verbs:535(a)"
	.GSTR STR?129,"verbs:535(b)"
	.GSTR STR?130,"verbs:538(a)"
	.GSTR STR?131,"verbs:538(b)"
	.GSTR STR?134,"verbs:656"
	.GSTR STR?137,"verbs:994"
	.GSTR STR?36,"way to do that.
"
	.GSTR STR?192,"wear"
	.GSTR STR?480,"What an odd thing to attempt."
	.GSTR STR?86,"What the devil are you doing here! Lafond is a dangerous man to play with!"" Jamison "
	.GSTR STR?525,"What, afrighted of a lick o' the whip?"
	.GSTR STR?150,"with"
	.GSTR STR?492,"With a creak and a crash, somewhere a mast falls to the deck"
	.GSTR STR?104,"words"
	.GSTR STR?524,"Would yer like a taste o' water?"
	.GSTR STR?527,"Ye're a tasty doxy to let slip, but no 'elp fer it."
	.GSTR STR?40,"You already have"
	.GSTR STR?454,"You are at the far end of a dank passageway heading north. A wooden door leads east."
	.GSTR STR?429,"You are in a small clearing under the western side of the house. Heavy vines creep up the wall past a second floor window, open to the night air. Southwest is an opening in the bushes."
	.GSTR STR?401,"You are in an officer's cabin, lit by the firelight glowing through a porthole. A door is to starboard. Except for the built-in bed, the room seems to have been emptied thoroughly, if hurriedly."
	.GSTR STR?498,"You are misted in the spray of waves hitting the reefs. The island is far away"
	.GSTR STR?426,"You are on a well-trampled lawn at the side of the house, one low doorway leading in to the east. Gravelled paths lead north and south into the undergrowth."
	.GSTR STR?38,"You aren't "
	.GSTR STR?294,"You awake too late to save the ship -- or rather, you never wake at all."
	.GSTR STR?34,"You can see"
	.GSTR STR?37,"You can't "
	.GSTR STR?64,"You can't do that from here.
"
	.GSTR STR?458,"You can't go that way."
	.GSTR STR?65,"You can't go that way.
"
	.GSTR STR?35,"You can't see any "
	.GSTR STR?423,"You can't see any way to get past into the folly."
	.GSTR STR?408,"You can't swim, and decide not to jump."
	.GSTR STR?421,"You crouch in the green rustlings of the hedge. Not far east, wind keens up the cliff, high above swells breaking against a rocky shore. You know the folly is somewhere to the west. North, the hedge is somewhat less dense."
	.GSTR STR?18,"You dip the oars and pull them towards you. The "
	.GSTR STR?50,"You find yourself speechless with dread.
"
	.GSTR STR?479,"You have lost your mind."
	.GSTR STR?57,"You haven't the strength.
"
	.GSTR STR?534,"You hear a duellist leap forward, and swords clash, parrying."
	.GSTR STR?531,"You hear a piece of furniture being knocked over."
	.GSTR STR?529,"You hear metal scrape metal. A woman gasps."
	.GSTR STR?12,"You might be able to squeeze past it.
"
	.GSTR STR?422,"You might fight your way a few feet into the thorns but you'd only tear your clothes."
	.GSTR STR?3,"You pace out the steps.
"
	.GSTR STR?414,"You perch on a platform high above the deck, giving a view of the endless sea and the southernmost cliffs of the island, where a house pokes out of the vegetation. It gives off a general glow, but no lights can be seen in any of the second story windows. A tiny beach nestles into the base of the cliff."
	.GSTR STR?41,"You pull the cloth aside momentarily."
	.GSTR STR?493,"You recognize a voice from far away, ""Don't take that! Look in the cabin at the stern -- you'll find some fun there!"" It sounds like Davis"
	.GSTR STR?0,"You shake your head"
	.GSTR STR?92,"You squeeze three colorless drops "
	.GSTR STR?443,"You stand in a carpeted hallway, leading east to a stair landing. Rooms lie north and south of you."
	.GSTR STR?446,"You stand in a carpeted hallway, leading west to a stair landing. To the north is an ornately carved door. From the south comes the impression of light and air."
	.GSTR STR?515,"You stare into space for a long, thoughtless moment. It seems very hard to think, you think, but you aren't sure."
	.GSTR STR?417,"You stop at a steep cliff-face."
	.GSTR STR?307,"You sweep down into the ballroom, felling dancer and pirate alike. Unfortunately, one of Jamison's crew, mistaking your shortcut for an attack, greets you with a sharpened dagger."
	.GSTR STR?39,"You'll have to "
	.GSTR STR?416,"You'll have to row that way."
	.GSTR STR?44,"You're already "
	.GSTR STR?66,"You're holding it!
"
	.GSTR STR?31,"You're not holding"
	.GSTR STR?213,"Your battered hands can take no more. Your grip loosens and the sea comes up to break your fall."
	.GSTR STR?516,"Your eyes are extraordinarily dry. You blink to moisten them, and snort awake a minute later, drool dripping down your chin."
	.GSTR STR?514,"Your face convulses in a prodigious yawn."
	.ENDI
