<ROUTINE PRINT-DESC1 (OBJ)
    <COND (.OBJ
        <TELL D .OBJ>)>>

<ROUTINE PRINT-ID (ID "OPT" (CONDITION T))
    <COND (.CONDITION
        <TELL "[ID: " .ID ", PRSO: "> <PRINT-DESC1 ,PRSO> <TELL ", PRSI: "> <PRINT-DESC1 ,PRSI> <TELL "]">
        )>>

<ROUTINE PRINT-DEBUG (TEXT "OPT" (CONDITION T))
    <COND (.CONDITION
        <TELL "DEBUG FLAG: " .TEXT>
        )>>

; "============ THESE ARE USEFUL IN ALMOST EVERY GAME ============"
<ROUTINE IS-THEFT? ()
    <AND <VERB? TAKE>
    <EQUAL? ,PRSO ,LOG-READER ,LOG-TAPE ,KEY ,PUCE-SPOOL ,DIODE-M ,DETONATOR ,BLACKENED-DIODE ,DRILL ,SMALL-BIT
    ,DIARY ,TWENTY-PRONG-FROMITZ-BOARD ,NOTE ,CRYSTAL-BALL ,HEADLAMP ,TAFFY ,TWELVE-PRONG-FROMITZ-BOARD ,DIODE-J
    ,SPACESUIT ,BOOK ,PAPER ,PLATINUM-DETECTOR ,EXPLOSIVE ,SPRAY-CAN ,STRONG-BOX ,LETTER ,COIN ,ID-CHANGER>>>

<ROUTINE IS-OBJECT-OR-PROPERTY? ()
    <EQUAL? ,PRSO ,AIRLOCK-OBJECT ,AUTO-DOOR ,BALLOON ,BED ,BEDISTOR ,BLACKENED-DIODE ,BOOK
    ,BOOTS ,CAGE ,CALL-BUTTON ,CEILING ,COFFEE ,COIN
    ,COPILOT-SEAT ,COUNTER ,CRUMPLED-FORM ,CRYSTAL-BALL ,CUBICLE ,DESK ,DETONATOR ,DIARY ,DICE ,DIODE-J ,DIODE-M
    ,DISPENSER ,DRILL ,DRILLED-HOLE ,DRYER ,ELEVATOR-OBJECT ,ELEVATOR-SHAFT ,EQUIPMENT ,ETERNAL-FLAME
    ,EXERCISE-MACHINE ,EXPLOSIVE ,FIXTURES ,FOIL ,FOOD-KIT ,FORKLIFT ,FPU ,GARBAGE
    ,GRATING ,GRAY-GOO ,HEADLAMP ,HEATING-CHAMBER ,HOLDING-TANK ,HOUSING
    ,ID-CHANGER ,ID-READER ,INNER-AIRLOCK-DOOR ,INSTRUCTION-SHEET ,IRIS-HATCH ,JAMMER ,KEY
    ,KEYPAD ,LADDER ,LARGE-BIT ,LEASH ,LETTER ,LILAC-SPOOL ,LOCKER ,LOG-READER ,LOG-TAPE ,MAGAZINES
    ,MAUVE-SPOOL ,MEDIUM-BIT ,NANOFILM-READER ,NECTAR ,NOTE ,ORANGE-GOO
    ,OSTRICH-NIP ,OUTER-AIRLOCK-DOOR ,PALLETS ,PANEL ,PAPER ,PATTERN-OF-DOTS ,PEDESTAL ,PILOT-SEAT
    ,PLASTIC-BAG ,PLATINUM-DETECTOR ,PRESSER ,PUCE-SPOOL ,PULPIT ,PYRAMID ,RADIO
    ,ROULETTE-WHEEL ,SAFE ,SCULPTURE ,SECURITY-DOOR ,SHRUBBERY ,SIGN
    ,SIMULATION-BOOTH ,SKELETON ,SMALL-BIT ,SOUP ,SPACESUIT ,SPACETRUCK-HATCH ,SPACETRUCK-OBJECT ,SPRAY-CAN
    ,STAR ,STRONG-BOX ,STUN-GUN ,SWITCH ,SYSTEM-MONITORS ,TAFFY ,THERMOS ,TIMER ,TRASH-CAN
    ,TWELVE-PRONG-FROMITZ-BOARD ,TWENTY-PRONG-FROMITZ-BOARD ,VALIDATION-STAMP ,VILLAGE ,VILLAGE-FORM ,VOLUME
    ,WALLS ,WARDROBE ,WELDER ,WINDOW ,ZAPGUN>>

<ROUTINE IS-PERSON? ()
    <EQUAL? ,PRSO ,EVERYONE ,FLOYD ,HELEN ,HIM ,OLIVER ,PLATO ,PROTAGONIST ,REX>>

<ROUTINE IS-ANIMAL? ()
    <EQUAL? ,PRSO ,GRUE ,OSTRICH>>

<ROUTINE IS-SELF? ()
    <EQUAL? ,PRSO ,ME>>

<ROUTINE IS-PART-OF-SELF? ()
    <EQUAL? ,PRSO ,HANDS ,TONGUE>>

<ROUTINE IS-SELF-OR-PART-OF-SELF? ()
    <OR <IS-SELF?> <IS-PART-OF-SELF?>>>

<ROUTINE IS-YOUR-PROPERTY? ()
    <EQUAL? ,PRSO ,ASSIGNMENT-COMPLETION-FORM ,ROBOT-USE-AUTHORIZATION-FORM ,CLASS-THREE-SPACECRAFT-ACTIVATION-FORM
    ,CHRONOMETER ,PATROL-UNIFORM ,ID-CARD>>

<ROUTINE DANGEROUS-DRINK? ()
    <EQUAL? ,PRSO ,GRAY-GOO ,ORANGE-GOO>>


; "============ THESE DON'T NEED FILLING OUT, BUT CAN BE CHANGED ============"
<ROUTINE DANGEROUS-FOOD? ()
    <AND <OR <IS-PART-OF-SELF?> <IS-OBJECT-OR-PROPERTY?>> <NOT <EQUAL? ,PRSO ,SOUP ,TAFFY ,NECTAR>>>>

<ROUTINE IS-OBJ-PROP-ANIMAL? ()
    <OR <IS-OBJECT-OR-PROPERTY?>
        <IS-ANIMAL?>>>



