	; Strings to accompany annotated_games/borderzone/borderzone.zap

	.GSTR STR?642,""
	.GSTR STR?270,"

The man, seeming to notice you for the first time, turns casually in your direction. A second later, he seems to do a double take and you fear you have given yourself away."
	.GSTR STR?207,"
    Enkipna!
Nizemzi obstch im!
 Fingri en Morz!"
	.GSTR STR?290,"
Epilogue

Two days later, in your hotel room in Vienna, you notice a headline referring to an attempted assassination of a high-ranking American diplomat in the small border town of Ostnitz, Litzenburg. Accounts were sketchy, but it appears as if local police were tipped off about the impending attack in time to prevent it.

Congratulations! You get no medals, but you've successfully finished the first chapter of Border Zone. The story continues with Chapter 2:[RWD_ID: bystander:2844, VAL: 3] The Border. To start, type CONTINUE at the next prompt. 
"
	.GSTR STR?17,"
Epilogue

You are taken to police headquarters, and it is there that you learn of the successful assassination of the American ambassador. Back home, you are commended for your work - drawing attention away from the assassins and thereby helping assure the success of the mission. Sadly, you have failed in your real mission, but perhaps there was really nothing you could have done.
"
	.GSTR STR?215,"
You can see the owner of the hut"
	.GSTR STR?28," "
	.GSTR STR?134," A"
	.GSTR STR?646," can have no desirable effect."
	.GSTR STR?645," is useless, or worse."
	.GSTR STR?92," N for Next hint"
	.GSTR STR?150," One of the guards, close enough to take a good shot, fires, hitting you in the leg. You drop to the ground, injured, but alive."
	.GSTR STR?8," reaches for a gun which he carries under his belt. ""Have a seat,"" he advises, as he calls for the authorities on his radio telephone. All you can do is wait until they arrive."
	.GSTR STR?90," RETURN for hint"
	.GSTR STR?94," RETURN to see hint"
	.GSTR STR?114," With no hope of escape, you surrender to the guards, and are led away, handcuffed, to the border station."
	.GSTR STR?644," won't help you."
	.GSTR STR?345,", a pall of suspicion hangs over you. A short time later, you are reassigned away from sensitive materials, effectively ending your usefulness as an American double-agent. A small price to pay, perhaps, for the life of the Ambassador, but you cannot help but feel that things might have worked out much better."
	.GSTR STR?795,"!"
	.GSTR STR?5,".
"
	.GSTR STR?262,". He gives you a sidelong glance, and then a subtle double take, and you fear you have given yourself away"
	.GSTR STR?727,"... and don't worry much about odors."
	.GSTR STR?867,"...buying food from the vendor?"
	.GSTR STR?823,"...climbing the hut?"
	.GSTR STR?697,"...dropping things in the passageway?"
	.GSTR STR?698,"...entering other compartments (they're all different!)"
	.GSTR STR?871,"...figuring out how many Infocom people live in the Gribnitz apartments?"
	.GSTR STR?706,"...flushing things down the toilet?"
	.GSTR STR?703,"...giving the document (or shreds) to the bad spy?"
	.GSTR STR?820,"...going farther into the swamp?"
	.GSTR STR?819,"...having the bomb explode in the car? Or in or adjacent to the hut? Or the shed?"
	.GSTR STR?682,"...in the lavatory?"
	.GSTR STR?683,"...in your camera?"
	.GSTR STR?681,"...in your compartment?"
	.GSTR STR?702,"...jumping out the window in your compartment?"
	.GSTR STR?870,"...killing the sniper yourself? with Topaz's gun?"
	.GSTR STR?821,"...knocking on the tower door for a second time?"
	.GSTR STR?700,"...photographing the bad spy? yourself? the camera?"
	.GSTR STR?699,"...photographing things at the train platform?"
	.GSTR STR?701,"...pulling the stop cord on the train?"
	.GSTR STR?705,"...putting things in the sink?"
	.GSTR STR?704,"...reading the graffiti in the bathroom?"
	.GSTR STR?708,"...taking a gun from one of the guards?"
	.GSTR STR?868,"...taking food after toppling the cart?"
	.GSTR STR?869,"...throwing things at Topaz as he chases you?"
	.GSTR STR?707,"...trying to hide the document every place you can think of?"
	.GSTR STR?822,"...using the binoculars? On something you're carrying?"
	.GSTR STR?938,"""I am afraid that you really must come with me."""
	.GSTR STR?13,"""I am afraid you have not been very honest with us. We will need to ask some, how to say, more difficult questions now."" He motions to the guards, who lead you into a holding area nearby. After hours of questioning, you are finally released, but not before missing your rendezvous."
	.GSTR STR?936,"""I am in a hurry. If you wouldn't mind..."""
	.GSTR STR?940,"""I really must insist."" After a moment, the man speaks loudly in Frobnian, as if to somebody farther away than yourself."
	.GSTR STR?941,"""If you won't come out, we can arrange something else..."" His voice trails off in a rather sarcastic way."
	.GSTR STR?273,"""Thank you so much for your patience."" He leads you into your compartment and shuts the door."
	.GSTR STR?696,"[Please don't read further until you have successfully completed this chapter.]"
	.GSTR STR?3,"[That sentence isn't one I recognize.]
"
	.GSTR STR?34,"[Transcripting o"
	.GSTR STR?968,"A"
	.GSTR STR?407,"A branch falls from a nearby tree, startling you briefly. You turn back and press on through the forest, until you stop at a small wooden shed."
	.GSTR STR?389,"A branch falls from a nearby tree, startling you briefly. You turn back and press on through the forest."
	.GSTR STR?486,"A brisk wind gives you a deep chill, but you continue along the road to the point at which it bends to the north."
	.GSTR STR?472,"A brisk wind gives you a deep chill, but you reenter the forest. Soon, you rejoint the road which now is running from east to west."
	.GSTR STR?454,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you press on into the forest."
	.GSTR STR?480,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you press on through the forest, finally coming to the back door of a small wooden hut. Smoke rises from the chimney above."
	.GSTR STR?384,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you press on through the forest."
	.GSTR STR?432,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you press on to the north side of the hut."
	.GSTR STR?439,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you press on to the south side of the hut."
	.GSTR STR?428,"A cold gust of wind swirls snow into your face, making it difficult to see clearly, but you walk to the front door of the hut."
	.GSTR STR?510,"A family of five is having what appears to be a rather heated argument. You are nearly socked in the head before you retreat to the corridor. The door slams behind you."
	.GSTR STR?609,"A few dozen discarded boxes are strewn on the ground here."
	.GSTR STR?505,"A guard prevents you from boarding the train. ""Nye mneshna pletska bli!"""
	.GSTR STR?128,"A lone guard, toting a machine gun, walks up behind you and announces himself. It is too late to react, and you are quickly taken to a nearby waiting car, and thereby into custody."
	.GSTR STR?167,"A moment later, they burst through the door and take you into custody."
	.GSTR STR?455,"A pile of snow falls on your head from a heavily laden branch above. You shake it off, and continue into the forest."
	.GSTR STR?415,"A pile of snow falls on your head from a heavily laden branch above. You shake it off, and continue through the forest, until you come to a small wooden shed."
	.GSTR STR?409,"A pile of snow falls on your head from a heavily laden branch above. You shake it off, and continue through the forest, until you reach a small wooden shed."
	.GSTR STR?411,"A pile of snow falls on your head from a heavily laden branch above. You shake it off, and continue through the forest."
	.GSTR STR?297,"A shot rings out, then another. The sound echoes through the square, followed by a different one, the sound of screams, then sirens. Police run onto the dais, as the body of the American ambassador is carried off on a stretcher. By instinct, you know he is already dead."
	.GSTR STR?522,"A smallish woman, in peasant dress, bumps into you. She looks at you fiercely and says"
	.GSTR STR?508,"A stern-faced guard refuses to let you pass."
	.GSTR STR?520,"A stern-faced Russian soldier brushes into you. He leers at you, spits, and says"
	.GSTR STR?844,"A variety of reasons. First, anything you do that might cause him to think you're intent on defeating him will get you killed. Also, arriving at his door while you're being pursued is a definite killer."
	.GSTR STR?518,"A young boy, perhaps twelve years old, backs into you. He bows, saying"
	.GSTR STR?514,"A young girl, holding her mother's hand, walks into you and stumbles. She says, meekly,"
	.GSTR STR?20,"Actor"
	.GSTR STR?123,"After what seems like an eternity, a man opens the door and steps outside to talk to the men."
	.GSTR STR?165,"All at once, you feel lightheaded and stumble to the ground, overcome by the cumulative effects of pain, blood loss, cold, and your strenuous efforts. You are found not long afterwards, and placed under arrest."
	.GSTR STR?604,"alley just behind the vendor's cart"
	.GSTR STR?667,"Also, answering in a way that contradicts the evidence (i.e. the bloodiness of the floor), adds suspicion."
	.GSTR STR?674,"Also, if you have been seen outside of your compartment holding any unusual items - a carnation, a briefcase, etc..."
	.GSTR STR?660,"Also, the admission that you have seen the American agent is enough to generate a little suspicion."
	.GSTR STR?743,"Also, the occupant will leave at some point to get more wood from the shed."
	.GSTR STR?744,"Also, there's another way, but that's for you to figure out..."
	.GSTR STR?861,"Also, you know that Topaz can be made to kill the sniper for you."
	.GSTR STR?769,"Also, you'll need something to break the chain links."
	.GSTR STR?611,"An empty trash can is standing here."
	.GSTR STR?801,"An explosive device would be useful in this regard."
	.GSTR STR?842,"An interesting dilemma. If you kill the sniper, your cover is broken, due to suspicion regarding the gun used (yours) and the incident on the train, in which you lost the coded document. On the other hand, you stop the assassination. All in all, a mixed bag. You can do better."
	.GSTR STR?640,"An official car is here, bearing the seal of Frobnia."
	.GSTR STR?516,"An old man seems to walk right into you. He adjusts his glasses and says"
	.GSTR STR?865,"And HIDE or STAND BEHIND THE DOOR so that you won't get in Topaz's line of fire and get killed with the sniper."
	.GSTR STR?778,"And why not?"
	.GSTR STR?545,"antique shop"
	.GSTR STR?593,"apartment building"
	.GSTR STR?919,"Apparently, one of the guards has been ordered to search the area, for a lone guard is walking past the window. Fortunately, he is concentrating on the grounds, rather than the inside of the hut."
	.GSTR STR?127,"Apparently, one of the guards was asked to check out the area around the hut. Finding the door open, he enters, finds you, and pulls you out of the hut to the waiting guards."
	.GSTR STR?917,"As if on command, a single guard breaks off from the group and walks slowly and carefully to the northeast."
	.GSTR STR?172,"As you start to reach the ladder, the guard glimpses you out of the corner of his eye, and instinctively swings his weapon into your head, knocking you onto the ground. You survive, fortunately, but you have been captured."
	.GSTR STR?385,"Attempting a run directly at the border station would be tantamount to surrendering to the authorities and giving up on your mission.[ID: border:1857]"
	.GSTR STR?969,"B"
	.GSTR STR?527,"back side of the apartment building"
	.GSTR STR?537,"back side of the office building"
	.GSTR STR?304,"bad:1166(a)"
	.GSTR STR?305,"bad:1166(b)"
	.GSTR STR?306,"bad:1166(c)"
	.GSTR STR?307,"bad:1480(a)"
	.GSTR STR?308,"bad:1480(b)"
	.GSTR STR?310,"bad:1745"
	.GSTR STR?311,"bad:1780"
	.GSTR STR?313,"bad:1803"
	.GSTR STR?315,"bad:1823"
	.GSTR STR?319,"bad:1966"
	.GSTR STR?320,"bad:1992"
	.GSTR STR?321,"bad:1995"
	.GSTR STR?322,"bad:1998"
	.GSTR STR?324,"bad:2100"
	.GSTR STR?325,"bad:2129"
	.GSTR STR?331,"bad:2714"
	.GSTR STR?335,"bad:2833"
	.GSTR STR?336,"bad:2851"
	.GSTR STR?337,"bad:2884"
	.GSTR STR?338,"bad:2917"
	.GSTR STR?340,"bad:2987"
	.GSTR STR?341,"bad:3030"
	.GSTR STR?342,"bad:3034"
	.GSTR STR?344,"bad:3059"
	.GSTR STR?346,"bad:3066"
	.GSTR STR?348,"bad:3102"
	.GSTR STR?349,"bad:3142"
	.GSTR STR?350,"bad:3191"
	.GSTR STR?351,"bad:3199"
	.GSTR STR?352,"bad:3222"
	.GSTR STR?353,"bad:3256"
	.GSTR STR?354,"bad:3258"
	.GSTR STR?355,"bad:3316"
	.GSTR STR?356,"bad:3342"
	.GSTR STR?357,"bad:3348"
	.GSTR STR?358,"bad:3361"
	.GSTR STR?359,"bad:3375"
	.GSTR STR?294,"bad:51"
	.GSTR STR?299,"bad:590"
	.GSTR STR?301,"bad:728"
	.GSTR STR?302,"bad:739"
	.GSTR STR?295,"bad:78"
	.GSTR STR?303,"bad:816"
	.GSTR STR?736,"Basically, three enemy guards are in the car."
	.GSTR STR?827,"Be careful; the police are sometimes inside, checking around. They know who you are, so you'd better not get seen."
	.GSTR STR?35,"begin"
	.GSTR STR?966,"Belboz"
	.GSTR STR?964,"Besnap"
	.GSTR STR?752,"Better might be ""Where...?"""
	.GSTR STR?993,"Bextra"
	.GSTR STR?40,"Biting "
	.GSTR STR?975,"Blenka"
	.GSTR STR?997,"Blivik"
	.GSTR STR?561,"bookstore"
	.GSTR STR?173,"border:1017"
	.GSTR STR?174,"border:1026"
	.GSTR STR?177,"border:1047"
	.GSTR STR?178,"border:1067"
	.GSTR STR?179,"border:1075"
	.GSTR STR?180,"border:1084"
	.GSTR STR?181,"border:1093"
	.GSTR STR?182,"border:1105"
	.GSTR STR?183,"border:1113"
	.GSTR STR?184,"border:1121"
	.GSTR STR?185,"border:1135"
	.GSTR STR?186,"border:1148"
	.GSTR STR?187,"border:1155"
	.GSTR STR?188,"border:1162"
	.GSTR STR?189,"border:1188"
	.GSTR STR?190,"border:1194"
	.GSTR STR?191,"border:1202(a)"
	.GSTR STR?192,"border:1202(b)"
	.GSTR STR?193,"border:1225(a)"
	.GSTR STR?194,"border:1225(b)"
	.GSTR STR?195,"border:1228(a)"
	.GSTR STR?196,"border:1228(b)"
	.GSTR STR?197,"border:1258"
	.GSTR STR?136,"border:137"
	.GSTR STR?201,"border:1416"
	.GSTR STR?202,"border:1524"
	.GSTR STR?204,"border:1552"
	.GSTR STR?205,"border:1560"
	.GSTR STR?206,"border:1562"
	.GSTR STR?208,"border:1753"
	.GSTR STR?210,"border:1784"
	.GSTR STR?211,"border:1791"
	.GSTR STR?212,"border:1795"
	.GSTR STR?213,"border:1798"
	.GSTR STR?139,"border:206"
	.GSTR STR?140,"border:209"
	.GSTR STR?216,"border:2687"
	.GSTR STR?217,"border:2743"
	.GSTR STR?218,"border:2844"
	.GSTR STR?219,"border:3238"
	.GSTR STR?220,"border:3259"
	.GSTR STR?227,"border:3533"
	.GSTR STR?228,"border:3538(a)"
	.GSTR STR?229,"border:3538(b)"
	.GSTR STR?230,"border:3665"
	.GSTR STR?231,"border:3668"
	.GSTR STR?232,"border:3675"
	.GSTR STR?234,"border:3729"
	.GSTR STR?235,"border:3735"
	.GSTR STR?237,"border:3742"
	.GSTR STR?242,"border:3851"
	.GSTR STR?141,"border:387"
	.GSTR STR?243,"border:3890"
	.GSTR STR?249,"border:3998"
	.GSTR STR?252,"border:4014"
	.GSTR STR?253,"border:4019"
	.GSTR STR?254,"border:4021"
	.GSTR STR?142,"border:407"
	.GSTR STR?255,"border:4237"
	.GSTR STR?144,"border:503(a)"
	.GSTR STR?145,"border:503(b)"
	.GSTR STR?146,"border:503(c)"
	.GSTR STR?147,"border:549"
	.GSTR STR?149,"border:561"
	.GSTR STR?151,"border:566"
	.GSTR STR?152,"border:629"
	.GSTR STR?153,"border:632"
	.GSTR STR?155,"border:640"
	.GSTR STR?156,"border:651"
	.GSTR STR?159,"border:685"
	.GSTR STR?160,"border:690"
	.GSTR STR?162,"border:734"
	.GSTR STR?164,"border:753"
	.GSTR STR?166,"border:766"
	.GSTR STR?168,"border:781"
	.GSTR STR?170,"border:813"
	.GSTR STR?171,"border:820"
	.GSTR STR?784,"Both are moving, so you should WATCH them."
	.GSTR STR?423,"Both the road and the railroad tracks lead into a dark tunnel to the south. If your memory from the train serves, this tunnel is miles long, and without interruption. The tracks continue toward the border to the northwest, and the road bends to the northeast. A dark forest stretches before you to the north."
	.GSTR STR?612,"bottom of the fire escape"
	.GSTR STR?973,"Brgmiz"
	.GSTR STR?983,"Brlensk"
	.GSTR STR?967,"Brzni"
	.GSTR STR?748,"But now, the owner's returned as well. The squeaky door alerts him to your presence."
	.GSTR STR?343,"But Topaz is there, and taking no chances, fires three shots at you, killing you almost instantly."
	.GSTR STR?802,"But where to put it?"
	.GSTR STR?265,"bystander:1083"
	.GSTR STR?266,"bystander:1380"
	.GSTR STR?267,"bystander:1398"
	.GSTR STR?268,"bystander:1442"
	.GSTR STR?269,"bystander:1446"
	.GSTR STR?256,"bystander:165"
	.GSTR STR?276,"bystander:1831"
	.GSTR STR?277,"bystander:2117"
	.GSTR STR?278,"bystander:2143"
	.GSTR STR?280,"bystander:2361"
	.GSTR STR?281,"bystander:2425"
	.GSTR STR?282,"bystander:2432"
	.GSTR STR?283,"bystander:2486"
	.GSTR STR?284,"bystander:2505"
	.GSTR STR?285,"bystander:2509"
	.GSTR STR?286,"bystander:2594"
	.GSTR STR?287,"bystander:2639"
	.GSTR STR?288,"bystander:2779"
	.GSTR STR?289,"bystander:2804"
	.GSTR STR?291,"bystander:2847"
	.GSTR STR?292,"bystander:2849"
	.GSTR STR?293,"bystander:2886"
	.GSTR STR?257,"bystander:416"
	.GSTR STR?258,"bystander:431"
	.GSTR STR?259,"bystander:435"
	.GSTR STR?260,"bystander:453"
	.GSTR STR?261,"bystander:685"
	.GSTR STR?263,"bystander:835"
	.GSTR STR?264,"bystander:890"
	.GSTR STR?970,"C"
	.GSTR STR?849,"Can Topaz help me?"
	.GSTR STR?851,"Can you arrange for Topaz to kill the sniper?"
	.GSTR STR?725,"Can you confuse their senses?"
	.GSTR STR?721,"Can you find food to distract them?"
	.GSTR STR?723,"Can you hide your tracks?"
	.GSTR STR?857,"Can you put a stumbling block in his way?"
	.GSTR STR?120,"Carefully looking around the side of the house, you can see three men approaching the door of the hut, then knocking loudly."
	.GSTR STR?989,"Carlyni"
	.GSTR STR?810,"Check out the brace; you can GET ON it."
	.GSTR STR?692,"Check your Frobnian phrase book (in your Border Zone package) for the translation of the phrase that your contact was supposed to repeat. Be careful; the exact words must be used."
	.GSTR STR?578,"chemist's shop"
	.GSTR STR?676,"Clearly, you are under suspicion."
	.GSTR STR?43,"close"
	.GSTR STR?985,"Cnezeni"
	.GSTR STR?934,"compartment next to your own"
	.GSTR STR?541,"corner of Besnap and Fremzi"
	.GSTR STR?976,"Cyrink"
	.GSTR STR?971,"D"
	.GSTR STR?673,"Depending on how you handled your 'interview' with the trench coated man, you might have appeared suspicious."
	.GSTR STR?777,"Did you don your gas mask?"
	.GSTR STR?808,"Did you try knocking on the door?"
	.GSTR STR?722,"Didn't think so."
	.GSTR STR?990,"Dimwitz"
	.GSTR STR?650,"Don't even consider it!"
	.GSTR STR?974,"Dornik"
	.GSTR STR?836,"Down at the end is a fire-escape ladder."
	.GSTR STR?864,"DROP something before giving the password; it's presence will alert Topaz to yours. Oh, and make it small or the sniper will find it instead."
	.GSTR STR?902,"E"
	.GSTR STR?886,"east"
	.GSTR STR?885,"east-northeast"
	.GSTR STR?887,"east-southeast"
	.GSTR STR?782,"Either way, it doesn't reflect well on you."
	.GSTR STR?637,"elevator"
	.GSTR STR?581,"empty storefront"
	.GSTR STR?36,"end"
	.GSTR STR?606,"end of the alley"
	.GSTR STR?977,"Endrizen"
	.GSTR STR?901,"ENE"
	.GSTR STR?14,"Epilogue

Two days later, in your hotel room in Vienna, you notice the headline reporting the assassination of the American ambassador to Litzenburg in the small border town of Ostnitz. The apparent assassin was a member of a radical Islamic group, although details of the plot may never be known since the assassin himself was found dead at the scene of the crime, an apparent suicide."
	.GSTR STR?903,"ESE"
	.GSTR STR?951,"Excuse me. I am sorry."
	.GSTR STR?641,"F"
	.GSTR STR?70,"Fiddling with "
	.GSTR STR?330,"fifth"
	.GSTR STR?104,"Finally, you pass out from the cold, and you are fortunate enough not to have frozen to death before the border patrol finds you."
	.GSTR STR?619,"fire escape at the fifth floor"
	.GSTR STR?618,"fire escape at the fourth floor"
	.GSTR STR?615,"fire escape at the second floor"
	.GSTR STR?617,"fire escape at the third floor"
	.GSTR STR?972,"first"
	.GSTR STR?850,"Firstly, his interest and yours are similar - preventing the assassination. In your case, however, you daren't risk exposing yourself to Topaz, firstly, for fear of being seen by other Soviet agents and, secondly, for fear of being killed by Topaz, who has an axe to grind with you."
	.GSTR STR?930,"five compartments"
	.GSTR STR?998,"Flipni"
	.GSTR STR?925,"FOO"
	.GSTR STR?670,"For another, they know the American agent had it."
	.GSTR STR?766,"For example, the WORK SHOES in the hut."
	.GSTR STR?669,"For one reason, there's an important document missing."
	.GSTR STR?947,"Forgive me."
	.GSTR STR?929,"four compartments"
	.GSTR STR?329,"fourth"
	.GSTR STR?316,"From somewhere in the hallway, you can hear a muffled, cracking noise. Perhaps Topaz has mistakenly broken into one of the apartments nearby, hoping to find you inside. A few moments later, you hear feet racing down the hall, then silence."
	.GSTR STR?279,"From the sound of it, the train has just entered a tunnel. If memory serves, you should be very near the border now."
	.GSTR STR?830,"From the town square, try LOOKing AT THE WINDOWS or BUILDINGS. There are three open windows in the apartment building; the sniper is in one of them."
	.GSTR STR?978,"Galnitz"
	.GSTR STR?988,"Gentezek"
	.GSTR STR?366,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:18]"
	.GSTR STR?367,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:22]"
	.GSTR STR?370,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:292]"
	.GSTR STR?371,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:296]"
	.GSTR STR?373,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:342]"
	.GSTR STR?374,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the forest to the south.[ID: border:346]"
	.GSTR STR?386,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1860]"
	.GSTR STR?387,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1864]"
	.GSTR STR?391,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1933]"
	.GSTR STR?392,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1937]"
	.GSTR STR?395,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1979]"
	.GSTR STR?396,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:1983]"
	.GSTR STR?398,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:2019]"
	.GSTR STR?399,"Given the rate at which the searchlights are turning, it would be suicidal to attempt anything other than a direct run at the tower to the north.[ID: border:2023]"
	.GSTR STR?87,"globals:470(a)"
	.GSTR STR?88,"globals:470(b)"
	.GSTR STR?716,"Go east and north from your starting point."
	.GSTR STR?96,"good:11"
	.GSTR STR?116,"good:1103"
	.GSTR STR?125,"good:1280"
	.GSTR STR?126,"good:1286"
	.GSTR STR?129,"good:1327"
	.GSTR STR?131,"good:1336"
	.GSTR STR?133,"good:1459"
	.GSTR STR?100,"good:320"
	.GSTR STR?101,"good:352"
	.GSTR STR?102,"good:367"
	.GSTR STR?103,"good:382"
	.GSTR STR?105,"good:399"
	.GSTR STR?107,"good:638"
	.GSTR STR?108,"good:644"
	.GSTR STR?109,"good:676"
	.GSTR STR?110,"good:687"
	.GSTR STR?111,"good:844"
	.GSTR STR?113,"good:868"
	.GSTR STR?115,"good:966"
	.GSTR STR?724,"Guess not."
	.GSTR STR?621,"hallway near the fire escape"
	.GSTR STR?417,"Hanging from a hook near the door is a pair of binoculars."
	.GSTR STR?590,"hardware store"
	.GSTR STR?946,"Hartzi dazi!"
	.GSTR STR?728,"Have you been at the swamp?"
	.GSTR STR?695,"Have you ever tried...?"
	.GSTR STR?715,"Have you found any shelter?"
	.GSTR STR?732,"Have you observed it from up close?"
	.GSTR STR?825,"Have you seen your contact, the antique dealer?"
	.GSTR STR?680,"Have you tried hiding it...?"
	.GSTR STR?740,"Have you tried the front and back doors?"
	.GSTR STR?710,"Have you tried using a tourniquet?"
	.GSTR STR?956,"Having calmed down the crowd, Huttinger begins to speak. The words seem to careen through your head but make little impact - there are only moments now in which to act."
	.GSTR STR?158,"Having satisfied himself that he has been daydreaming, the guard moves back into the tower, shutting the door behind him."
	.GSTR STR?847,"He can be avoided by staying away from the cafe. The more you pass by there or spend time there, the more likely that he'll see you."
	.GSTR STR?519,"He stares you down as you look clearly at him, but his face reveals nothing more than his words."
	.GSTR STR?244,"He's"
	.GSTR STR?856,"He's about the same speed as you, so you're usually fine. Unless you're in the alley, trying to get to the fire-escape ladder. That takes more time than you've got."
	.GSTR STR?557,"Here, at the southwest corner of Ostnitz Square, you can walk down either Besnap Street to the east and west, or Ostnitz Street to the north and south. In the Square, thousands of people have gathered for the festivities which are to begin at noon."
	.GSTR STR?362,"him"
	.GSTR STR?726,"How about a place where you don't leave tracks..."
	.GSTR STR?783,"How can I avoid the border guards?"
	.GSTR STR?758,"How can I avoid the searchlights?"
	.GSTR STR?845,"How can I avoid Topaz?"
	.GSTR STR?796,"How can I cross the border?"
	.GSTR STR?767,"How can I cross the first fence?"
	.GSTR STR?678,"How can I deliver the document?"
	.GSTR STR?739,"How can I get into the hut?"
	.GSTR STR?745,"How can I get out of the hut?"
	.GSTR STR?714,"How can I get warm?"
	.GSTR STR?720,"How can I keep away from the dogs?"
	.GSTR STR?776,"How can I survive the tear gas?"
	.GSTR STR?657,"How do I answer the man?"
	.GSTR STR?807,"How do I get into the tower?"
	.GSTR STR?790,"How do I get past the second fence?"
	.GSTR STR?839,"How do I get the password?"
	.GSTR STR?833,"How do I get TO the sniper?"
	.GSTR STR?709,"How do I stop myself from bleeding?"
	.GSTR STR?751,"How do I use the explosive?"
	.GSTR STR?798,"How tall is the fence?"
	.GSTR STR?799,"How tall is the tower?"
	.GSTR STR?685,"However, you can deliver its contents."
	.GSTR STR?961,"Huttinger begins to speak. The words seem to careen through your head but make little impact - you have only moments in which to act."
	.GSTR STR?962,"Huttinger continues to speak, and the crowd responds with enthusiasm, interrupting him frequently."
	.GSTR STR?859,"I can't get the best ending. Why?"
	.GSTR STR?659,"If he thinks you are lying, it will raise his level of suspicion, regardless of what you said."
	.GSTR STR?746,"If the owner hasn't returned and there's no scout prowling around, it's no problem."
	.GSTR STR?759,"If you are not WATCHing them, you should."
	.GSTR STR?854,"If you can lead him there, you're home free. Almost."
	.GSTR STR?733,"If you get in it's way, you'll be caught."
	.GSTR STR?797,"If you haven't gotten to the guard tower yet, don't read any further."
	.GSTR STR?837,"If you TAKE THE TRASH CAN, then PUT THE TRASH CAN UNDER THE LADDER, then STAND ON THE CAN, you can easily reach the ladder. Then, go up to the proper floor."
	.GSTR STR?672,"If you're wearing that crushed carnation, you might look peculiar to them."
	.GSTR STR?124,"In front of the hut, three men, two guards armed with machine guns, and one who appears to be a civilian, are standing by the door. A few moments later, the door opens and a fourth man walks out. They begin to talk."
	.GSTR STR?831,"In the apartment building's lobby, there is a directory of residents; maybe there is some information there."
	.GSTR STR?298,"In the direction of the square, you hear the sound of shots being fired. You needn't be told what has happened - your agents are quite thorough - the ambassador is dead."
	.GSTR STR?666,"In the lavatory, across the hall and to the south, there is a towel. Get it, wet it, then use it to clean up the blood."
	.GSTR STR?881,"In your confusion, you've all but forgotten how cold it is outside."
	.GSTR STR?548,"inside of the antique shop"
	.GSTR STR?89,"INVISICLUES (TM)"
	.GSTR STR?711,"Is there any cloth or fabric you can use?"
	.GSTR STR?662,"Is there any reason the man might KNOW that you've seen the American agent?"
	.GSTR STR?691,"It depends on what the American agent said at the very beginning."
	.GSTR STR?658,"It is possible to answer either way, although you must be careful."
	.GSTR STR?800,"It might be possible to ""ride"" the tower across the border."
	.GSTR STR?425,"It would take hours to get through the tunnel, and your mission would undoubtably fail. You'd best find a way across the border."
	.GSTR STR?768,"It's electrified, so you'd best not touch it."
	.GSTR STR?49,"Kicking "
	.GSTR STR?838,"Knock on the door, and have the password handy. If you don't give the password quickly, the sniper will ignore you for the remainder of the scenario."
	.GSTR STR?55,"Knocking on "
	.GSTR STR?995,"Kooplitz"
	.GSTR STR?935,"lavatory"
	.GSTR STR?610,"Leaning up against the office building, a foul-smelling trash can is standing."
	.GSTR STR?37,"leave the game"
	.GSTR STR?982,"Lebniz"
	.GSTR STR?138,"left"
	.GSTR STR?914,"leftmost tower "
	.GSTR STR?987,"Lengnoz"
	.GSTR STR?326,"level just above the ground"
	.GSTR STR?735,"Like the north side of the hut."
	.GSTR STR?596,"lobby of the apartment building"
	.GSTR STR?1,"Look around you.
"
	.GSTR STR?665,"LOOK AT THE FLOOR to see the blood that he's left here. It's a dead giveaway, no pun intended. It would be best to clean up after him."
	.GSTR STR?21,"M-Beg"
	.GSTR STR?729,"Make sure that you ENTER THE SWAMP; then move somewhere else along the edge, so they'll lose the trail."
	.GSTR STR?762,"Make sure you understand where YOU are in relation to the three lights; the right times to cross differ depending on your position."
	.GSTR STR?848,"Maybe you don't want to avoid him..."
	.GSTR STR?862,"Meaning that Topaz must follow you up to the sniper's room. See the previous clue for help in this regard."
	.GSTR STR?933,"middle compartment"
	.GSTR STR?569,"middle of Ostnitz Square"
	.GSTR STR?631,"middle of the hallway"
	.GSTR STR?915,"middle tower "
	.GSTR STR?663,"Might the agent have left something behind, besides the document and the carnation?"
	.GSTR STR?199,"minute"
	.GSTR STR?25,"misc:741"
	.GSTR STR?27,"misc:764"
	.GSTR STR?29,"misc:776"
	.GSTR STR?31,"misc:793"
	.GSTR STR?979,"Mrtzki"
	.GSTR STR?60,"n"
	.GSTR STR?898,"N"
	.GSTR STR?176,"Naturally, the explosion attracts the attention of the border guards, who are rapidly on the scene."
	.GSTR STR?900,"NE"
	.GSTR STR?899,"NNE"
	.GSTR STR?913,"NNW"
	.GSTR STR?812,"No, we're not pulling your leg."
	.GSTR STR?794,"No."
	.GSTR STR?15,"Nobody responds. Maybe it is your accent, or maybe you should reread your phrase book, or just maybe nobody's interested."
	.GSTR STR?882,"north"
	.GSTR STR?635,"north end of the hallway"
	.GSTR STR?883,"north-northeast"
	.GSTR STR?897,"north-northwest"
	.GSTR STR?884,"northeast"
	.GSTR STR?931,"northernmost compartment"
	.GSTR STR?896,"northwest"
	.GSTR STR?584,"northwest corner of Ostnitz Square"
	.GSTR STR?649,"Not a chance!"
	.GSTR STR?19,"Not Here"
	.GSTR STR?750,"Now you can leave - just don't come back!"
	.GSTR STR?363,"number"
	.GSTR STR?912,"NW"
	.GSTR STR?805,"Oh, first you should set the timer and arm the device."
	.GSTR STR?730,"Oh, I hope you weren't wearing any of your nice shoes."
	.GSTR STR?775,"Oh, yeah. If you want to get through the fence, you'll have to BEND (or PULL) it back, otherwise you'll get zapped going through."
	.GSTR STR?779,"Oh, you don't have one."
	.GSTR STR?684,"Oh, you have? Then, you should be aware that you CANNOT deliver the document."
	.GSTR STR?754,"Oh... you won't want to be there when it goes off."
	.GSTR STR?846,"Once he's seen you, he will doggedly pursue you for the remainder of your alloted time (i.e. until the assassination happens.)"
	.GSTR STR?863,"Once you're in the sniper's room, Topaz will never find you in time unless you've helped him along."
	.GSTR STR?926,"one compartment"
	.GSTR STR?32,"One of the guards notices you and fires a warning shot. An alarm sounds, and you are rapidly surrounded by border guards..."
	.GSTR STR?981,"Onilik"
	.GSTR STR?950,"Oopzi dazi. Izi slep!"
	.GSTR STR?61,"open"
	.GSTR STR?781,"Or cheating?"
	.GSTR STR?835,"Or, have you been into the alley?"
	.GSTR STR?93,"P for Previous hint"
	.GSTR STR?943,"Pardon me, sir."
	.GSTR STR?945,"Pardon me."
	.GSTR STR?829,"Perhaps he is, in some way, visible from the street; the town square might be a good vantage point."
	.GSTR STR?771,"Perhaps RUBBER GLOVES, from the woodshed."
	.GSTR STR?780,"Perhaps you're playing the wrong game?"
	.GSTR STR?687,"PHOTOGRAPH the document."
	.GSTR STR?64,"Playing in this way with "
	.GSTR STR?22,"Preaction"
	.GSTR STR?860,"Presumably, you have found the sniper and know the password."
	.GSTR STR?942,"Pripsa dazi, vaz!"
	.GSTR STR?944,"Pripsa dazi!"
	.GSTR STR?980,"Profnim"
	.GSTR STR?23,"PRSI"
	.GSTR STR?24,"PRSO"
	.GSTR STR?62,"Pushing "
	.GSTR STR?91,"Q to go back"
	.GSTR STR?95,"Q to return to game"
	.GSTR STR?793,"Really."
	.GSTR STR?38,"restart"
	.GSTR STR?137,"right"
	.GSTR STR?916,"rightmost tower "
	.GSTR STR?712,"RIP your CLOTHES."
	.GSTR STR?984,"Rivni"
	.GSTR STR?965,"Riznik"
	.GSTR STR?992,"Robnerim"
	.GSTR STR?906,"S"
	.GSTR STR?33,"scenario:129"
	.GSTR STR?904,"SE"
	.GSTR STR?327,"second"
	.GSTR STR?932,"second northernmost compartment"
	.GSTR STR?757,"See ""How can I cross the border?"" for details."
	.GSTR STR?719,"See the question ""How do I get into the hut?"""
	.GSTR STR?818,"See the question regarding ""How can I cross the border?"""
	.GSTR STR?339,"Seeing that you have been followed, he screams with rage, ""You have betrayed us!"" Without a moment's hesitation, he pulls the trigger, ending your life."
	.GSTR STR?67,"Shaking "
	.GSTR STR?521,"She averts her gaze as you attempt to get a better look at her. You can tell she's fairly young and quite beautiful."
	.GSTR STR?841,"Should I kill the sniper?"
	.GSTR STR?554,"side entrance of the antique store"
	.GSTR STR?599,"sidewalk in front of the cafe"
	.GSTR STR?996,"Sinkriz"
	.GSTR STR?639,"sniper's room"
	.GSTR STR?890,"south"
	.GSTR STR?889,"south-southeast"
	.GSTR STR?891,"south-southwest"
	.GSTR STR?888,"southeast"
	.GSTR STR?626,"southern part of the hallway"
	.GSTR STR?892,"southwest"
	.GSTR STR?556,"southwest corner of Ostnitz square"
	.GSTR STR?532,"spot directly across from the vacant lot"
	.GSTR STR?117,"Spotting you just in time, the car skids to a slippery stop about fifteen feet in front of you. The doors quickly open, and two guards emerge, machine guns drawn. Brilliant white lights shine in your face. ""So happy to see you, Mister ... Topaz ... is that right?"" Through the lights, a face slowly appears - it is Viper, your archenemy. He shrugs apologetically, and says, ""If we had known you were coming, well, we would have brought a larger car..."" He signals to the guards, who thrust you into the trunk."
	.GSTR STR?905,"SSE"
	.GSTR STR?907,"SSW"
	.GSTR STR?655,"Stop wasting time."
	.GSTR STR?550,"storage room"
	.GSTR STR?908,"SW"
	.GSTR STR?603,"table he was seated at"
	.GSTR STR?565,"tailor's shop"
	.GSTR STR?749,"Take the oil can, then OIL THE HINGES."
	.GSTR STR?380,"That appears to be the problem at hand."
	.GSTR STR?26,"That last action of yours has alerted the owner of your presence. He calmly walks in, gun in hand, and places a call to the border patrol who quickly arrive to take you into custody."
	.GSTR STR?764,"That means warm and not bleeding."
	.GSTR STR?372,"That would be suicidal."
	.GSTR STR?375,"That would be suicidal.[ID: border:362]"
	.GSTR STR?376,"That would be suicidal.[ID: border:368]"
	.GSTR STR?378,"That would mean jumping off the tower to your death.[ID: border:461]"
	.GSTR STR?365,"That would put you directly in front of the border station, and that would be suicidal.[ID: border:14]"
	.GSTR STR?368,"That would put you directly in front of the border station, and that would be suicidal.[ID: border:239]"
	.GSTR STR?369,"That would put you directly in front of the border station, and that would be suicidal.[ID: border:242]"
	.GSTR STR?654,"That's a waste of time, and you haven't much left."
	.GSTR STR?652,"That's impossible!"
	.GSTR STR?648,"That's ridiculous!"
	.GSTR STR?135,"The"
	.GSTR STR?954,"The anthem finished, the mayor calls upon the head of the church of Litzenburg to give a benediction."
	.GSTR STR?959,"The anthem is now finished, and after a few moments, a benediction is read."
	.GSTR STR?826,"The antique shop is just west of the southwest corner of the square (i.e. south and west of your starting position)."
	.GSTR STR?457,"The bedroom is a shambles, consisting in all of a bed and a chair, over which are draped assorted clothes too numerous and jumbled to mention. A small  window looks south to a snowy landscape."
	.GSTR STR?430,"The blowing snow blinds you for a moment as you enter the forest."
	.GSTR STR?440,"The blowing snow blinds you for a moment as you walk into the clearing."
	.GSTR STR?416,"The blowing snow blinds you for a moment as you walk through the forest and into a clearing. A small hut lies off the east, and from the smoke from the chimney, it appears as though somebody's home."
	.GSTR STR?383,"The blowing snow blinds you for a moment as you walk through the forest."
	.GSTR STR?517,"The boy is looking rather ashamed at having bumped into you. He clearly recognizes you as a stranger, and starts to look away."
	.GSTR STR?132,"The car pulls up to the end of the road, and you are caught in the headlights's glare. The car's doors fly open, and armed guards aim their rifles at you. Slowly, from the rear of the car, a man emerges - it is your arch-rival, Viper. ""We meet again,"" he says, ""I am delighted that you decided to remain in our friendly country. Would you show our guest to the car?"" He chuckles, then motions to a guard, who throws you into the trunk of the car."
	.GSTR STR?458,"The clearing before you is large and open, and you are concerned about being so exposed. Seeing the hut off to the east, you decide to play it safe by taking a position just to its south, where you can better gauge the situation."
	.GSTR STR?523,"the corner or Brzni and Fremzi"
	.GSTR STR?963,"The crowd noise subsides and the national anthem is begun."
	.GSTR STR?379,"The crumpled body of the fallen guard is lying on the ground. Beneath him lies his machine gun."
	.GSTR STR?555,"The door is locked from the inside."
	.GSTR STR?630,"The door is locked."
	.GSTR STR?333,"The elevator arrives; the operator, a woman, waits for you to enter."
	.GSTR STR?332,"The elevator door closes; presumably the elevator will return to the ground floor."
	.GSTR STR?334,"The elevator door opens down the hall to the north."
	.GSTR STR?788,"The farther away they are, the better."
	.GSTR STR?377,"The guard post itself looks both north and south. To the south, one can look out over the no-man's-land and toward the forest. The machine gun bolted to the floor is a grim reminder of the obstacles you have faced so far. To the north, only a few feet beyond reach and about five feet below you, lies the border fence."
	.GSTR STR?813,"The guards are coming after me!"
	.GSTR STR?169,"The guards burst through the door; a shot is fired - you are hit!"
	.GSTR STR?163,"The guards reach the base of the tower, and fire a few shots. After some muffled discussion, they call out: ""It is of no use. Come out, or we shall be forced to kill you! You have 15 seconds to decide!"""
	.GSTR STR?620,"The ladder ends here; there is no access to the roof."
	.GSTR STR?789,"The less you hang around there, the better."
	.GSTR STR?241,"The man enters the storage area, looks around for a moment, scratches his balding head, and returns whence he came."
	.GSTR STR?274,"The man in the trench coat takes you by the arm and walks you back to your compartment."
	.GSTR STR?515,"The man is old and infirm. He apparently can't see too well, for he is constantly squinting. He also appears to be mumbling to himself."
	.GSTR STR?937,"The man looks at you impatiently. ""Please..."" he implores."
	.GSTR STR?251,"The man returns to the living room, leaving your line of sight."
	.GSTR STR?223,"The man walks from the front of the hut and into the clearing, continuing to the northwest and out of sight."
	.GSTR STR?226,"The man walks out of the hut and heads toward the clearing."
	.GSTR STR?225,"The man walks up to the front of the hut, and fumbles around with the door, though his hands are full of logs."
	.GSTR STR?222,"The man, carrying a large pile of wood in his arms, walks out of the forest and into the clearing."
	.GSTR STR?221,"The man, carrying a pile of wood, walks into the clearing and seeing that his hut is on fire, runs off into the forest to the northeast."
	.GSTR STR?240,"The man, coat in hand, enters the storage area and throws the coat onto the floor. After looking around for a moment, he returns whence he came."
	.GSTR STR?198,"The man, confused about the source of the recent explosion, returns to the comfort of his living room."
	.GSTR STR?224,"The man, seeing that his hut is on fire, runs off into the forest to the northeast."
	.GSTR STR?960,"The mayor announces the ""kickoff"" speaker, William Henry Huttinger, the American ambassador. The crowd roars its approval; you've got only moments before it will be too late to save him!"
	.GSTR STR?314,"The next blow is yours, and the next, but Topaz manages a few good shots of his own. Time, time. Not much time, you think."
	.GSTR STR?804,"The northern posts will work. ATTACH THE PEN TO THE NE (NW) POST"
	.GSTR STR?247,"The owner of the hut returns with a pile of wood in his hands. Luckily, he hasn't seen you yet."
	.GSTR STR?250,"The owner, presumably alerted by something amiss in the living room, has no trouble locating you. In a short time, the border patrol has arrived."
	.GSTR STR?504,"The platform ends here at a tall fence, marking the actual border between Frobnia and Litzenburg."
	.GSTR STR?506,"The platform ends here, and a guard prevents you from going any farther."
	.GSTR STR?803,"The posts are fairly weak, but choose well."
	.GSTR STR?955,"The priest departs, and the mayor announces the ""kickoff"" speaker, William Henry Huttinger, the American ambassador. Amidst the roaring approval of the crowd, Huttinger approaches the rostrum.

It may seem strange for an unaligned country to show such feeling for a former member of the American military, but it was Huttinger who led the Allied forces during the liberation of Litzenburg in 1945, and the people have not forgotten.

How ironic that the Kremlin chose this time, this place for the death of one of Litzenburg's only heroes. Even more ironic is that the irony is almost certainly lost on them."
	.GSTR STR?175,"The pursuing guards are more fortunate."
	.GSTR STR?787,"The quieter you are, the better."
	.GSTR STR?747,"The scout will be gone when the car leaves (you'll hear it)."
	.GSTR STR?563,"The shop is closed and locked, presumably due to the holiday. With all of the security in the area, it is unlikely you could force your way in without being detected."
	.GSTR STR?296,"The sniper squeezes the trigger twice, and the sound echoes through the room. Your agents have chosen well - Huttinger is dead, and you have failed in your mission."
	.GSTR STR?347,"The sniper, who has been watching you carefully, spins around and fires at you, killing you instantly."
	.GSTR STR?760,"The status line will show you the current positions of the lights."
	.GSTR STR?651,"The strain is showing!"
	.GSTR STR?121,"The three men approach the door of the hut, then knock loudly. The third man looks familiar, though in the darkness, it's hard to be certain."
	.GSTR STR?952,"The town's fifteenth century clock strikes the hour, indicating that the ceremonies are shortly to commence."
	.GSTR STR?957,"The town's fifteenth century clock strikes the hour."
	.GSTR STR?607,"The wall climbs perhaps twenty feet; there's no way you could get over it."
	.GSTR STR?874,"The weakness has taken a toll on your physical abilities; movement is slower and less sure."
	.GSTR STR?513,"The young girl is holding the hand of her mother, tugging gently. She seems distracted, as young girls will be."
	.GSTR STR?811,"Then try KNOCKing on the DOOR."
	.GSTR STR?694,"Then, GIVE THE COLOR ROLL TO THE CONTACT. Alternatively, you can DROP THE COLOR FILM; this latter method is less obvious, in case you are followed. Depending on how much suspicion you have raised, you may be able to do either, both, or none of these two things."
	.GSTR STR?866,"Then, HIT TOPAZ, and he'll never know what happened."
	.GSTR STR?713,"Then, TIE THE PIECE OF CLOTHING AROUND LEFT ARM."
	.GSTR STR?806,"Then, you should get INTO the tower."
	.GSTR STR?677,"There are a number of things you may have done to make the situation worse. See the previous two questions. Also, if the guards found anything peculiar in their search of your possessions, that would increase their suspicions."
	.GSTR STR?271,"There are two sharp raps on the lavatory door, and a man with a thick accent speaks. ""Please forgive the intrusion, but I must have a word with you, outside, in your compartment."""
	.GSTR STR?272,"There are two sharp raps on your door, and a man wearing a trench coat enters."
	.GSTR STR?939,"There is a knock on the door. ""If you wouldn't mind, I really must speak to you."""
	.GSTR STR?624,"There is no door to the east."
	.GSTR STR?625,"There is no door to the west."
	.GSTR STR?832,"There is only one vacant apartment with the window open. Guess who's in it?"
	.GSTR STR?734,"There's a good spot where you can observe the car."
	.GSTR STR?718,"There's a very nice parka inside."
	.GSTR STR?656,"There's another few seconds down the drain."
	.GSTR STR?536,"There's just a wall there, papered with various uninteresting posters."
	.GSTR STR?531,"There's no way into the apartment building from here."
	.GSTR STR?445,"There's no way into the hut from here."
	.GSTR STR?540,"There's no way into the office building from here."
	.GSTR STR?791,"There's no way."
	.GSTR STR?361,"they"
	.GSTR STR?161,"They are close enough to take a few quick shots, one of which hits you in the leg, causing you to topple off the brace and onto the ground. You survive, but it's little consolation."
	.GSTR STR?737,"They come to warn the man in the hut that you are an escaped lunatic."
	.GSTR STR?852,"Think about it..."
	.GSTR STR?328,"third"
	.GSTR STR?817,"This hinges on where you've placed the explosive, how you've set the timer, and where you are when it goes off."
	.GSTR STR?553,"This is as far as you can go on Fremzi Stret, before running into the police cordons. A metal door, closed and locked, lies to the east. On it, a sign reads ""Riznik's Antiques - Deliveries Only"""
	.GSTR STR?585,"This is the corner of Brzni Street, running east and west, and Ostnitz Street, running north and south along the western edge of Ostnitz Square. Though congested, your way is clear in all directions, except to the north, where police barricades block the street."
	.GSTR STR?597,"This is the lobby of the apartment building; there is little of note here, except for the elevator, whose door stands open to the north. In front of you, a directory lists the occupants of the building. You can exit the building to the east."
	.GSTR STR?511,"This smoke-filled compartment is filled with a dozen or more men, playing some sort of card game. They regard you with hostility, and force you back into the corridor."
	.GSTR STR?928,"three compartments"
	.GSTR STR?512,"Three women are here, busily engaging in what probably amounts to gossip. They stop abruptly as you enter, and stare at you stonily. After a moment, you mumble some apologetic word and return to the corridor."
	.GSTR STR?923,"Through the window, a lone guard comes into view, awalking slowly toward the front of the hut. Fortunately, he isn't looking in your direction."
	.GSTR STR?921,"Through the window, you see a lone guard checking out the rear of the hut. Fortunately, he isn't looking inside."
	.GSTR STR?239,"Through the window, you watch as the man walks out of sight toward the rear of the hut."
	.GSTR STR?248,"Through the window, you watch the man return to the living room, throw some logs into the wood stove, and return to his easy chair."
	.GSTR STR?200,"time"
	.GSTR STR?763,"To cross successfully, you must be in good physical condition."
	.GSTR STR?753,"To use the explosive, REMOVE the CAP, PUSH the BUTTON once for every minute you want the fuse to run, and REPLACE the CAP."
	.GSTR STR?112,"Too late! The guards, alerted by the guard dogs who have pursued you across no-man's-land, approach with weapons drawn."
	.GSTR STR?855,"Topaz always catches me. Why?"
	.GSTR STR?309,"Topaz has spotted you! He's started to move away from his table and rushes in your direction.[RWD_ID: bad:1614, VAL: 1]"
	.GSTR STR?643,"Topaz is lying unconscious on the ground."
	.GSTR STR?853,"Topaz will follow you anywhere, even to the sniper's room."
	.GSTR STR?774,"Try CUTting the LINKS WITH THE BOLT CUTTERS."
	.GSTR STR?755,"Try placing it in different places to see what happens; remember it's magnetic so you can PUT it ON metallic objects."
	.GSTR STR?689,"Try rewinding the roll that's in there, and loading the camera with the exposed roll. That will divert suspicion."
	.GSTR STR?653,"Try to think more rationally!"
	.GSTR STR?56,"Trying to break "
	.GSTR STR?66,"Turning "
	.GSTR STR?927,"two compartments"
	.GSTR STR?509,"Two newlyweds here are enjoying their privacy, and not enjoying your presence. The woman, who appears to be the man of the house, escorts you out of the door."
	.GSTR STR?236,"Unfortunately, somebody's home, though he isn't very hospitable looking with his revolver in hand."
	.GSTR STR?233,"Unfortunately, someone was indeed home, and carrying a weapon at that. He motions you to the door, and you follow him as he telephones for the border police."
	.GSTR STR?786,"Unless you're in front of the middle tower, you are ALWAYS in view of one of the guards."
	.GSTR STR?991,"Urg"
	.GSTR STR?601,"vendor's cart"
	.GSTR STR?65,"verbs:1020"
	.GSTR STR?68,"verbs:1117"
	.GSTR STR?69,"verbs:1202"
	.GSTR STR?71,"verbs:1272"
	.GSTR STR?72,"verbs:1438"
	.GSTR STR?73,"verbs:1662"
	.GSTR STR?74,"verbs:1668"
	.GSTR STR?75,"verbs:1678"
	.GSTR STR?76,"verbs:1684"
	.GSTR STR?77,"verbs:1891"
	.GSTR STR?78,"verbs:1892(a)"
	.GSTR STR?79,"verbs:1892(b)"
	.GSTR STR?80,"verbs:1895"
	.GSTR STR?82,"verbs:1967"
	.GSTR STR?83,"verbs:1996(a)"
	.GSTR STR?84,"verbs:1996(b)"
	.GSTR STR?85,"verbs:1996(c)"
	.GSTR STR?39,"verbs:287"
	.GSTR STR?41,"verbs:312(a)"
	.GSTR STR?42,"verbs:312(b)"
	.GSTR STR?44,"verbs:433(a)"
	.GSTR STR?45,"verbs:433(b)"
	.GSTR STR?46,"verbs:472"
	.GSTR STR?47,"verbs:486(a)"
	.GSTR STR?48,"verbs:486(b)"
	.GSTR STR?50,"verbs:656"
	.GSTR STR?51,"verbs:659(a)"
	.GSTR STR?52,"verbs:659(b)"
	.GSTR STR?53,"verbs:659(c)"
	.GSTR STR?54,"verbs:663"
	.GSTR STR?57,"verbs:820(a)"
	.GSTR STR?58,"verbs:820(b)"
	.GSTR STR?59,"verbs:820(c)"
	.GSTR STR?63,"verbs:905"
	.GSTR STR?986,"Veznich"
	.GSTR STR?948,"Vinchim dorn!"
	.GSTR STR?910,"W"
	.GSTR STR?360,"was"
	.GSTR STR?664,"Wasn't he holding his left arm? Mightn't it have been wounded?"
	.GSTR STR?741,"Well, it works better if nobody's inside."
	.GSTR STR?809,"Well, that doesn't mean that you should be just standing there with a stupid look on your face..."
	.GSTR STR?814,"Well, what did you expect?"
	.GSTR STR?894,"west"
	.GSTR STR?895,"west-northwest"
	.GSTR STR?893,"west-southwest"
	.GSTR STR?647,"What a concept!"
	.GSTR STR?731,"What about the automobile I hear?"
	.GSTR STR?785,"When they are facing away from you, you have some freedom of action."
	.GSTR STR?693,"When your contact appears, you must SAY ""It is my fault"" in Frobnian. Check your phrase book for the translation."
	.GSTR STR?824,"Where is the sniper hiding?"
	.GSTR STR?738,"Who else would be walking around, wounded and cold, in the middle of nowhere?"
	.GSTR STR?690,"Who is my contact?"
	.GSTR STR?675,"Why am I followed at the station?"
	.GSTR STR?668,"Why am I searched so thoroughly?"
	.GSTR STR?843,"Why does the sniper kill me?"
	.GSTR STR?661,"Why doesn't he believe my answer?"
	.GSTR STR?994,"Winip"
	.GSTR STR?86,"with"
	.GSTR STR?275,"Without warning, the door is knocked open by one of the uniformed guards. The man in the trench coat then takes you by the arm and escorts you back to your compartment."
	.GSTR STR?911,"WNW"
	.GSTR STR?909,"WSW"
	.GSTR STR?627,"You are about one-third of the way betwween the southern and northern ends of the hallway. Doors are on both sides of you, east and west."
	.GSTR STR?671,"You are American, therefore somewhat suspicious."
	.GSTR STR?570,"You are amidst a huge crowd which has poured into the square to better see and hear the afternoon's events. From here, you can move in any direction, albeit slowly, except toward the barricades to the east. Behind the barricades, a raised dais has been constructed, and the dignitaries are already in place. A tall column here commemorates those who died in the Litzenburger war for independence."
	.GSTR STR?613,"You are at the bottom of the fire-escape ladder, about ten feet above the ground. The ladder rises to each of the upper four levels and it's just a short drop to the ground. A toppled trash can lies in the alley beneath your feet."
	.GSTR STR?524,"You are at the corner of Brzni, running east-west, and Besnap, running north and south. The town square can be reached east along Brzni."
	.GSTR STR?636,"You are at the northern end of the hallway; closed doors lie on either side of you, east and west. In front of you, to the north, is an elevator, beside which is a white call button."
	.GSTR STR?528,"You are behind the apartment building; there is no access to the inside from this street. Fremzi continues north and south here; a vacant lot lies to the west."
	.GSTR STR?538,"You are behind the office building; there is no access to the inside from this street. Fremzi continues north and south here; a vacant lot lies to the west."
	.GSTR STR?875,"You are definitely weaker now, and it is starting to affect you significantly."
	.GSTR STR?632,"You are halfway between the northern and southern ends of the hallway; closed doors lie on either side of you."
	.GSTR STR?949,"You are in my way!"
	.GSTR STR?209,"You are jolted by the 240 volts which courses through your body. Just before passing out, you manage to pull yourself away from the electrified fence, saving you from a certain death. You regain consciousness some time later, but not before the border patrol arrives."
	.GSTR STR?530,"You are now moving down Fremzi Street, just between Brzni Street to the north and Besnap Street to the south. The apartment building and office building lie to your northeast and southeast respectively, but there is no access here to either. A vacant lot lies to the west."
	.GSTR STR?562,"You are on Besnap Street in front of a closed bookstore. The street continues east and west here; the town square lies to the north."
	.GSTR STR?566,"You are on Besnap Street in front of a closed tailor's shop. Police barricades block the street to the east, but you can continue west easily enough. The square lies to the north."
	.GSTR STR?579,"You are on Brzni Street, in front of a closed chemist's shop. Police barricades block the street to the east, though it is easy, but slow, going to the west. The town square lies to the south."
	.GSTR STR?591,"You are on Brzni Street, in front of a closed hardware store. The street runs east-west here."
	.GSTR STR?582,"You are on Brzni Street, in front of a vacant storefront. The street continues east and west here; the town square lies to the south."
	.GSTR STR?533,"You are on Fremzi Stret, halfway between Brzni to the north and Besnap to the south. A vacant lot sits to the west; two buildings rise to the northeast and southeast, but access to the inside is on Ostnitz Street."
	.GSTR STR?872,"You are on your last legs now, and have trouble moving around. Even the most simple of actions is complicated, and you realize that your mission will soon end in failure. If you're lucky, maybe they'll find you before you die here."
	.GSTR STR?742,"You can get in when the occupant is talking to the men from the car. [See the hint about the car if this is meaningless...]"
	.GSTR STR?10,"You can hear an explosion in the distance."
	.GSTR STR?118,"You can hear the sound of an automobile engine being started, though it's hard to tell from which direction the sound is coming."
	.GSTR STR?922,"You can see a single guard slowly walking around the back side of the hut to the south side of the hut."
	.GSTR STR?122,"You can see, through the window in the back door, the occupant of the hut walk outside."
	.GSTR STR?858,"You can TOPPLE THE VENDOR'S CART and make an unholy mess; that will hold Topaz for a little while. After that, it's up to you."
	.GSTR STR?834,"You can try using the elevator in the apartment lobby."
	.GSTR STR?534,"You can't enter the apartment building from here."
	.GSTR STR?535,"You can't enter the office building from here."
	.GSTR STR?2,"You can't go that way.
"
	.GSTR STR?815,"You can't leave; you can't fight; or can you?"
	.GSTR STR?475,"You can't move any farther in that direction."
	.GSTR STR?792,"You can't."
	.GSTR STR?16,"You consider telling Topaz who and what you are, but it is too dangerous; your own men are probably swarming the area, and any contact with Topaz would blow your cover wide open."
	.GSTR STR?600,"You consider trying to force your way into the building, but decide against it, realizing that anything that calls attention to yourself will jeopardize either your plan or your cover."
	.GSTR STR?559,"You continue along Besnap Street until you come to the front of a closed bookstore. The street continues east; the town square is just to the north."
	.GSTR STR?568,"You continue along Besnap Street until you come to the front of a closed bookstore. The street continues west; the town square is just to the north."
	.GSTR STR?564,"You continue along Besnap Street until you come to the front of a closed tailor's shop. Police barricades block the street to the east; the town square is just to the north."
	.GSTR STR?544,"You continue along Besnap Street until you come to the front of an antique shop. The sign outside says:

   Riznik's Antiques
 Rare Books and Curios

The gathering crowd which surrounds you continues its relentless push toward Ostnitz Square to the east."
	.GSTR STR?526,"You continue along Brzni Street, arriving in front of a closed hardware store. The street continues east."
	.GSTR STR?588,"You continue along Brzni Street, arriving in front of a closed hardware store. The street continues west."
	.GSTR STR?583,"You continue along Brzni until you reach the front of a closed chemist's shop. Barricades block the way to the east; the town square lies to the south."
	.GSTR STR?473,"You continue along the road as it heads south toward the mouth of a tunnel. The road is joined here by railroad tracks which also lead into the tunnel, but bend to the northwest alongside a steep ridge."
	.GSTR STR?497,"You continue along the roadway for about a hundred yards to a point where it bends to the southwest."
	.GSTR STR?465,"You continue along the roadway for about a hundred yards, to a point where it bends to the northeast."
	.GSTR STR?483,"You continue along the roadway for about a hundred yards, to a point where it curves to the left, heading south. A small spur of the road leads north."
	.GSTR STR?470,"You continue along the roadway for about a hundred yards; the road continues along here to the southwest."
	.GSTR STR?467,"You continue along the roadway for about a hundred yards."
	.GSTR STR?539,"You continue along the street to the corner of Besnap and Fremzi; crowds of people are now heading east through this intersection on their way to the square."
	.GSTR STR?547,"You continue along the street, jostled every few moments by the surging crowd, and stop at the intersection of Besnap Street (going east-west) and Ostnitz Street (going north-south), at the southwest corner of Ostnitz Square. The Square itself is packed with people awaiting the start of the Constitution Day festivities."
	.GSTR STR?414,"You continue along the tracks for about a hundred yards, and come to a place where the tracks are met by a roadway, heading off to the northeast. Both the tracks and the roadway enter a tunnel to the south."
	.GSTR STR?405,"You continue along the tracks for about a hundred yards, reaching a spot at which the tracks bend off to the southeast."
	.GSTR STR?402,"You continue along the tracks for about a hundred yards."
	.GSTR STR?434,"You continue along until you enter a clearing; to the east, before you, lies a burning hut, sending plumes of black smoke and orange flame into the sky."
	.GSTR STR?587,"You continue down Brzni Street, arriving in front of a vacant storefront. The street continues east."
	.GSTR STR?580,"You continue down Brzni Street, arriving in front of a vacant storefront. The street continues west."
	.GSTR STR?592,"You continue down Brzni Street, coming to the intersection with Fremzi Street, which runs south alongside a vacant lot to the west."
	.GSTR STR?529,"You continue down Fremzi Street, coming to the intersection with Brzni Street, which runs east toward the square."
	.GSTR STR?633,"You continue down the hall to the last set of doorways, one to the east and one to the west. Before you, to the north is an elevator with a white call button."
	.GSTR STR?623,"You continue down the hall to the next set of doorways, one to the east and one to the west. You're now about a third of the way toward the end of the hall."
	.GSTR STR?628,"You continue down the hall to the next set of doorways, one to the east and one to the west. You're now about halfway down the hall."
	.GSTR STR?634,"You continue down the hall to the next set of doorways, one to the east and one to the west. You're now about two-thirds of the way toward the end of the hall."
	.GSTR STR?459,"You continue down the road and come to the junction of a larger road running from south to east."
	.GSTR STR?558,"You continue through the crowds as you head down Ostnitz Street, stopping finally in front of a sidewalk cafe. Waiters here in traditional red robes cater to the mixed crowd of tourists and locals eager to watch the festivities while sipping on a drink in the shade. Behind the cafe to the west is the entrance to the building itself, which appears to be used as office space. A pair of policemen guard the door - added security for the occasion."
	.GSTR STR?479,"You continue through the forest and come to the north side of a small wooden hut. Smoke rises in black swirls from the chimney, indicating that it's likely that somebody's home."
	.GSTR STR?394,"You continue through the forest for a hundred yards, and then stop. Snowflakes fall softly around you - nearby, a small animal scurries through the brush."
	.GSTR STR?424,"You continue through the forest, coming finally to the edge of a putrid swamp, which winds its way off to the northeast."
	.GSTR STR?382,"You continue through the forest, until you come to the edge of a wide clearing to the north - this is the border zone. From atop three guard towers standing in a line from east to west, searchlights play across the zone, brightly illuminating everything in their path. On either side of the towers are tall fences, running parallel to the border, making a direct assault all but impossible."
	.GSTR STR?388,"You continue through the forest, until you come to the edge of a wide clearing to the north - this is the border zone. From atop three guard towers standing in a line from east to west, searchlights play across the zone, brightly illuminating everything in their path. On either side of the towers are tall fences, running parallel to the border, making a direct assault all but impossible. Directly across the border zone is the border crossing station."
	.GSTR STR?629,"You continue to the end of hall, where a window leads to a fire-escape ladder connecting the various floors of the building."
	.GSTR STR?441,"You continue until reaching the front of the blazing hut. The heat is so extreme that you can't get within twenty feet of it."
	.GSTR STR?446,"You continue until reaching the north side of a blazing hut. With the extreme heat here, you can't get close at all."
	.GSTR STR?431,"You continue until you come to the start of a roadway leading south."
	.GSTR STR?456,"You continue until you reach the back side of a blazing hut. Engulfed as it is in flames, you cannot possibly get closer."
	.GSTR STR?770,"You could use something insulating on your hands."
	.GSTR STR?364,"You crawl along the ground until you reach a point directly south of the next guard tower."
	.GSTR STR?481,"You cross a road, leave the forest, and come to the edge of a dank area at the edge of a swamp running from northeast to southwest. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?421,"You cross a roadway and come to the edge of a putrid swamp, which runs off to the northeast."
	.GSTR STR?323,"You dodge not only the vendor's cart, but its strewn contents, and finally manage to get through to the other side."
	.GSTR STR?203,"You don't get anywhere so far as damaging the post is concerned; you do, however, rattle it enough to alert the guard inside, who within five seconds is upon you, gun drawn."
	.GSTR STR?756,"You don't really need this until you've gotten as far as the border fences."
	.GSTR STR?614,"You drop the last four feet to the ground."
	.GSTR STR?381,"You emerge from the forest into an open area through which runs a railroad track oriented north and south. Beyond the tracks, the ground rises steeply."
	.GSTR STR?422,"You emerge from the forest into an open area through which runs a railroad track running to the northwest and a roadway running to the northeast. Both lead south into a tunnel."
	.GSTR STR?492,"You emerge from the swamp and come to a roadway running from north to south."
	.GSTR STR?482,"You emerge from the thick forest and come to a roadway running from east to west."
	.GSTR STR?419,"You emerge from the thick forest and come to a roadway running from north to south."
	.GSTR STR?420,"You emerge from the thick forest and come to a roadway running from north to southwest."
	.GSTR STR?478,"You emerge from the thick forest and come to a roadway running from northeast to south."
	.GSTR STR?418,"You emerge from the thick forest and come to a roadway running from south to east, with a narrow spur leading north."
	.GSTR STR?427,"You enter the forest, breaking branches as you go, and finally stop after walking about a hundred yards."
	.GSTR STR?437,"You enter the forest, breaking branches as you go, and finally stop as you come into a clearing, to the east of which is a small hut."
	.GSTR STR?453,"You enter the forest, but soon emerge at a roadway running from east to west."
	.GSTR STR?608,"You head back toward Ostnitz street, stopping just behind the vendor's cart."
	.GSTR STR?6,"You hear a cry of ""Halt,"" then spin around to see a large man aiming a pistol at you. You start to run, but you're shot in the leg. Unable to move, you await the arrival of the border patrol."
	.GSTR STR?920,"You hear footsteps coming slowly in your direction from the back side of the hut."
	.GSTR STR?918,"You hear footsteps coming slowly in your direction from the north side of the hut."
	.GSTR STR?214,"You hear heavy footsteps headed your way; looking through the window, a man comes into sight from the southeast."
	.GSTR STR?119,"You hear knocking from the front of the house."
	.GSTR STR?157,"You knock on the door. A moment later, the door opens, and you are facing a guard whose automatic weapon is aimed at your head."
	.GSTR STR?551,"You leave quietly through the side door, which closes behind you. You're now on a north-south street just around the corner from the store's entrance. Just south of you stands a guarded police barricade."
	.GSTR STR?605,"You leave the alley at Ostnitz Street; the street vendor is still here, though his stock is somewhat depleted. The square is before you, still practically bursting with humanity. The street continues to the north and south."
	.GSTR STR?598,"You leave the apartment building, and return to Ostnitz Street, where the crowd is packed in even tighter than before, especially east, in the direction of the town square."
	.GSTR STR?477,"You leave the edge of the swamp and enter the forest; it is quite a relief for your nose. You take some deep breaths, continue for a hundred yards, and stop."
	.GSTR STR?408,"You leave the forest and come to some railroad tracks, running more-or-less north and south. Behind the tracks, the ground rises steeply."
	.GSTR STR?410,"You leave the forest and come to some railroad tracks, running more-or-less north and south. Behind the tracks, the rises steeply."
	.GSTR STR?413,"You leave the forest and come to some railroad tracks, running northwest to southeast. Behind the tracks, to the west and south, the ground rises steeply."
	.GSTR STR?494,"You leave the forest, crossing a roadway, and come to the edge of a dank area at the edge of a swamp which continues to the south. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?485,"You leave the road, walk through the forest, and then come upon the same road again, now heading north-south."
	.GSTR STR?484,"You leave the roadway and come to the edge of a dank area at the edge of a swamp running from northeast to southwest. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?495,"You leave the roadway and come to the edge of a dank area at the edge of a swamp which continues to the south. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?466,"You leave the roadway and come to the edge of a dank area at the edge of a swamp which runs from northeast to south. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?496,"You leave the roadway and come to the edge of a dank area at the edge of a swamp which runs from the north to the southwest. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?474,"You leave the roadway and come to the edge of a dank area at the edge of a swamp, which continues northeast. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters."
	.GSTR STR?469,"You leave the roadway and come to the edge of a dank area at the edge of a swamp. Putrid sulphurous vapors fill your lungs as you step to the edge of the noisome waters. The swamp's edge continues to the north and southwest."
	.GSTR STR?463,"You leave the roadway, and reenter the forest. After a few dozen yards, you come to a roadway running east and west."
	.GSTR STR?549,"You leave the shop, and reenter the gathering crowd which surrounds you in its relentless push toward Ostnitz Square to the east."
	.GSTR STR?400,"You leave the side of the railroad tracks and head into the forest, until you come to the edge of a wide clearing to the north - this is the border zone. From atop three guard towers standing in a line from east to west, searchlights play across the zone, brightly illuminating everything in their path. On either side of the towers are tall fences, running parallel to the border, making a direct assault all but impossible."
	.GSTR STR?401,"You leave the side of the railroad tracks and head into the forest. The darkness is deeper here, as less moonlight reaches the forest floor. The snow crunches under your feet, and you pause after moving a hundred or so yards into the forest."
	.GSTR STR?487,"You leave the side of the roadway and enter the forest, proceeding a hundred yards before you come to the south side of a small hut. The smoke from the chimney indicates that perhaps someone is home."
	.GSTR STR?464,"You leave the side of the roadway and enter the forest, proceeding a hundred yards before you stop."
	.GSTR STR?462,"You leave the side of the roadway and reenter the forest."
	.GSTR STR?461,"You leave the side of the roadway and reenter the forest. A cold gust of wind chills you to the bone."
	.GSTR STR?460,"You leave the side of the roadway, bear off slightly to the north to avoid a thicket, and reenter the forest. A cold gust of wind chills you to the bone."
	.GSTR STR?490,"You leave the side of the swamp and walk onto the nearby east-west roadway. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?476,"You leave the side of the swamp and walk onto the nearby roadway, running from the north to the southwest. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?488,"You leave the side of the swamp and walk onto the nearby roadway, which runs from north to south. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?501,"You leave the side of the swamp and walk onto the nearby roadway, which runs from north to southwest here. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?502,"You leave the side of the swamp and walk onto the nearby roadway, which runs from south to northeast. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?489,"You leave the side of the swamp and walk onto the nearby roadway, which runs from the north to the southwest. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once."
	.GSTR STR?491,"You leave the side of the swamp and walk onto the nearby roadway. The air is already fresher here, and you cannot help but cough a few times, as if to purge the foul air all at once. The road leads east and south, but a narrow spur heads to the north."
	.GSTR STR?576,"You leave the square, arriving at Besnap Street in front of a closed bookstore. The street continues east and west."
	.GSTR STR?577,"You leave the square, arriving at Besnap Street in front of a closed tailor's shop. Police barricades block the street to the east."
	.GSTR STR?571,"You leave the square, arriving at Brzni Street in front of a chemist's shop. The street is blocked by barricades to the east, but it does continue to the west."
	.GSTR STR?572,"You leave the square, arriving at Brzni Street in front of a vacant storefront. The street continues east and west."
	.GSTR STR?317,"You look behind you and spot Topaz, down on the ground, having been knocked over in the near-melee at the vendor's cart. It'll be a little while before he catches up to you."
	.GSTR STR?318,"You look down; Topaz is on the ground below you, moving the trash can into position under the ladder."
	.GSTR STR?406,"You move deeper into the forest, until you reach..."
	.GSTR STR?543,"You move down Fremzi Street, stopping just short of a police barricade. Some uniformed police watch you casually; these are probably crowd control officers, restricting access to the site of the festivities. A closed metal door lies to the east."
	.GSTR STR?602,"You move down Ostnitz Street until you come to the entrance to an apartment building. When you have seen this building before, it has been protected by doormen; today, they have been replaced by police. Something is definitely up here - even an occasion such as this would not normally have so much in the way of security. You wonder if perhaps the plot has been uncovered."
	.GSTR STR?586,"You move down Ostnitz Street until you come to the entrance to an apartment building. When you have seen this building before, it has been protected by doormen; today, they have been replaced by police. Something is definitely up here - even an occasion such as this would not normally require so much extra security. Your mind races - could the plot have been uncovered?"
	.GSTR STR?575,"You move through the crowd and finally leave the Square at its southwest corner, at the intersection of Besnap Street (going east-west) and Ostnitz Street (going north-south)."
	.GSTR STR?567,"You move toward the barricade, then think twice as you see the line of policemen blocking your way."
	.GSTR STR?688,"You must be clever to avoid the guards destroying your film during the search."
	.GSTR STR?958,"You notice that the crowd has become quiet. After a moment, the national anthem begins to play."
	.GSTR STR?97,"You pass out from loss of blood."
	.GSTR STR?573,"You press through the crowd to the corner of Ostnitz and Brzni Streets. A police barricade to the north effectively closes off Ostnitz Street in that direction, but movement in other directions is simple enough, if slow due to the crowd congestion."
	.GSTR STR?18,"You press through the crowd until you reach Ostnitz Street at a point where a street vendor is busily cleaning up his overturned cart. Soda cans and pretzels lie everywhere, making the congestion even worse than it was before. Behind the cart, to the west, is a blind alley sandwiched between the apartment building to your north and the office building to your south. It might take a while to get there, though, with all the mess in the way."
	.GSTR STR?574,"You press through the crowd until you reach Ostnitz Street at a point where a street vendor is busily peddling his wares - soda, pretzels, and hot dogs. His cart is practically overflowing with food, but it's a safe bet that it will all be gone before the afternoon is over. Behind the cart, to the west, is a blind alley sandwiched between the apartment building to your north and the office building to your south."
	.GSTR STR?616,"You pull yourself through the window, and find yourself staring at a long hallway leading north."
	.GSTR STR?560,"You push your way through the crowd, reaching a spot near the middle of the square where a graceful column stands, dedicated to the Litzenburgers who died in the War of Independence which is celebrated here today. Surrounding the square on all sides are stately buildings dating from the 18th century, most of which now have storefronts on ground level.

Stretching from northeast through southeast, a series of barricades has been erected to separate the crowd from the dignitaries attending the ceremonies. Hundreds of uniformed police guard the barricades, and scores of plainclothes police are milling around nearby, heads cocked toward their earphones to enable them to hear over the ever louder crowd. The dais is raised about ten feet, and the dignitaries are just starting to take their positions."
	.GSTR STR?589,"You push your way through the crowd, reaching a spot near the middle of the square where a graceful column stands, dedicated to those who died in the War of Independence. Atop the column, a fifteenth century clock tolls the hours. Surrounding the square on all sides are stately buildings dating from the time of the War, most of which now have storefronts at ground level.

Stretching from northeast through southeast, a series of barricades has been erected to separate the crowd from the dignitaries attending the ceremonies. Hundreds of uniformed police guard the barricades, and scores of plainclothes police are milling around nearby, heads cocked toward their earphones to enable them to hear over the ever louder crowd. The dais is raised about ten feet, and the dignitaries are just starting to take their positions."
	.GSTR STR?154,"You rap on the door again. This time, the guard has figured out your game and is prepared. He swings around, and smashes his automatic weapon into your head, knocking you to the ground below. You aren't killed, but it sure feels like it, and a moment later, you are surrounded by unsympathetic guards."
	.GSTR STR?450,"You reach the south side of a hut, now completely ablaze. The heat from the flames makes it impossible to go any closer."
	.GSTR STR?448,"You reenter the forest and soon come to a roadway running from east to west."
	.GSTR STR?12,"You reply that indeed a wounded man did wander into the compartment, apparently looking for someone. A moment later, he was gone. You are asked whether he gave you anything, a piece of paper perhaps, but you shake your head in the negative."
	.GSTR STR?397,"You scramble up a bit, but slide back down. It's just too steep."
	.GSTR STR?765,"You should also be wearing proper shoes."
	.GSTR STR?761,"You should plan to head NORTH when the three lights are all aimed away from you."
	.GSTR STR?542,"You stand at the corner of Besnap and Fremzi, away from the throngs that have gathered in Ostnitz Square to the east. Fremzi can be followed to the north and, for a short ways, to the south, while Besnap is cordoned off to the west. A large vacant lot lies to the northwest."
	.GSTR STR?143,"You start across to the guard tower, but you are spotted by one of the guards, who was facing in your direction. He calls out, and you turn to find a place to hide. A shot rings out, and you are hit! When you come to, you are surrounded by guards."
	.GSTR STR?498,"You start along the road, until you see a roadblock come into sight; you duck back into the forest. It would never work to go that way."
	.GSTR STR?503,"You start onto the roadway, and find yourself facing a roadblock. Realizing that you'd be caught in a moment continuing that way, you return to the edge of the swamp."
	.GSTR STR?449,"You stumble through a three-foot snowdrift, but get back on your feet quickly and move to a point in the forest at which a small road leads south."
	.GSTR STR?433,"You stumble through a three-foot snowdrift, but get back on your feet quickly and proceed into the forest, stopping as you come upon a small wooden shed."
	.GSTR STR?393,"You stumble through a three-foot snowdrift, but get back on your feet quickly and proceed through the forest."
	.GSTR STR?436,"You stumble through a three-foot snowdrift, but get back on your feet quickly and proceed to a point at which a road leading south through the forest begins."
	.GSTR STR?435,"You stumble through a three-foot snowdrift, but get back on your feet quickly and proceed to the north side of the house."
	.GSTR STR?312,"You try, but can hear nothing at all coming from the hallway. Topaz must be close, but how close you can't determine."
	.GSTR STR?500,"You walk along the road for a hundred or so yards, snow swirling in your face, until you come to a point where the road bends to the northeast."
	.GSTR STR?499,"You walk along the road for a hundred or so yards, snow swirling in your face. From here, the road continues to the west."
	.GSTR STR?471,"You walk along the road for a hundred or so yards, snow swirling in your face. The road bends to the east here, but a narrow spur continues north."
	.GSTR STR?443,"You walk around the house and into the clearing."
	.GSTR STR?442,"You walk around the house to the back; a door here leads into the hut."
	.GSTR STR?447,"You walk around the house to the back; the door is closed."
	.GSTR STR?444,"You walk around to the front of the house."
	.GSTR STR?451,"You walk around to the north side of the house."
	.GSTR STR?438,"You walk around to the north side of the hut."
	.GSTR STR?452,"You walk around to the south side of the house."
	.GSTR STR?429,"You walk around to the south side of the hut."
	.GSTR STR?426,"You walk for a short while and come to a large clearing, to the east of which lies a small hut. Concerned about the possibility of being seen, you head toward a spot on the north side of the hut, where you can check the situation out."
	.GSTR STR?595,"You walk nonchalantly past the guards, nodding at them politely, and find yourself in the lobby. An elevator lies to the north; its door is open and the operator, an older woman, is standing inside. A directory, listing the building's occupants, is standing here as well. You can leave the building to the east."
	.GSTR STR?468,"You walk onto the spur leading north, and continue until the road ends just south of a clearing."
	.GSTR STR?148,"You walk out into the open, as five guards with weapons raised stand ready. Slowly, you descend the stairs and are taken into custody."
	.GSTR STR?390,"You walk through the forest, breaking branches as you go, and finally stop after walking about a hundred yards."
	.GSTR STR?81,"You walk to the border station, waving your bloody shirt like a white flag, until the guards come and take you away."
	.GSTR STR?300,"You watch as a man walks out of the antique shop. A moment later, still in motion, he takes a walkie-talkie out of his pocket and starts speaking into it. Within seconds, he is lost in the crowd. You try to think, but you're certain you've never seen him before."
	.GSTR STR?98,"You watch as the automobile speeds into the tunnel and disappears."
	.GSTR STR?99,"You watch as the car makes a three-point turn, then heads back down the road to the south."
	.GSTR STR?924,"You watch as the lone guard returns to the group. He appears relieved that he has nothing to report."
	.GSTR STR?246,"You watch as the man enters the hut, drops the pile of wood on the floor near the wood stove, and heads toward the rear of the hut."
	.GSTR STR?953,"You watch as the mayor of Ostnitz comes to the podium at the front of the dais. He motions for the crowd to be silent for the playing of the national anthem."
	.GSTR STR?245,"You watch the man, carrying a large pile of wood, reenter his hut."
	.GSTR STR?238,"You watch through the window as the man walks out of sight toward the back of the hut."
	.GSTR STR?525,"You would be getting rather far from the action, and you've no time to spare getting sidetracked."
	.GSTR STR?552,"You would only be detained by the police.[ID: bad:527]"
	.GSTR STR?493,"You'd be caught in a moment.[ID: border:4732]"
	.GSTR STR?403,"You'd do as well to surrender.[ID: border:2071]"
	.GSTR STR?404,"You'd do as well to surrender.[ID: border:2073]"
	.GSTR STR?412,"You'd never make it up the cliff on the other side of the tracks."
	.GSTR STR?772,"You'll also need the BOLT CUTTERS, also found in the woodshed."
	.GSTR STR?828,"You'll have to find out yourself on which floor of the apartment building the sniper is hiding, but at least your contact had the password."
	.GSTR STR?717,"You'll have to get into the hut."
	.GSTR STR?9,"You'll have to get there first."
	.GSTR STR?773,"You'll have to LOOK AT THE TOOLS to find the gloves and the bolt cutters."
	.GSTR STR?679,"You'll have to make sure the guards don't find it."
	.GSTR STR?840,"You'll have to meet with your contact, the antique dealer. See the previous question."
	.GSTR STR?816,"You'll have to somehow blow up the tower and yet stay in relative safety (no mean trick)."
	.GSTR STR?622,"You're at the end of a north-south hallway. There are no doors right here; they are farther down the hall. The window leading to the fire-escape is open."
	.GSTR STR?106,"You're feeling a lot warmer now."
	.GSTR STR?4,"You're holding it!
"
	.GSTR STR?0,"You're not holding"
	.GSTR STR?877,"You're shaking uncontrollably from the cold. It won't be long before you are competely incapacitated."
	.GSTR STR?878,"You're shivering badly. If you don't find some warmth soon, it's hard to see how you can go on."
	.GSTR STR?638,"You're standing in the elevator of the apartment building..."
	.GSTR STR?546,"You're standing on Besnap Street, just outside the entrance to Riznik's Antique Shop. The crowd here continues to push eastward toward Ostnitz Square, but you can continue westward to a less congested spot."
	.GSTR STR?594,"You're standing outside of a prestigious apartment building. Two policemen guard the entrance as added security for the afternoon's events. The street here continues north and south, and the square lies directly to your east."
	.GSTR STR?876,"You're starting to feel a little weak and confused; it occurs to you that you won't last very long unless you stop the bleeding from your wounded left arm."
	.GSTR STR?11,"You're too far away to do that."
	.GSTR STR?130,"You've been spotted by one of the guards! You turn to run, but he fires a warning shot. You spin around, and in a moment the two guards have you in  their grasp. The third man approaches more slowly. ""Ah, we meet again!"" he begins, ""It is so awfully good to see you!"" He motions to the guards, who carry you to the waiting car, then throw you into the trunk."
	.GSTR STR?880,"You've got quite a chill; you must move now to keep warm, but even this is not enough."
	.GSTR STR?873,"You've gotten to the point where you must stop and rest briefly after every few dozen steps. Unless you stop the blood loss soon, you will collapse."
	.GSTR STR?30,"You've made enough noise to attract the guard's attention! He fires a warning shot, alerting the other guards, who rapidly approach with their weapons drawn..."
	.GSTR STR?686,"Your camera can be used for more than tourist shots."
	.GSTR STR?7,"Your sanity is coming into question. Perhaps it is the blood loss."
	.GSTR STR?507,"Your situation is serious, but not desperate."
	.GSTR STR?879,"Your teeth start to chatter from the cold; you are clearly slowing down, both physically and mentally."
	.ENDI
