"[RIDX: 2584]"

<CONSTANT RELEASEID 1> <VERSION EZIP>

<FREQUENT-WORDS?>

<INSERT-FILE "macros" T>
<INSERT-FILE "syntax" T>
<INSERT-FILE "misc" T>
<INSERT-FILE "parser" T>
<INSERT-FILE "verbs" T>
<INSERT-FILE "events" T>
<INSERT-FILE "people" T>
<INSERT-FILE "places" T>
<INSERT-FILE "things" T>

<INSERT-FILE "annotation_utils" T>

<PROPDEF SIZE 0>
<PROPDEF CAPACITY 0>
<PROPDEF MASS 0>
<PROPDEF VALUE 0>